Repository 2factorauth/twofactorauth, pull requests merged in 2018-10, with the labels that each got.

#3457 Remove Patelco Credit Union
  _data/banking.yml
Labels: updated site

#3469 Update Robinhood doc
  _data/investing.yml
Labels: updated site

#3480 Update Hostens doc URL
  _data/hosting.yml
Labels: updated site

#3365 Add KnowBe4
  _data/education.yml
  img/education/knowbe4.png
Labels: new site

#3449 Add Duke University
  _data/education.yml
  img/education/duke.png
Labels: new site

#3446 Remove Mastodon
  _data/social.yml
  img/social/mastodon.png
Labels: updated site

#3485 statuspage.io changed their twitter handle
  _data/developer.yml
Labels: updated site

#3471 Mobile: stop opening all categories
  css/base.scss
Labels: enhancement

#3493 Update Sentry's urls
  _data/developer.yml
Labels: updated site

#3484 Add HackerOne exception text
  _data/security.yml
Labels: updated site

#3489 Update Commonwealth Bank of Australia 2FA Status
  _data/banking.yml
Labels: updated site

#3477 Update US Bank 2FA status
  _data/banking.yml
Labels: updated site

#2942 Add Allegro
  _data/retail.yml
  img/retail/allegro.png
Labels: new site

#3451 Add SailPoint
  _data/identity.yml
  img/identity/sailpoint.png
Labels: new site

#2973 Add National Australia Bank (NAB)
  _data/banking.yml
  img/banking/nab.png
Labels: new site

#3491 Fix input search lag via debounced keyup function
  js/app.js
Labels: enhancement

#3490 Update Adobe 2FA status
  _data/other.yml
Labels: updated site

#2945 Add NASA Federal Credit Union
  _data/banking.yml
  img/banking/nasafederalcu.png
Labels: new site

#3315 Add Toontown Rewritten, Wizard101
  _data/gaming.yml
  img/gaming/toontownrewritten.png
  img/gaming/wizard101.png
Labels: new site

#2985 Add BTC Markets
  _data/cryptocurrencies.yml
  img/cryptocurrencies/btcmarkets.png
Labels: new site

#3524 StatusCake is supporting software TFA
  _data/developer.yml
Labels: updated site

#3514 Update University of Michigan doc
  _data/education.yml
Labels: updated site

#3518 Update ActiveCollab URL
  _data/task.yml
Labels: updated site

#3517 Update Xapo doc
  _data/cryptocurrencies.yml
Labels: updated site

#3227 Add Coinut
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinut.png
Labels: new site
