Repository 2factorauth/twofactorauth, pull requests merged in 2018-12, with the labels that each got.

#3569 Update transportation images
  img/transport/aircanada.png
  img/transport/alaska.png
  img/transport/ba.png
  img/transport/frontier.png
  img/transport/lufthansa.png
  img/transport/sj.png
  img/transport/spirit.png
Labels: enhancement

#3567 Update Uber 2FA status and logo
  _data/transport.yml
  img/transport/uber.png
Labels: updated site

#3306 Add Booking.com
  _data/other.yml
  img/other/bookingcom.png
Labels: new site

#3544 Remove phone auth from Guild Wars 2
  _data/gaming.yml
Labels: updated site

#3563 Add Acquia
  _data/hosting.yml
  img/hosting/acquia.png
Labels: new site

#3327 Add Purdue
  _data/education.yml
  img/education/purdue.png
Labels: new site

#3513 Add BitcoinTrade
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitcointrade.png
Labels: new site

#3242 Fix up Notes Pages
  _layouts/default.html
  _layouts/secondary.html
  index.html
  notes/chase.html
  notes/fidelity.html
  notes/gree.html
  notes/img/schwab.png
  notes/index.html
  notes/internetbs.html
  notes/schwab.html
  providers.html
Labels: enhancement

#3439 Update fidelity logo in /notes
  notes/img/fidelity.png
Labels: updated site

#3574 Allow both 644 and 664 permissions on images
  verify.rb
Labels: bug fix, enhancement

#3577 Add Crowdin documentation
  _data/developer.yml
Labels: updated site

#3573 Update Keeper 2FA status
  _data/identity.yml
Labels: updated site

#3575 Add ICICI bank
  _data/banking.yml
  img/banking/icici.png
Labels: new site

#3534 Remove DediServe
  _data/hosting.yml
  img/hosting/dediserve.png
Labels: remove site

#3593 Add SimpliSafe
  _data/iot.yml
  img/iot/simplisafe.png
Labels: new site

#3587 Fix figma documentation
  _data/other.yml
Labels: updated site

#3588 Fix bitpay doc
  _data/cryptocurrencies.yml
Labels: updated site

#3589 Remove Greenhost doc
  _data/hosting.yml
Labels: updated site

#3596 Add BRA
  _data/transport.yml
  img/transport/bra.png
Labels: new site

#3591 Update ECU doc
  _data/education.yml
Labels: updated site

#3590 Update Purdue doc
  _data/education.yml
Labels: updated site

#3600 Moving BCA doc to https
  _data/banking.yml
Labels: updated site

#3592 Update Gandi doc
  _data/domains.yml
Labels: updated site

#3597 Add Rocket Mortgage
  _data/finance.yml
  img/finance/rocketmortgage.png
Labels: new site

#3316 Add Surfshark
  _data/security.yml
  img/security/surfshark.png
Labels: new site
