Repository 2factorauth/twofactorauth, pull requests merged in 2018-09, with the labels that each got.

#3334 Fix GitHub corner clickable area
  css/corner.scss
  index.html
Labels: enhancement

#3408 Add digitec
  _data/retail.yml
  img/retail/digitec.png
Labels: new site

#3425 Update Dwolla doc
  _data/payments.yml
Labels: updated site

#3423 Add SiteGround
  _data/hosting.yml
  img/hosting/siteground.png
Labels: new site

#3427 update justworks doc
  _data/finance.yml
Labels: updated site

#3428 update dell to https
  _data/retail.yml
Labels: updated site

#3433 Add A2 Hosting
  _data/hosting.yml
  img/hosting/a2hosting.png
Labels: new site

#3429 Remove campbx
  _data/cryptocurrencies.yml
  img/cryptocurrencies/campbx.png
Labels: updated site

#3430 Update fortrabbit doc
  _data/cloud.yml
Labels: updated site

#3432 Update Signal doc
  _data/communication.yml
Labels: updated site

#3434 Update Kraken doc
  _data/cryptocurrencies.yml
Labels: updated site

#3435 Update Autodesk doc
  _data/other.yml
Labels: updated site

#3404 Add PassHub
  _data/identity.yml
  img/identity/passhub.png
Labels: new site

#3384 Add localethereum
  _data/cryptocurrencies.yml
  img/cryptocurrencies/localethereum.png
Labels: new site

#3165 Update IRS to include SMS and software 2FA
  _data/government.yml
Labels: updated site

#3431 Remove Openprovider doc
  _data/domains.yml
Labels: updated site

#3436 Update MongoDB Cloud Manager doc
  _data/developer.yml
Labels: updated site

#3443 Remove builtwith from other and doc
  _data/developer.yml
  _data/other.yml
  img/other/builtwith.png
Labels: updated site

#3442 Remove DBBL facebook tag
  _data/banking.yml
Labels: updated site

#3445 Update SecureSafe doc
  _data/identity.yml
Labels: updated site

#3455 Rubocop fixes
  verify.rb
Labels: bug fix

#3440 Update SmartThings
  _data/iot.yml
Labels: updated site

#3444 Update Xapo doc
  _data/cryptocurrencies.yml
Labels: updated site

#3441 Update Hexonet doc
  _data/domains.yml
Labels: updated site

#3450 Add Funding Circle
  _data/finance.yml
  img/finance/fundingcircle.png
Labels: new site

#3413 Mobile layout improvements
  _includes/mobile-table.html
  css/base.scss
Labels: enhancement

#3461 Update VentraIP Australia 2FA status
  _data/hosting.yml
Labels: updated site

#3463 Add Buddy
  _data/developer.yml
  img/developer/buddy.png
Labels: new site

#3470 Update ING AT
  _data/banking.yml
Labels: updated site

#3465 Fix withings (again)
  _data/health.yml
  img/health/nokiahealth.png
  img/health/withings.png
Labels: updated site

#3474 Remove delicious
  _data/other.yml
  img/other/delicious.png
Labels: updated site
