Repository 2factorauth/twofactorauth, pull requests merged in 2018-08, with the labels that each got.

#3335 Update evernote docs URL
  _data/backup.yml
Labels: updated site

#3342 Correct Starling Bank misspelling
  _data/banking.yml
Labels: updated site

#3346 Add Crowdin
  _data/developer.yml
  img/developer/crowdin.png
Labels: new site

#3353 Add Plastiq
  _data/payments.yml
  img/payments/plastiq.png
Labels: new site

#3357 Update USAA 2FA options
  _data/banking.yml
Labels: updated site

#3361 Credit Karma Supports Phone Call 2FA
  _data/finance.yml
Labels: updated site

#3381 Update DigitalOcean 2FA status and doc
  _data/cloud.yml
Labels: updated site

#3386 Update Algolia doc link
  _data/developer.yml
Labels: updated site

#3378 Add Laravel Forge
  _data/cloud.yml
  img/cloud/forge.png
Labels: new site

#3388 Update WageWorks 2FA status
  _data/other.yml
Labels: updated site

#3397 Update Blizzard added exception for software 2FA
  _data/gaming.yml
Labels: updated site

#3391 Update Tidal (added email)
  _data/entertainment.yml
Labels: updated site

#3392 Add Twitch exception
  _data/entertainment.yml
Labels: updated site

#3389 Add HackerOne
  _data/security.yml
  img/security/hackerone.png
Labels: new site

#3363 Add KnownHost
  _data/hosting.yml
  img/hosting/knownhost.png
Labels: new site

#3394 Add Metorik
  _data/finance.yml
  img/finance/metorik.png
Labels: new site

#3402 Add Strava
  _data/health.yml
  img/health/strava.png
Labels: new site

#3366 Update easyDNS 2FA status and doc
  _data/domains.yml
  img/domains/easydns.png
Labels: updated site

#3411 Update Instagram to include software.
  _data/social.yml
Labels: updated site

#3403 Create code of conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#3414 Add Alexa top 200k site addition constraint to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement
