Repository 2factorauth/twofactorauth, pull requests merged in 2018-06, with the labels that each got.

#3167 Update semantic-ui
  _data/sections.yml
  _layouts/default.html
  _layouts/secondary.html
  index.html
  notes/chase.html
  notes/fidelity.html
  notes/gree.html
  notes/internetbs.html
  notes/schwab.html
  providers.html
Labels: bug fix

#3179 Add Pushover
  _data/developer.yml
  img/developer/pushover.png
Labels: new site

#3142 Add Ripe NCC
  _data/other.yml
  img/other/ripe.png
Labels: new site

#3207 Add Moneybird
  _data/finance.yml
  img/finance/moneybird.png
Labels: new site

#3240 Update Citibank (AU) TFA status
  _data/banking.yml
Labels: updated site

#3221 Add Google Hangouts and Digidentity
  _data/communication.yml
  _data/identity.yml
  img/communication/hangouts.png
Labels: new site

#3176 Add Scryfall
  _data/gaming.yml
  img/gaming/scryfall.png
Labels: new site

#3194 Add Gemini
  _data/cryptocurrencies.yml
  img/cryptocurrencies/gemini.png
Labels: new site

#3186 Update Plurk
  _data/social.yml
Labels: updated site

#3028 Add chocolatey
  _data/developer.yml
  img/developer/chocolatey.png
Labels: new site

#3188 remove use of .each
  js/app.js
Labels: enhancement

#3022 Add IDentité Numérique
  _data/identity.yml
  img/identity/identitenumerique.png
Labels: new site

#2931 Add Changelly
  _data/cryptocurrencies.yml
  img/cryptocurrencies/changelly.png
Labels: new site

#2861 Add SaferVPN.com
  _data/security.yml
  img/security/safervpn.png
Labels: new site

#2745 Add PosteItaliane
  _data/banking.yml
  img/banking/posteitaliane.png
Labels: new site

#2848 Add Bitflyer and Bithumb
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitflyer.png
  img/cryptocurrencies/bithumb.png
Labels: new site

#2850 Add BTC Pop and BX Thailand
  _data/cryptocurrencies.yml
  img/cryptocurrencies/btcpop.png
  img/cryptocurrencies/bxthailand.png
Labels: new site

#2819 Add Snapdeal
  _data/retail.yml
  img/retail/snapdeal.png
Labels: new site

#2722 Add Deutsche Telekom
  _data/utilities.yml
  img/utilities/deutschetelekom.png
Labels: new site

#3002 Add Deezer
  _data/entertainment.yml
  img/entertainment/deezer.png
Labels: new site

#2984 Add Ergon Energy
  _data/utilities.yml
  img/utilities/ergon.png
Labels: new site

#3245 Add Firefox
  _data/other.yml
  img/other/firefox.png
Labels: new site

#2860 Add ProtonVPN and PureVPN
  _data/security.yml
  img/security/protonvpn.png
  img/security/purevpn.png
Labels: new site

#3251 finance: Add Carta
  _data/finance.yml
  img/finance/carta.png
Labels: new site

#2776 Add SixthContinent
  _data/payments.yml
  img/payments/sixthcontinent.png
Labels: new site

#3279 Update ProtonVPN TFA status
  _data/security.yml
Labels: updated site

#3119 Add AirBank
  _data/banking.yml
  img/banking/airbank.png
Labels: new site

#3286 add hardware to twitter
  _data/social.yml
Labels: updated site
