Repository 2factorauth/twofactorauth, pull requests merged in 2018-11, with the labels that each got.

#3496 Add Dynu
  _data/domains.yml
  img/domains/dynu.png
Labels: new site

#3504 Add Cigna
  _data/health.yml
  img/health/cigna.png
Labels: new site

#3508 Add HubSpot
  _data/communication.yml
  img/communication/hubspot.png
Labels: new site

#3525 Add Avanza
  _data/banking.yml
  img/banking/avanza.png
Labels: new site

#3519 Add Linxo
  _data/finance.yml
  img/finance/linxo.png
Labels: new site

#3510 Update XING 2FA status
  _data/social.yml
Labels: updated site

#3507 Add Mint doc
  _data/finance.yml
Labels: updated site

#3210 Add Devolutions Remote Desktop Manager
  _data/remote.yml
  img/remote/RemoteDesktopManager.png
Labels: new site

#3522 Update ExpressVPN 2FA status
  _data/security.yml
Labels: updated site

#3527 Update Dreamhost doc
  _data/hosting.yml
Labels: updated site

#3530 Remove Pacific Continental
  _data/banking.yml
  img/banking/pcb.png
Labels: updated site

#3528 Remove Scottrade
  _data/investing.yml
  img/investing/scottrade.png
Labels: updated site

#3500 Update Addiko Bank doc
  _data/banking.yml
Labels: updated site

#3533 Add buildkite
  _data/developer.yml
  img/developer/buildkite.png
Labels: new site

#2924 Update Virginia Commonwealth University doc
  _data/education.yml
Labels: updated site

#3506 Add Hostnet
  _data/hosting.yml
  img/hosting/hostnet.png
Labels: new site

#3536 Remove OneLogin 2FA provider
  _data/identity.yml
  img/identity/onelogin.png
Labels: remove site

#3503 Add Rabobank
  _data/banking.yml
  img/banking/rabobank.png
Labels: new site

#3347 Add Betvictor
  _data/betting.yml
  _data/sections.yml
  img/betting/betvictor.png
Labels: new section, new site

#3538 Add lowercase check for images
  _data/banking.yml
  _data/education.yml
  _data/hosting.yml
  _data/remote.yml
  img/banking/bochk.png
  img/banking/caisse_epargne.png
  img/banking/regionsbank.png
  img/banking/towerfcu.png
  img/banking/unifyfcu.png
  img/education/cod.png
  img/education/comptia.png
  img/hosting/planethoster.png
  img/remote/remotedesktopmanager.png
  websites_schema.yml
Labels: enhancement

#3515 Update Bitflyer doc
  _data/cryptocurrencies.yml
Labels: updated site

#3539 Add eset
  _data/security.yml
  img/security/eset.png
Labels: new site

#3332 Move OpenDNS from Security to Domains
  _data/domains.yml
  _data/security.yml
  img/domains/opendns.png
Labels: updated site

#3187 make use of Jekylls compression of scss/sass files
  _config.yml
Labels: enhancement

#3541 Update Mint doc
  _data/finance.yml
Labels: updated site

#3548 Update Coinjar doc
  _data/cryptocurrencies.yml
Labels: updated site

#3511 Add Mercado Bitcoin
  _data/cryptocurrencies.yml
  img/cryptocurrencies/mercadobitcoin.png
Labels: new site

#2781 Add Zalando
  _data/retail.yml
Labels: new site

#3553 Update Oderland
  _data/hosting.yml
Labels: updated site

#3495 Rename Bank Zachodni WBK to Santander PL
  _data/banking.yml
  img/banking/bzwbk.png
Labels: updated site

#3498 Update Basecamp 2FA status
  _data/communication.yml
Labels: updated site

#3551 Add Panic Sync
  _data/developer.yml
  img/developer/panic.png
Labels: new site

#3358 Add Exact Online
  _data/finance.yml
  img/finance/exact.png
Labels: new site

#3557 Add HostUS
  _data/hosting.yml
  img/hosting/hostus.png
Labels: new site

#3558 Add University of Washington
  _data/education.yml
  img/education/uw.png
Labels: new site

#3529 Remove Softlayer
  _data/hosting.yml
  img/hosting/softlayer.png
Labels: remove site

#3561 Move wex to new tld
  _data/cryptocurrencies.yml
Labels: updated site

#3559 Update Leaseweb doc
  _data/cloud.yml
Labels: updated site

#3560 Update ECU doc
  _data/education.yml
Labels: updated site
