Repository 2factorauth/twofactorauth, pull requests merged in 2018-07, with the labels that each got.

#3058 Add Wykop
  _data/social.yml
  img/social/wykop.png
Labels: new site

#3250 Update Etsy
  _data/retail.yml
Labels: updated site

#3282 Add Czech goverment messaging system
  _data/government.yml
  img/government/cz_datovky.png
Labels: new site

#3202 Remove Bank of America hardware token support
  _data/banking.yml
Labels: updated site

#3294 Update Wikipedia/Wikimedia entry
  _data/other.yml
Labels: please add/update site

#3299 Add Cacoo
  _data/developer.yml
  img/developer/cacoo.png
Labels: new site

#3297 Add Bitdefender
  _data/security.yml
  img/security/bitdefender.png
Labels: new site

#3298 Add Blau.de
  _data/utilities.yml
  img/utilities/blau.png
Labels: new site

#3295 Add AVG
  _data/security.yml
  img/security/avg.png
Labels: new site

#3310 Update TD Canada Trust to have SMS and Phone 2FA
  _data/banking.yml
Labels: updated site

#3308 Update SAASPASS
  _data/identity.yml
Labels: updated site

#3214 Add Atlassian Cloud
  _data/developer.yml
  img/developer/atlassian.png
Labels: new site

#3287 Add SF Fire Credit Union
  _data/banking.yml
Labels: new site

#3320 Add Trade Me
  _data/retail.yml
  img/retail/trademe.png
Labels: new site

#3322 Add Capsule
  _data/communication.yml
  img/communication/capsule.png
Labels: new site

#3317 Add Recurly
  _data/payments.yml
  img/payments/recurly.png
Labels: new site

#3314 Update Navy FCU 2FA status
  _data/banking.yml
Labels: updated site

#3303 Add Simplii Financial
  _data/banking.yml
  img/banking/simplii.png
Labels: new site

#3329 Update Indeed
  _data/other.yml
Labels: updated site

#3337 Add Monzo
  _data/banking.yml
  img/banking/monzobank.png
Labels: new site
