Repository 2factorauth/twofactorauth, pull requests merged in 2019-09, with the labels that each got.

#3987 Add University of Notre Dame
  _data/education.yml
  img/education/nd.png
Labels: new site

#3980 Update Fiverr 2FA status
  _data/other.yml
Labels: updated site

#3979 Add emails for some VPN Providers
  _data/vpn.yml
Labels: updated site

#3969 Add dmarcanalyzer.com
  _data/security.yml
  img/security/dmarcanalyzer.png
Labels: new site

#3714 Fix Sierra name and handles
  _data/retail.yml
  img/retail/sierra.png
Labels: updated site

#3988 Updated Jottacloud
  _data/backup.yml
Labels: updated site

#3990 update 2fa for web.de email provider
  _data/email.yml
Labels: updated site

#3977 Update Evernote exception
  _data/backup.yml
Labels: updated site

#3966 Add British Telecom (BT)
  _data/utilities.yml
  img/utilities/bt.png
Labels: new site

#3998 Update 2FA AdGuard documentation
  _data/security.yml
Labels: updated site

#4000 Remove Splitska banka
  _data/banking.yml
  img/banking/splitska.png
Labels: remove site

#3999 Delete Curse and Code School and add Pluralsight
  _data/education.yml
  _data/gaming.yml
  img/education/codeschool.png
  img/education/pluralsight.png
  img/gaming/curse.png
Labels: remove site

#4001 Add OTP banka
  _data/banking.yml
  img/banking/otpbanka.png
Labels: new site

#3994 Add emails for some services
  _data/backup.yml
  _data/communication.yml
  _data/developer.yml
  _data/education.yml
  _data/entertainment.yml
  _data/health.yml
  _data/other.yml
  _data/social.yml
  _data/task.yml
Labels: updated site

#4014 Removed exception for Tutanota + update doc link
  _data/email.yml
Labels: updated site

#3867 Add Segment
  _data/hosting.yml
  img/hosting/segment.png
Labels: new site

#3986 Add Karlsruher Institut für Technologie
  _data/education.yml
  img/education/kit.png
Labels: new site

#4033 Add eventbrite
  _data/social.yml
  img/social/eventbrite.png
Labels: new site

#4040 Add Files.com
  _data/backup.yml
  img/backup/files.png
Labels: new site

#4019 Add ReadMe
  _data/developer.yml
  img/developer/readme.png
Labels: new site

#4022 Added TSP.gov
  _data/government.yml
  img/government/tsp.png
Labels: new site

#4021 Update YNAB
  _data/finance.yml
Labels: updated site
