Repository 2factorauth/twofactorauth, pull requests merged in 2019-08, with the labels that each got.

#3958 Update VOIP.ms 2FA
  _data/utilities.yml
Labels: updated site

#3956 Update Braintree hardware 2FA
  _data/payments.yml
Labels: updated site

#3955 Add CoinTracking
  _data/cryptocurrencies.yml
  img/cryptocurrencies/cointracking.png
Labels: new site

#3951 Add SoFi
  _data/banking.yml
  img/banking/sofi.png
Labels: new site

#3946 Sticky table header
  css/base.scss
Labels: enhancement

#3965 Update login.gov doc
  _data/government.yml
Labels: updated site

#3904 Upgraded various links to HTTPS
  _data/backup.yml
  _data/banking.yml
  _data/developer.yml
  _data/education.yml
  _data/gaming.yml
  _data/government.yml
Labels: updated site

#3719 Add NationBuilder
  _data/other.yml
  img/other/nationbuilder.png
Labels: new site

#3970 Add ICDSoft
  _data/hosting.yml
  img/hosting/icdsoft.png
Labels: new site

#3960 Add dmarcian
  _data/security.yml
  img/security/dmarcian.png
Labels: new site

#3976 Remove HipChat
  _data/communication.yml
  img/communication/hipchat.png
Labels: remove site

#3971 Update doc URL for Salesforce
  _data/communication.yml
  img/communication/salesforce.png
Labels: updated site
