Repository 2factorauth/twofactorauth, pull requests merged in 2019-01, with the labels that each got.

#3605 Add exception to Pinterest
  _data/social.yml
Labels: updated site

#3608 Remove Hyper.sh
  _data/cloud.yml
  img/cloud/hypersh.png
Labels: remove site

#3243 Rename Atlas to TFE, add Vagrant Cloud
  _data/developer.yml
  img/developer/hashicorp-atlas.png
  img/developer/hashicorp-terraform-enterprise.png
  img/developer/hashicorp-vagrant-cloud.png
Labels: new site

#3610 Add garmin.com
  _data/health.yml
  img/health/garmin.png
Labels: new site

#3612 Remove Context.io
  _data/developer.yml
  img/developer/contextio.png
Labels: remove site

#3609 Move Tibia to HTTPS
  _data/gaming.yml
Labels: updated site

#3616 Add Ring.com to iot.yml
  _data/iot.yml
  img/iot/ringcom.png
Labels: new site

#3618 Update cosmolex doc
  _data/other.yml
Labels: updated site

#3619 Add McAfee to security. Closes #3611
  _data/security.yml
  img/security/mcafee.png
Labels: new site

#3621 Add hardware 2FA for GoDaddy
  _data/domains.yml
Labels: updated site

#3624 Update Appveyor 2FA status
  _data/developer.yml
Labels: updated site

#3622 Update Garena URL
  _data/gaming.yml
Labels: updated site

#3617 Add Wyze
  _data/iot.yml
  img/iot/wyze.png
Labels: new site

#3623 Add hardware to login.gov
  _data/government.yml
Labels: updated site

#3628 Add ClickUp
  _data/task.yml
  img/task/clickup.png
Labels: new site

#3627 Add FreeTaxUSA
  _data/finance.yml
  img/finance/freetaxusa.png
Labels: new site

#3630 Fix sonic doc
  _data/utilities.yml
Labels: updated site

#3615 Add Boursorama
  _data/banking.yml
  img/banking/boursorama.png
Labels: new site

#3635 Add Remember The Milk
  _data/task.yml
  img/task/rememberthemilk.png
Labels: new site

#3636 Add documentation URL for XING
  _data/social.yml
Labels: updated site

#3633 Add GroupMe
  _data/communication.yml
  img/communication/groupme.png
Labels: new site

#3640 added Republic Wireless
  _data/utilities.yml
  img/utilities/rw.png
Labels: new site

#3626 Fix desktop alignment and buttons
  _includes/desktop-table.html
  css/base.scss
Labels: bug fix

#3647 Update Threat X
  _data/security.yml
  img/security/threatx.png
Labels: updated site

#3584 Add Couchsurfing
  _data/other.yml
  img/other/couchsurfing.png
Labels: new site

#3670 Update Quickbooks Online doc link
  _data/finance.yml
Labels: updated site

#3668 Update Rebel facebook handle
  _data/domains.yml
Labels: updated site

#3669 Remove AeroFS
  _data/backup.yml
  img/backup/aerofs.png
Labels: remove site

#3648 Update Questrade
  _data/investing.yml
Labels: updated site

#3067 Output the proper order of the sites when not alphabetical
  Gemfile
  verify.rb
Labels: enhancement

#3178 Update TD Ameritrade TFA status
  _data/investing.yml
Labels: updated site

#3305 Add Carnegie Mellon University
  _data/education.yml
  img/education/cmu.png
Labels: new site

#3656 Add .ruby-version to match travis version
  .ruby-version
  .travis.yml
  Gemfile
  Rakefile
  verify.rb
Labels: enhancement

#2907 Update Discover
  _data/banking.yml
Labels: updated site

#3598 Add MacStadium
  _data/cloud.yml
  img/cloud/macstadium.png
Labels: new site
