Repository 2factorauth/twofactorauth, pull requests merged in 2019-11, with the labels that each got.

#4249 Update Brightbox
  _data/cloud.yml
Labels: updated site

#4239 Update Upwork
  _data/other.yml
Labels: updated site

#4235 Rename+Update American Funds
  _data/investing.yml
  img/investing/capitalgroup.png
Labels: updated site

#4267 Add Hermes DE
  _data/other.yml
  img/other/hermes.png
Labels: new site

#4263 Update ICICI
  _data/banking.yml
Labels: updated site

#4257 Reference TinyPNG instead of OptiPNG
  CONTRIBUTING.md
Labels: enhancement

#4221 Add University of Delaware
  _data/education.yml
  img/education/udel.png
Labels: new site

#4217 Add Close
  _data/communication.yml
  img/communication/close.png
Labels: new site

#4216 Update Namecheap
  _data/domains.yml
Labels: updated site

#4203 Add BunnyCDN
  _data/hosting.yml
  img/hosting/bunnycdn.png
Labels: new site

#4253 Update HSBC
  _data/banking.yml
Labels: updated site

#4241 Update VyStar Credit Union
  _data/banking.yml
Labels: updated site

#4237 Update Square Cash
  _data/payments.yml
Labels: updated site

#4161 Update N26
  _data/banking.yml
Labels: updated site

#4251 Update Best Buy, uses 2FA
  _data/retail.yml
Labels: updated site

#4262 Add BBBank
  _data/banking.yml
  img/banking/bbbank.png
Labels: new site

#4096 Add Hotels and Accommodations Category with new site IHG, and move airbnb & hilton honors.
  _data/hotels.yml
  _data/other.yml
  _data/sections.yml
  img/hotels/airbnb.png
  img/hotels/hilton.png
  img/hotels/ihg.png
  img/hotels/marriott.png
Labels: new category, new site

#4274 Add Hebrew language support
  _data/languages.yml
Labels: enhancement

#4269 Add BlockFi
  _data/cryptocurrencies.yml
  img/cryptocurrencies/blockfi.png
Labels: new site

#4248 Add ClickPay
  _data/payments.yml
  img/payments/clickpay.png
Labels: new site

#4294 Update Facebook exception
  _data/social.yml
Labels: updated site

#4291 Update Desjardins
  _data/banking.yml
Labels: updated site

#4289 Move Booking.com, Couchsurfing to H&A
  _data/hotels.yml
  _data/other.yml
  img/hotels/bookingcom.png
  img/hotels/couchsurfing.png
Labels: updated site

#4292 Move DoorDash, Postmates to Food
  _data/food.yml
  _data/other.yml
  img/food/doordash.png
  img/food/postmates.png
Labels: updated site

#4284 Update Hint Health
  _data/health.yml
Labels: updated site

#4277 Add Semantic-ui website for icon usage
  CONTRIBUTING.md
Labels: enhancement

#4307 Update JetBrains
  _data/developer.yml
Labels: new site

#4302 Update Registro.br
  _data/domains.yml
Labels: updated site

#4297 Add jpc
  _data/retail.yml
  img/retail/jpc.png
Labels: new site

#4296 Update Web.de
  _data/email.yml
Labels: updated site

#4283 Add Contentful
  _data/other.yml
  img/other/contentful.png
Labels: new site

#4311 Rename Google Wallet to Google Pay
  _data/payments.yml
  img/payments/googlepay.png
  img/payments/googlewallet.png
Labels: updated site

#4322 Update Online
  _data/hosting.yml
Labels: updated site

#4323 Removed deprecated entries
  _data/cryptocurrencies.yml
  _data/developer.yml
  _data/finance.yml
  _data/health.yml
  _data/retail.yml
  img/cryptocurrencies/cryptopia.png
  img/developer/cloud9.png
  img/finance/noddle.png
  img/health/healthvault.png
  img/retail/dwi.png
Labels: remove site

#4278 Add Office Depot
  _data/retail.yml
  img/retail/officedepot.png
Labels: new site

#4268 Add Park.io
  _data/domains.yml
  img/domains/parkio.png
Labels: new site

#4259 Add ViaBTC
  _data/cryptocurrencies.yml
  img/cryptocurrencies/viabtc.png
Labels: new site

#4327 Move Pushcoin
  _data/education.yml
  _data/finance.yml
  img/finance/pushcoin.png
Labels: updated site

#4331 Add automatic-rebase GH app
  .github/workflows/rebase.yml
Labels: enhancement

#4326 Add Staples
  _data/retail.yml
  img/retail/staples.png
Labels: new site

#4325 Add RCWilley
  _data/retail.yml
  img/retail/rcwilley.png
Labels: new site

#4328 Amundi ampersand correction
  _data/finance.yml
Labels: updated site

#4288 Add Bremer Straßenbahn AG
  _data/transport.yml
  img/transport/bsag.png
Labels: new site

#4316 Add E-POST
  _data/communication.yml
  img/communication/epost.png
Labels: new site

#4318 Update Gatehub
  _data/cryptocurrencies.yml
Labels: updated site

#4299 Add EVENTIM
  _data/retail.yml
  img/retail/eventim.png
Labels: new site

#4335 Removing Phone Number requirement from twitter exceptions
  _data/social.yml
Labels: updated site

#4337 Update badge style
  README.md
Labels: enhancement

#4332 Add WePay
  _data/payments.yml
  img/payments/wepay.png
Labels: new site

#4315 Move entries from Other to suitable categories
  _data/communication.yml
  _data/legal.yml
  _data/other.yml
  _data/remote.yml
  _data/social.yml
  _data/task.yml
  img/communication/faxplus.png
  img/legal/basiscode.png
  img/legal/cosmolex.png
  img/legal/everlaw.png
  img/remote/directadmin.png
  img/social/postcrossing.png
  img/task/airtable.png
Labels: multiple sites, updated site

#4317 Update BitcoinTrade
  _data/cryptocurrencies.yml
Labels: updated site

#4280 Add Gerber Life Insurance
  _data/finance.yml
  img/finance/gerberlife.png
Labels: new site

#4276 Add remitano
  _data/cryptocurrencies.yml
  img/cryptocurrencies/remitano.png
Labels: new site

#4340 Add more PR checks
  .github/workflows/jekyll.yml
  .github/workflows/pr.yml
  .github/workflows/ruby.yml
  .tests/alexa.rb
  .tests/alexa.sh
  .tests/twitter.rb
  .tests/twitter.sh
  .tests/verify.rb
  .travis.yml
  Rakefile
Labels: enhancement

#4348 Change name of LocalEthereum
  _data/cryptocurrencies.yml
  img/cryptocurrencies/localcryptos.png
  img/cryptocurrencies/localethereum.png
Labels: updated site

#4347 Remove Zag Bank
  _data/banking.yml
  img/banking/zagbank.png
Labels: remove site

#4346 Update State Farm
  _data/banking.yml
Labels: updated site

#4344 Update LendingClub
  _data/banking.yml
Labels: updated site

#4341 Update DBS Bank Singapore
  _data/banking.yml
Labels: updated site

#4330 Update GOG documentation URL
  _data/gaming.yml
Labels: updated site

#4223 Add Short.cm
  _data/social.yml
  img/social/shortcm.png
Labels: new site

#4351 Move PR checks from GH actions to Travis
  .github/workflows/pr.yml
  .tests/alexa.rb
  .tests/alexa.sh
  .tests/twitter.rb
  .tests/twitter.sh
  .travis.yml
Labels: bug

#4345 Update Openbank
  _data/banking.yml
Labels: updated site

#4261 Translate email subject
  _data/languages.yml
  _includes/desktop-table.html
  _includes/mobile-table.html
  index.html
Labels: enhancement

#4252 Adding CSOB bank
  _data/banking.yml
  img/banking/csob.png
Labels: new site

#4246 Add TransUnion
  _data/finance.yml
  img/finance/transunion.png
Labels: new site

#4355 Add Disney+
  _data/entertainment.yml
  img/entertainment/disneyplus.png
Labels: new site

#4362 Add Barnes & Noble
  _data/retail.yml
  img/retail/barnesandnoble.png
Labels: new site

#4361 Change Betting icon
  _data/sections.yml
Labels: enhancement

#3887 Add ScriptingHelpers
  _data/developer.yml
  img/developer/scriptinghelpers.png
Labels: new site

#4366 Add Facebook check
  .circleci/config.yml
  .tests/facebook.sh
  .tests/twitter.rb
  .tests/twitter.sh
Labels: enhancement

#4368 Clean up tests
  .circleci/config.yml
  .tests/alexa.sh
  .tests/facebook.sh
  .tests/twitter.rb
  .tests/twitter.sh
Labels: enhancement

#4265 Add Immowelt
  _data/other.yml
  img/other/immowelt.png
Labels: new site

#4264 Add Hamburger Verkehrsverbund
  _data/transport.yml
  img/transport/hvv.png
Labels: new site

#4360 Add Bank Leumi
  _data/banking.yml
  img/banking/leumi.png
Labels: new site

#4350 Update README.md
  README.md
Labels: enhancement

#4367 Add World4you
  _data/hosting.yml
  img/hosting/world4you.png
Labels: new site
