Repository 2factorauth/twofactorauth, pull requests merged in 2019-05, with the labels that each got.

#3830 Update multiple http to https links
  _data/backup.yml
  _data/banking.yml
  _data/cloud.yml
  _data/communication.yml
  _data/developer.yml
  _data/domains.yml
  _data/education.yml
  _data/email.yml
  _data/entertainment.yml
  _data/finance.yml
  _data/gaming.yml
  _data/health.yml
  _data/hosting.yml
  _data/security.yml
  _data/social.yml
  _data/task.yml
  _data/utilities.yml
Labels: updated site

#3850 Update 500px
  _data/social.yml
Labels: updated site

#3859 Update eBay
  _data/retail.yml
Labels: updated site

#3851 Update Black Desert Online
  _data/gaming.yml
Labels: updated site

#3841 Update SendGrid
  _data/communication.yml
  img/communication/sendgrid.png
Labels: updated site

#3842 Update Mint
  img/finance/mint.png
Labels: updated site

#3786 Update Todoist
  _data/task.yml
  img/task/todoist.png
Labels: updated site

#3844 Add Help Scout
  _data/other.yml
  img/other/helpscout.png
Labels: new site

#3857 Add Bohemia Interactive
  _data/gaming.yml
  img/gaming/bohemia.png
Labels: new site

#3853 Update ActiveCollab
  img/task/activecollab.png
Labels: updated site

#3825 Add AdGuard
  _data/security.yml
  img/security/adguard.png
Labels: new site

#3847 Remove WildStar
  _data/gaming.yml
  img/gaming/wildstar.png
Labels: remove site

#3819 Update Porkbun
  _data/domains.yml
Labels: updated site
