Repository 2factorauth/twofactorauth, pull requests merged in 2019-10, with the labels that each got.

#4046 23andme now supports 2fa
  _data/health.yml
Labels: updated site

#4028 Add Meistertask
  _data/task.yml
  img/task/meistertask.png
Labels: new site

#4032 Add Hilton
  _data/other.yml
  img/other/hilton.png
Labels: new site

#4025 Update Rabobank documentation link
  _data/banking.yml
Labels: updated site

#4035 Add DHL Deutschland
  _data/other.yml
  img/other/dhl.png
Labels: new site

#4044 Update Uptimerobot
  _data/developer.yml
  img/developer/uptimerobot.png
Labels: updated site

#3817 Update TransIP
  _data/hosting.yml
Labels: updated site

#3963 Update Vanguard
  _data/investing.yml
Labels: updated site

#4013 Update to Nationwide Building Society
  _data/banking.yml
Labels: updated site

#4062 Update xapo
  _data/cryptocurrencies.yml
Labels: updated site

#4061 Update login.gov doc
  _data/government.yml
Labels: updated site

#4060 Update Rebel facebook
  _data/domains.yml
Labels: updated site

#4058 Update America First CU Facebook
  _data/banking.yml
Labels: updated site

#4057 Update coincafe
  _data/cryptocurrencies.yml
Labels: updated site

#4059 Update Runtastic facebook
  _data/health.yml
Labels: updated site

#4056 Add President's Choice Financial
  _data/banking.yml
  img/banking/pcfinancial.png
Labels: new site

#4055 Add Youinvest
  _data/investing.yml
  img/investing/youinvest.png
Labels: new site

#4072 Remove InEx
  _data/finance.yml
  img/finance/inex.png
Labels: remove site

#4066 Remove MYDIGIPASS
  _data/identity.yml
  img/identity/mydigipass.png
Labels: remove site

#4067 Change Temple doc URL
  _data/education.yml
Labels: updated site

#4068 Remove Peerio
  _data/communication.yml
  img/communication/peerio.png
Labels: remove site

#4069 Remove Pogoplug
  _data/backup.yml
  img/backup/pogoplug.png
Labels: remove site

#4071 Remove Singlehop
  _data/cloud.yml
  img/cloud/singlehop.png
Labels: remove site

#4070 Change BTC BOX doc url
  _data/cryptocurrencies.yml
Labels: updated site

#4065 Add Grammarly
  _data/other.yml
  img/other/grammarly.png
Labels: new site

#4017 Updates
  _data/banking.yml
  _data/betting.yml
  _data/developer.yml
  _data/domains.yml
  img/betting/win2day.png
  img/developer/heapanalytics.png
  img/domains/epik.png
Labels: new site, updated site

#4009 Add ING-DiBa Deutschland
  _data/banking.yml
Labels: new site

#4102 Update Uber image
  img/transport/uber.png
Labels: updated site

#4105 Add all-inkl to Hosting
  _data/hosting.yml
  img/hosting/all-inkl.png
Labels: new site

#4099 Remove Time Warner Cable
  _data/utilities.yml
  img/utilities/timewarner.png
Labels: remove site

#3288 Update schwab 2fa instructions
  notes/schwab.html
Labels: updated site

#4106 Update Deutsche Kreditbank (DKB)
  _data/banking.yml
Labels: updated site

#4108 Remove Allegro software TFA
  _data/retail.yml
Labels: updated site

#4095 Add Glassdoor
  _data/social.yml
  img/social/glassdoor.png
Labels: new site

#4010 Add LPI (Linux Professional Institute)
  _data/education.yml
  img/education/lpi.png
Labels: new site

#4094 Add Yelp
  _data/social.yml
  img/social/yelp.png
Labels: new site

#4117 Reformat developer.yml
  _data/developer.yml
Labels: enhancement

#4126 Typo correction in CONTRIBUTING.MD
  CONTRIBUTING.md
Labels: bug

#4124 Add doc for ProtonVPN
  _data/vpn.yml
Labels: updated site

#4132 Update Communications category
  _data/communication.yml
Labels: updated site

#4131 Update Crypto Currencies category
  _data/cryptocurrencies.yml
  img/cryptocurrencies/anxpro.png
  img/cryptocurrencies/bitcoinsnorway.png
Labels: remove site, updated site

#4133 Update Cloud Computing category
  _data/cloud.yml
  img/cloud/profitbricks.png
Labels: remove site, updated site

#4138 Add HypoVereinsbank
  _data/banking.yml
  img/banking/hypovereinsbank.png
Labels: new site

#4135 Update Postbank
  _data/banking.yml
Labels: updated site

#4136 Update TARGOBANK
  _data/banking.yml
Labels: updated site

#4137 Update Sparkasse
  _data/banking.yml
Labels: updated site

#4121 Update WSL/Ubuntu requirements
  README.md
Labels: enhancement

#4129 Update comdirect
  _data/banking.yml
  img/banking/comdirect.png
Labels: updated site

#4151 Update GitHub icon
  img/developer/github.png
Labels: updated site

#3820 Add Filmweb
  _data/entertainment.yml
  img/entertainment/filmweb.png
Labels: new site

#4120 Add FAX.PLUS
  _data/other.yml
  img/other/faxplus.png
Labels: new site

#4109 Update Lyft image
  img/transport/lyft.png
Labels: updated site

#4128 Update Sparda Banken
  _data/banking.yml
Labels: updated site

#4130 Update Commerzbank
  _data/banking.yml
Labels: updated site

#4154 Update Starbucks
  _data/food.yml
Labels: updated site

#3889 Add Avast
  _data/security.yml
  img/security/avast.png
Labels: new site

#4192 Add Github Actions CI
  .github/workflows/jekyll.yml
Labels: enhancement

#4188 Add Twitter card
  _config.yml
  _layouts/default.html
Labels: enhancement

#4165 Update Docker
  _data/developer.yml
Labels: updated site

#4194 Update packagist 2FA support
  _data/developer.yml
Labels: updated site

#4197 Add Lake Michigan Credit Union
  _data/banking.yml
  img/banking/lakemichigancreditunion.png
Labels: new site

#4193 Update DHL Deutschland
  _data/other.yml
Labels: updated site

#4098 Update Fidelity documentation
  _data/investing.yml
  notes/fidelity.html
Labels: updated site

#4195 Add Sunsuper
  _data/investing.yml
  img/investing/sunsuper.png
Labels: new site

#4200 Update verify.rb
  verify.rb
Labels: enhancement

#4211 Add College Board
  _data/education.yml
  img/education/collegeboard.png
Labels: new site

#4183 Add sapo
  _data/email.yml
  img/email/sapo.png
Labels: new site

#4187 Update ImmobilienScout24
  _data/other.yml
Labels: updated site

#4173 Add Prudential to Investing
  _data/investing.yml
  img/investing/prudential.png
Labels: new site

#4191 Update Schwab to reflect support of SMS and better notes.
  _data/investing.yml
  notes/schwab.html
Labels: updated site

#4157 Add netbank
  _data/banking.yml
  img/banking/netbank.png
Labels: new site

#4160 Add Consorsbank
  _data/banking.yml
  img/banking/consorsbank.png
Labels: new site

#4155 Update GLS
  _data/banking.yml
Labels: updated site

#4150 Add Telus
  _data/utilities.yml
  img/utilities/telus.png
Labels: new site

#4110 Add entry for Nexon America
  _data/gaming.yml
  img/gaming/nexon.png
Labels: new site

#4209 Add Vodafone (DE)
  _data/utilities.yml
Labels: new site

#4202 Add Sixt
  _data/transport.yml
  img/transport/sixt.png
Labels: new site

#4148 Add Koodo
  _data/utilities.yml
  img/utilities/koodo.png
Labels: new site

#4199 Update Booking.com
  _data/other.yml
Labels: updated site

#4186 Update Barclays UK/US
  _data/banking.yml
Labels: updated site

#4212 Update Zoho Mail
  _data/email.yml
Labels: updated site

#4236 Add Pipedrive
  _data/communication.yml
  img/communication/pipedrive.png
Labels: new site
