Repository 2factorauth/twofactorauth, pull requests merged in 2019-02, with the labels that each got.

#3683 Update PIA 2FA status
  _data/vpn.yml
Labels: updated site

#3629 Update Max facebook & twitter
  _data/food.yml
Labels: updated site

#2573 Add Readthedocs
  _data/developer.yml
  img/developer/readthedocs.png
Labels: new site

#3686 Update Privacy.com logo
  img/payments/privacy.png
Labels: updated site

#3702 Fix First Direct doc
  _data/banking.yml
Labels: updated site

#3672 Add Southwestern Railway
  _data/transport.yml
  img/transport/swr.png
Labels: new site

#3684 Add US Veteran Affairs
  _data/government.yml
  img/government/va.png
Labels: new site

#3705 Fix Pennsylvania State University doc link
  _data/education.yml
Labels: updated site

#3709 Update Comcast software token support & mobile app exception
  _data/utilities.yml
Labels: updated site

#3732 Add Boxcryptor hardware token
  _data/security.yml
Labels: new site

#3727 Change desktop docs icon to match book icon on mobile site
  _includes/desktop-table.html
Labels: enhancement

#3743 Add Finnair
  _data/transport.yml
  img/transport/finnair.png
Labels: new site

#3724 Update Uphold
  _data/cryptocurrencies.yml
Labels: updated site

#3711 Update Twitch exception with Authy app requirement
  _data/entertainment.yml
Labels: updated site

#3737 Add Drupal.org
  _data/developer.yml
  img/developer/drupalorg.png
Labels: new site
