Repository 2factorauth/twofactorauth, pull requests merged in 2019-12, with the labels that each got.

#4372 Move IFTTT to IoT
  _data/iot.yml
  _data/other.yml
  img/iot/ifttt.png
  img/other/ifttt.png
Labels: updated site

#4371 Add Flickr
  _data/social.yml
  img/social/flickr.png
Labels: new site

#4356 Update AnyDesk
  _data/remote.yml
Labels: updated site

#4380 Update Hostpoint
  _data/hosting.yml
Labels: updated site

#4281 Add TripIt
  _data/transport.yml
  img/transport/tripit.png
Labels: new site

#4384 Update Zendesk documentation
  _data/other.yml
Labels: updated site

#4386 Add Kaspersky
  _data/security.yml
  img/security/kaspersky.png
Labels: new site

#4222 Add Clubhouse
  _data/task.yml
  img/task/clubhouse.png
Labels: new site

#4234 Add Bcnex
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bcnex.png
Labels: new site

#4233 Add Bitpanda
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitpanda.png
Labels: new site

#4229 Add SingPass
  _data/government.yml
  img/government/singpass.png
Labels: new site

#4215 Add Chargebee
  _data/payments.yml
  img/payments/chargebee.png
Labels: new site

#4214 Add AppFolio
  _data/payments.yml
  img/payments/appfolio.png
Labels: new site

#4392 Change Questrade
  _data/investing.yml
Labels: updated site

#4398 Update Adobe ID
  _data/other.yml
Labels: updated site

#4201 Add Lieferando
  _data/food.yml
  img/food/lieferando.png
Labels: new site

#4182 Add santander PT
  _data/banking.yml
Labels: new site

#4169 Add OneLogin
  _data/identity.yml
  img/identity/onelogin.png
Labels: new site

#4180 Add Allianz
  _data/finance.yml
  img/finance/allianz.png
Labels: new site

#3888 Add TVTime
  _data/entertainment.yml
  img/entertainment/tvtime.png
Labels: new site

#4358 Add maccabi4u.co.il
  _data/health.yml
  img/health/maccabi.png
Labels: new site

#4408 Load images immediately when searching
  js/app.js
Labels: bug

#4406 Update Wyze
  _data/iot.yml
Labels: new site

#4397 Add Degussa Bank
  _data/banking.yml
  img/banking/degussa.png
Labels: new site

#4409 Show "Thank them" tweet button only if Twitter handle is available
  _includes/desktop-table.html
  _includes/mobile-table.html
Labels: bug

#4421 Update "software" method in Security
  _data/security.yml
Labels: updated site

#4437 Update "software" method in Entertainment
  _data/entertainment.yml
Labels: updated site

#4435 Update "software" method in Gaming
  _data/gaming.yml
Labels: updated site

#4434 Update "software" method in Government
  _data/government.yml
Labels: updated site

#4433 Update "software" method in Health
  _data/health.yml
Labels: updated site

#4438 Update "software" method in Email
  _data/email.yml
  img/email/mxroute.png
Labels: updated site

#4426 Update "software" method in Investing
  _data/investing.yml
Labels: updated site

#4415 Remove Payza
  _data/payments.yml
  img/payments/payza.png
Labels: remove site

#4423 Update "software" method in Payments
  _data/payments.yml
Labels: updated site

#4442 Proper number formatting
  .tests/alexa.sh
Labels: enhancement

#4425 Update "software" method in Legal
  _data/legal.yml
Labels: updated site

#4417 Update "software" method in Transport
  _data/transport.yml
Labels: updated site

#4419 Update "software" method in Utilities
  _data/utilities.yml
Labels: updated site

#4420 Update "software" method in VPN Providers
  _data/vpn.yml
Labels: updated site

#4422 Update "software" method in Remote Access
  _data/remote.yml
Labels: updated site

#4424 Update "software" method in Other
  _data/other.yml
Labels: updated site

#4443 Less noisy gem install
  .circleci/config.yml
Labels: enhancement
