Repository 2factorauth/twofactorauth, pull requests merged in 2019-06, with the labels that each got.

#3871 Update RubyGems.org 2FA status
  _data/developer.yml
Labels: updated site

#3834 Add Weclapp CRM
  _data/other.yml
  img/other/weclapp.png
Labels: new site

#3845 Update UK2
  _data/domains.yml
Labels: updated site

#3861 Update Adafruit
  _data/retail.yml
Labels: updated site

#3849 Update Zurich Cantonal Bank (ZKB)
  _data/banking.yml
Labels: updated site

#3838 Update PayPal
  _data/payments.yml
Labels: updated site

#3873 Add Nexus Mods
  _data/gaming.yml
  img/gaming/nexusmods.png
Labels: new site

#3869 Add Roblox
  _data/gaming.yml
  img/gaming/roblox.png
Labels: new site

#3880 Add creditkarma.com doc
  _data/finance.yml
Labels: updated site

#3879 Update Seznam.cz
  _data/email.yml
Labels: updated site

#3886 Updated 1Password entry, as it now supports U2F
  _data/identity.yml
Labels: updated site

#3890 Add Ryerson University
  _data/education.yml
  img/education/ryerson.png
Labels: new site

#3897 Update Twitch.tv doc
  _data/entertainment.yml
Labels: updated site

#3878 Add bu.edu
  _data/education.yml
  img/education/bu.png
Labels: new site

#3699 Add Ancestry
  _data/other.yml
  img/other/ancestry.png
Labels: new site

#3900 Add Marcus
  _data/banking.yml
  img/banking/gsbank.png
  img/banking/marcus.png
Labels: new site, remove site

#3899 Update HitBTC documentation
  _data/cryptocurrencies.yml
Labels: updated site

#3898 Update Mailbox.org documentation
  _data/email.yml
Labels: updated site

#3895 Add Mailgun documentation
  _data/communication.yml
Labels: updated site

#3893 Add Ubisoft email 2FA
  _data/gaming.yml
Labels: updated site

#3892 Update Unity 2FA Software Support
  _data/developer.yml
Labels: updated site
