Repository 2factorauth/twofactorauth, pull requests merged in 2019-04, with the labels that each got.

#3777 Add COBINHOOD
  _data/cryptocurrencies.yml
  img/cryptocurrencies/cobinhood.png
Labels: new site

#3770 Update Alliant Credit Union
  _data/banking.yml
Labels: updated site

#3673 Update Miss Hosting
  _data/hosting.yml
Labels: updated site

#3752 Add Zomato
  _data/food.yml
  img/food/zomato.png
Labels: new site

#3766 Add Miami University
  _data/education.yml
  img/education/miamioh.png
Labels: new site

#3746 Add speedcube.com.au
  _data/retail.yml
  img/retail/speedcubecomau.png
Labels: new site

#3725 HSBC add exception
  _data/banking.yml
Labels: updated site

#3749 Update League of Legends
  _data/gaming.yml
Labels: updated site

#3803 Add Floatplane
  _data/entertainment.yml
  img/entertainment/floatplane.png
Labels: new site

#3796 Add LHV
  _data/banking.yml
  img/banking/lhv.png
Labels: new site

#3801 Remove G+
  _data/social.yml
  img/social/g+.png
Labels: remove site

#3678 Add BGL Corp
  _data/finance.yml
  img/finance/bgl.png
Labels: new site

#3715 Rebrand IBM Cloud Video to IBM Watson Media
  _data/entertainment.yml
  img/entertainment/ibm.png
  img/entertainment/ustream.png
Labels: updated site

#2997 Add Amundi EE
  _data/finance.yml
  img/finance/amundiee.png
Labels: new site

#3805 Add Gamesplanet
  _data/gaming.yml
  img/gaming/gamesplanet.png
Labels: new site

#3774 Add niconico
  _data/entertainment.yml
  img/entertainment/niconico.png
Labels: new site

#3730 Add Seamless and Grubhub
  _data/food.yml
  img/food/grubhub.png
  img/food/seamless.png
Labels: new site

#3754 Update 1Password 2FA options
  _data/identity.yml
Labels: updated site

#3739 Add Tesco bank
  _data/banking.yml
  img/banking/tescobank.png
Labels: new site

#3797 Add Wolt
  _data/food.yml
  img/food/wolt.png
Labels: new site

#2954 Add Desert Financial Credit Union and Lockheed Georgia Employees Community Credit Union
  _data/banking.yml
  img/banking/desertfinancialcu.png
  img/banking/lgecommunitycu.png
Labels: new site

#3767 Update HelloSign 2FA options
  _data/legal.yml
Labels: updated site

#3745 Add osu!
  _data/gaming.yml
  img/gaming/osu.png
Labels: new site

#3776 Add Wix
  _data/hosting.yml
  img/hosting/wix.png
Labels: new site

#3716 Add the BiggerPockets site
  _data/social.yml
  img/social/biggerpockets.png
Labels: new site

#3720 Add Tokopedia
  _data/retail.yml
  img/retail/tokopedia.png
Labels: new site

#3780 Update mailbox.org doc link
  _data/email.yml
Labels: updated site

#3750 Add exception for TransferWise
  _data/finance.yml
Labels: updated site

#3787 Add AppSignal
  _data/developer.yml
  img/developer/appsignal.png
Labels: new site

#3791 Add Blacknight
  _data/hosting.yml
  img/hosting/blacknight.png
Labels: new site

#3807 Namecheap now supports hardware 2FA
  _data/domains.yml
Labels: updated site

#3816 Update US Social Security Administration
  _data/government.yml
Labels: updated site

#3759 Add CloudConvert
  _data/other.yml
  img/other/cloudconvert.png
Labels: new site

#3771 Add Mountain America Credit Union
  _data/banking.yml
  img/banking/macu.png
Labels: new site

#3762 Add Wasabi
  _data/backup.yml
  img/backup/wasabi.png
Labels: new site

#3692 Add Openbank
  _data/banking.yml
  img/banking/openbank.png
Labels: new site

#3808 Add Seznam.cz
  _data/email.yml
  img/email/seznamcz.png
Labels: new site

#3799 Add Anydesk
  _data/remote.yml
  img/remote/anydesk.png
Labels: new site

#3810 Add Ceska Sporitelna (bank)
  _data/banking.yml
  img/banking/csas-cz.png
Labels: new site

#3824 Update Migadu 2FA options
  _data/email.yml
  img/email/migadu.png
Labels: updated site

#3390 Add eBay Kleinanzeigen (DE)
  _data/retail.yml
  img/retail/ebay-kleinanzeigen.png
Labels: new site

#3804 Add Riot.im
  _data/communication.yml
  img/communication/riot.png
Labels: new site

#2972 Add Kerio Connect
  _data/email.yml
  img/email/kerio.png
Labels: new site

#3832 Update Packet URL and doc
  _data/cloud.yml
Labels: updated site

#3809 Add Fio banka
  _data/banking.yml
  img/banking/fio-cz.png
Labels: new site

#3793 Add Cloze
  _data/communication.yml
  img/communication/cloze.png
Labels: new site
