Repository 2factorauth/twofactorauth, pull requests merged in 2020-05, with the labels that each got.

#4746 Use "sticky" position on <th> instead of <thead> to increase browser compatibility
  css/base.scss
Labels: enhancement

#4748 Add exception for LinkedIn
  _data/social.yml
Labels: update site

#4764 Update Twilio
  _data/developer.yml
Labels: update site

#4739 Update Yahoo Mail
  _data/email.yml
Labels: update site

#4752 OVH: Add documentation and U2F support
  _data/hosting.yml
Labels: update site

#4758 Add Jelastic
  _data/cloud.yml
  img/cloud/jelastic.png
Labels: add site

#4751 Add PKO Bank Polski
  _data/banking.yml
  img/banking/pkobp.png
Labels: add site

#4713 Add itslearning
  _data/education.yml
  img/education/itslearning.png
Labels: add site

#4766 Update Epic Games doc URL
  _data/gaming.yml
Labels: update site

#4631 Add Alexa cache & Clean up all test scripts
  .circleci/config.yml
  .tests/alexa.rb
  .tests/alexa.sh
  .tests/facebook.sh
  .tests/twitter.sh
Labels: enhancement

#4767 Update to surfshark entry.
  _data/security.yml
Labels: update site

#4781 Remove TradeKing
  _data/investing.yml
  img/investing/tradeking.png
Labels: remove site

#4784 Add Bullion Exchanges
  _data/investing.yml
  img/investing/bullionexchanges.png
Labels: add site

#4771 Update Google Fi, Google Fiber
  _data/utilities.yml
Labels: multiple sites, update site

#4780 Adds Credit Karma UK
  _data/finance.yml
Labels: add site

#4722 Update Fifth Third
  _data/banking.yml
Labels: update site

#4247 Add Equifax
  _data/finance.yml
  img/finance/equifax.png
Labels: add site

#4144 Add Deutsche Bank
  _data/banking.yml
  img/banking/deutschebank.png
Labels: add site
