Repository 2factorauth/twofactorauth, pull requests merged in 2020-08, with the labels that each got.

#4866 Update T-Mobile
  _data/utilities.yml
Labels: update site

#4874 Fix rubocop
  _deployment/tests/verify.rb
Labels: bug, dependencies

#4862 Add iubenda
  _data/legal.yml
  img/legal/iubenda.png
Labels: add site

#4867 Use icon preset for cwebp
  _deployment/webp.sh
Labels: enhancement

#4825 Add regions to entertainment
  _data/entertainment.yml
Labels: international, multiple sites, update site

#4872 Add Colorado School of Mines to Education
  _data/education.yml
  img/education/coloradoschoolofmines.png
Labels: add site

#4865 add ACTIVE 24 hosting
  _data/hosting.yml
  img/hosting/active24.png
Labels: add site

#4835 Create api.rb
  .github/workflows/gh-pages.yml
  _deployment/api.rb
Labels: enhancement

#4878 Add Cronometer
  _data/health.yml
  img/health/cronometer.png
Labels: add site

#4884 Rename Riot to Element
  _data/communication.yml
  img/communication/element.png
  img/communication/riot.png
Labels: update site

#4881 Remove Mixer
  _data/entertainment.yml
  img/entertainment/mixer.png
Labels: remove site

#4875 Add UBS
  _data/banking.yml
  img/banking/ubs.png
Labels: add site

#4882 Add Fineco Bank (IT/UK)
  _data/banking.yml
  img/banking/finecobank.png
Labels: add site

#4893 Update Stash url and doc
  _data/investing.yml
Labels: update site

#4896 Add hCaptcha
  _data/security.yml
  img/security/hcaptcha.png
Labels: add site

#4502 Add Fanatical.com
  _data/gaming.yml
  img/gaming/fanatical.png
Labels: add site

#4904 Update Microsoft sites
  _data/backup.yml
  _data/communication.yml
  _data/developer.yml
  _data/email.yml
  _data/gaming.yml
  _data/other.yml
  _data/task.yml
Labels: multiple sites, update site

#4910 Update Github.com
  _data/developer.yml
Labels: update site

#4911 Update Bitbucket
  _data/developer.yml
Labels: update site

#4858 Use triple-dot notation for "git diff"
  _deployment/tests/alexa.sh
  _deployment/tests/facebook.sh
  _deployment/tests/twitter.sh
Labels: enhancement

#4711 Add Airbnb exception
  _data/hotels.yml
Labels: update site

#4906 Update Upwork
  _data/other.yml
Labels: update site

#4901 Add NordVPN Teams
  _data/vpn.yml
Labels: add site

#4914 Update Gandi
  _data/domains.yml
Labels: update site

#4913 Add Deka Investments
  _data/investing.yml
  img/investing/deka.png
Labels: add site

#4915 Update SatoshiTango
  img/cryptocurrencies/satoshitango.png
Labels: update site

#4879 Add Missive App
  _data/communication.yml
  img/communication/missiveapp.png
Labels: add site

#4869 Wikia has re-branded as FANDOM
  _data/other.yml
  img/other/fandom.png
  img/other/wikia.png
Labels: update site
