Repository 2factorauth/twofactorauth, pull requests merged in 2020-06, with the labels that each got.

#4788 Update Wix
  _data/hosting.yml
Labels: update site

#4792 Add mysqa.org.uk
  _data/education.yml
  img/education/mysqa.png
Labels: add site

#4801 Add region tag test
  .github/workflows/jekyll.yml
  _deployment/tests/region_codes.rb
Labels: enhancement

#4803 Update test dependencies
  .circleci/config.yml
  .github/workflows/gh-pages.yml
  .github/workflows/jekyll.yml
  .github/workflows/ruby.yml
  _deployment/tests/facebook.sh
  _deployment/tests/twitter.sh
Labels: enhancement

#4804 Add Invoice2go
  _data/finance.yml
  img/finance/invoice2go.png
Labels: add site

#4802 Minor styling fixes
  README.md
  _includes/desktop-table.html
  css/desktop-table.scss
  package-lock.json
Labels: enhancement

#4795 Add resolver.co.uk
  _data/legal.yml
  img/legal/resolver.png
Labels: add site

#4805 Add missing contact information
  _data/banking.yml
  _data/finance.yml
  _data/social.yml
Labels: multiple sites, update site

#4320 add groups.io
  _data/communication.yml
  img/communication/groups_io.png
Labels: add site

#4816 Add hotjar
  _data/developer.yml
  img/developer/hotjar.png
Labels: add site

#4814 Add Shadow
  _data/gaming.yml
  img/gaming/shadow.png
Labels: add site

#4830 Add Boots
  _data/retail.yml
  img/retail/boots.png
Labels: add site

#4827 Add email 2fa for ring
  _data/iot.yml
Labels: update site

#4782 Update RealVNC
  _data/remote.yml
Labels: update site

#4553 Add Speedrun.com
  _data/gaming.yml
  img/gaming/speedruncom.png
Labels: add site

#4823 Add Canada, France & Italy
  .gitignore
  _data/regions.yml
Labels: enhancement, international

#4411 Update JetBrains
  _data/developer.yml
Labels: update site
