Repository 2factorauth/twofactorauth, pull requests merged in 2020-10, with the labels that each got.

#4718 Add Bendigo Bank
  _data/banking.yml
  img/banking/bendigobank.png
Labels: add site

#4998 Update Tesla
  _data/iot.yml
Labels: update site

#4996 Add NCSU
  _data/education.yml
  img/education/ncsu.png
Labels: add site

#5003 Add Brack
  _data/retail.yml
  img/retail/brack.png
Labels: add site

#5005 Update Digitec
  _data/retail.yml
Labels: update site

#5008 Add STEG Electronics
  _data/retail.yml
  img/retail/steg.png
Labels: add site

#5007 Add ELV Elektronik
  _data/retail.yml
  img/retail/elv.png
Labels: add site

#5002 Add Hoststar
  _data/hosting.yml
  img/hosting/hoststar.png
Labels: add site

#5000 Add Migros
  _data/retail.yml
  img/retail/migros.png
Labels: add site

#5001 Add Wingo
  _data/utilities.yml
  img/utilities/wingo.png
Labels: add site

#4999 Add Coop
  _data/retail.yml
  img/retail/coopgenossenschaft.png
Labels: add site

#5004 Add Conrad
  _data/retail.yml
  img/retail/conrad.png
Labels: add site

#4930 Update Nuget
  _data/developer.yml
Labels: update site

#5014 Update StartMail
  _data/email.yml
Labels: update site

#4995 Update Nextdoor
  _data/social.yml
  img/social/nextdoor.png
Labels: update site

#4993 Update FogBugz
  _data/developer.yml
Labels: update site

#4992 Update Anydesk
  _data/remote.yml
Labels: update site

#4991 Update ImmobilienScout24
  _data/other.yml
Labels: update site

#5009 Update Hint Health
  _data/health.yml
Labels: update site

#5010 Update HitBTC
  _data/cryptocurrencies.yml
Labels: update site

#5011 Update NETELLER
  _data/payments.yml
Labels: update site

#5019 Update Thrift Savings Plan
  _data/government.yml
Labels: update site

#5013 Rename Packet to Equinix Metal
  _data/cloud.yml
  img/cloud/equinix-metal.png
  img/cloud/packet.png
Labels: update site

#5012 Update Nutmeg
  _data/investing.yml
Labels: update site

#4986 Update IT Glue
  _data/developer.yml
Labels: update site

#5022 Remove ThisData
  _data/backup.yml
  img/backup/thisdata.png
Labels: remove site

#4985 Update LendingClub
  _data/banking.yml
Labels: update site

#5023 Remove MotifInvesting
  _data/investing.yml
  img/investing/motif.png
Labels: remove site

#5020 Remove BX Thailand
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bxthailand.png
Labels: remove site

#5018 Update Binance
  _data/cryptocurrencies.yml
Labels: update site

#5017 Update ViaBTC
  _data/cryptocurrencies.yml
Labels: update site

#4984 Update Clubhouse
  _data/task.yml
Labels: update site

#4983 Update bugcrowd
  _data/security.yml
Labels: update site

#4982 Update Coinify
  _data/cryptocurrencies.yml
Labels: update site

#5036 Update Dominion Energy
  _data/utilities.yml
Labels: update site

#5035 Update LastPass
  _data/identity.yml
Labels: update site

#5038 Add Cembra MoneyBank
  _data/banking.yml
  img/banking/cembra-money-bank.png
Labels: add site

#5041 Update Playstation Network
  _data/gaming.yml
Labels: update site

#5039 Rename Short.cm to Short.io
  _data/social.yml
  img/social/shortio.png
Labels: update site

#5031 Add '--production' flag to region.rb
  .github/workflows/gh-pages.yml
  _deployment/regions.rb
Labels: enhancement

#5042 Update Pivotal Tracker
  _data/developer.yml
Labels: update site

#5044 Add email TFA to Invoice2go
  _data/finance.yml
Labels: update site

#4990 Update Pennsylvania State University
  _data/education.yml
Labels: update site

#5048 Remove Westminster Savings Credit Union
  _data/banking.yml
  img/banking/wscu.png
Labels: remove site

#5045 Add Bethesda
  _data/gaming.yml
  img/gaming/bethesda.png
Labels: add site

#5029 Update VPN Unlimited
  _data/vpn.yml
  img/vpn/vpnunlimited.png
Labels: update site

#5030 Add Passwarden
  _data/identity.yml
  img/identity/passwarden.png
Labels: add site

#5053 Vanguard Yubikey support doesn't require Chrome
  _data/investing.yml
Labels: update site

#5059 Update Zoom
  _data/communication.yml
Labels: update site

#5065 Add Bank igud
  _data/banking.yml
  img/banking/bankigud.png
Labels: add site

#5063 Add Swiss Life
  _data/finance.yml
  img/finance/swisslife.png
Labels: add site

#5066 Update Payoneer.com
  _data/payments.yml
Labels: update site
