Repository 2factorauth/twofactorauth, pull requests merged in 2020-04, with the labels that each got.

#4675 Add Gumtree
  _data/other.yml
  img/other/gumtree.png
Labels: add site

#4709 Update Cloudflare
  _data/security.yml
Labels: update site

#4716 Update Gemfile.lock
  Gemfile.lock
Labels: bug

#4714 Add Houseparty
  _data/communication.yml
  img/communication/houseparty.png
Labels: add site

#4715 ecobee has now enabled 2FA (SMS)
  _data/iot.yml
Labels: update site

#4717 Add eduonix
  _data/education.yml
  img/education/eduonix.png
Labels: add site

#4145 Add norisbank
  _data/banking.yml
  img/banking/norisbank.png
Labels: add site

#4298 Add Thalia
  _data/retail.yml
  img/retail/thalia.png
Labels: add site

#4228 Add FastSpring
  _data/payments.yml
  img/payments/fastspring.png
Labels: add site

#4712 Add Zoom
  _data/communication.yml
  img/communication/zoom.png
Labels: add site

#4720 Add Woodforest National Bank
  _data/banking.yml
  img/banking/woodforest.png
Labels: add site

#4719 Add Netlify
  _data/hosting.yml
  img/hosting/netlify.png
Labels: add site

#4458 Update build status image source
  README.md
Labels: enhancement

#4724 Update H&R Block
  _data/finance.yml
Labels: update site

#4727 Update Ubiquiti to use correct domain
  _data/other.yml
Labels: update site

#4731 Add NH Hotels
  _data/hotels.yml
  img/hotels/nh.png
Labels: add site

#4732 Add Virgin Atlantic
  _data/transport.yml
  img/transport/virginatlantic.png
Labels: add site

#4733 Add Wyndham Hotels
  _data/hotels.yml
  img/hotels/wyndham.png
Labels: add site

#4735 Add Despegar.com
  _data/transport.yml
  img/transport/despegar.png
Labels: add site

#4734 Add Melia Hotels
  _data/hotels.yml
  img/hotels/melia.png
Labels: add site

#4736 Update Amazon
  _data/retail.yml
Labels: update site

#4738 Update Amazon Web Services
  _data/cloud.yml
Labels: update site

#4737 Update Amazon Pay
  _data/payments.yml
Labels: update site

#4726 Add MaiCoin
  _data/cryptocurrencies.yml
  img/cryptocurrencies/maicoin.png
Labels: add site

#4742 Update GoCardless
  _data/payments.yml
Labels: update site

#4741 Add Tick
  _data/task.yml
  img/task/tickspot.png
Labels: add site

#4743 Link Hetzner doc to English version
  _data/hosting.yml
Labels: update site

#4744 Add Quizlet.com to Education category
  _data/education.yml
  img/education/quizlet.png
Labels: add site

#4747 Add exception / restriction for GitHub hardware tokens
  _data/developer.yml
Labels: update site

#4488 Add exception / restriction to Airtable
  _data/task.yml
Labels: update site
