Repository 2factorauth/twofactorauth, pull requests merged in 2020-03, with the labels that each got.

#4523 Update Twitter
  _data/social.yml
Labels: update site

#4669 Update AirVPN 2FA status
  _data/vpn.yml
Labels: update site

#4671 Add Bancolombia (Colombia)
  _data/banking.yml
  img/banking/bancolombia.png
Labels: add site

#4677 Add Cornell University
  _data/education.yml
  img/education/cornell.png
Labels: add site

#4674 Pluralsight now supports 2FA
  _data/education.yml
Labels: update site

#4649 Add Swiss Medical (Argentina)
  _data/health.yml
  img/health/swissmedical.png
Labels: add site

#4663 Add Rocket Beans TV (Germany)
  _data/entertainment.yml
  img/entertainment/rocketbeanstv.png
Labels: add site

#4666 Add Provident Metals
  _data/investing.yml
  img/investing/providentmetals.png
Labels: add site

#4681 Add Banco Macro
  _data/banking.yml
  img/banking/bancomacro.png
Labels: add site

#4664 Add Consumer Cellular
  _data/utilities.yml
  img/utilities/consumercellular.png
Labels: add site

#4480 Add APMEX
  _data/investing.yml
  img/investing/apmex.png
Labels: add site

#4701 Add InvoiceBerry
  _data/finance.yml
  img/finance/invoiceberry.png
Labels: add site

#4686 Update Hootsuite
  _data/social.yml
Labels: update site

#4685 Add LATAM Airlines
  _data/transport.yml
  img/transport/latam.png
Labels: add site

#4689 Update Facebook exception
  _data/social.yml
Labels: update site

#4684 Add Copa Airlines
  _data/transport.yml
  img/transport/copaairlines.png
Labels: add site

#4683 Add Aerolíneas Argentinas
  _data/transport.yml
  img/transport/aerolineasargentinas.png
Labels: add site

#4678 Added buda.com crypto site
  _data/cryptocurrencies.yml
  img/cryptocurrencies/buda.png
Labels: add site

#4680 Add Banco Nación
  _data/banking.yml
  img/banking/banconacion.png
Labels: add site

#4660 Update Arcadia
  _data/utilities.yml
Labels: update site

#4653 Update League of Legends
  _data/gaming.yml
Labels: update site

#4617 Add ANSES (AR)
  _data/government.yml
  img/government/anses.png
Labels: add site

#4597 Add Mi Argentina (AR)
  _data/government.yml
  img/government/miargentina.png
Labels: add site

#4629 Add Neolo
  _data/hosting.yml
  img/hosting/neolo.png
Labels: add site

#4565 Add Citationsy
  _data/education.yml
  img/education/citationsy.png
Labels: add site

#4578 Update tfa support for Gemini
  _data/cryptocurrencies.yml
Labels: update site

#4604 Update 1Password
  _data/identity.yml
Labels: update site

#4338 Add Airdroid
  _data/remote.yml
  img/remote/airdroid.png
Labels: add site

#4339 Add onvista bank
  _data/investing.yml
  img/investing/onvista.png
Labels: add site

#4388 Add DPD
  _data/other.yml
  img/other/dpd.png
Labels: add site

#4665 Add JM Bullion
  _data/investing.yml
  img/investing/jmbullion.png
Labels: add site

#4399 Add Host Europe
  _data/hosting.yml
  img/hosting/hosteurope.png
Labels: add site

#4618 Add Saturn
  _data/retail.yml
  img/retail/saturn.png
Labels: add site

#4628 Add WeltSparen
  _data/investing.yml
  img/investing/weltsparen.png
Labels: add site

#4654 Update ING (LU)
  _data/banking.yml
Labels: update site

#4696 Add BitMEX
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitmex.png
Labels: add site

#4697 Add Bybit
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bybit.png
Labels: add site

#4698 Add Nulab
  _data/communication.yml
  img/communication/nulab.png
Labels: add site

#4196 Add AOK
  _data/finance.yml
  img/finance/aok.png
Labels: add site

#4343 Update CIBC
  _data/banking.yml
Labels: update site

#4584 Include tfa methods in search keywords
  _includes/row-title.html
  index.html
Labels: enhancement

#4672 Added GWR (UK train company)
  _data/transport.yml
  img/transport/gwr.png
Labels: add site

#4679 Add OSDE
  _data/health.yml
  img/health/osde.png
Labels: add site

#4225 Add Liquid
  _data/cryptocurrencies.yml
  img/cryptocurrencies/liquid.png
Labels: add site

#4704 Add coincheck
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coincheck.png
Labels: add site

#4699 Add ISL Online
  _data/remote.yml
  img/remote/islonline.png
Labels: add site

#4700 Add STEX
  _data/cryptocurrencies.yml
  img/cryptocurrencies/stex.png
Labels: add site

#4630 Update Chime 2FA
  _data/banking.yml
Labels: update site

#4232 Add Intercom
  _data/communication.yml
  img/communication/intercom.png
Labels: add site

#4517 Update GoDaddy
  _data/domains.yml
Labels: update site

#4389 Add Unbounce
  _data/developer.yml
  img/developer/unbounce.png
Labels: add site

#4687 Update Name.com
  _data/domains.yml
Labels: update site

#4557 Add artstation
  _data/social.yml
  img/social/artstation.png
Labels: add site

#4705 Update Entertainment icons
  img/entertainment/floatplane.png
  img/entertainment/googleplay.png
  img/entertainment/hulu.png
  img/entertainment/imdb.png
  img/entertainment/smashcast.png
  img/entertainment/spotify.png
  img/entertainment/twitch.png
  img/entertainment/youtube.png
Labels: enhancement

#4006 Add Aruba Cloud
  _data/cloud.yml
  img/cloud/arubacloud.png
Labels: add site

#4707 Update AltoIRA
  _data/finance.yml
Labels: update site

#4708 Update FollowMyHealth
  _data/health.yml
Labels: update site

#4706 Fix LineLength namespace
  Rakefile
Labels: enhancement

#4682 Update Skrill
  _data/payments.yml
Labels: update site
