Repository 2factorauth/twofactorauth, pull requests merged in 2020-01, with the labels that each got.

#4492 Add Cryptonator
  _data/cryptocurrencies.yml
  img/cryptocurrencies/cryptonator.png
Labels: new site

#4491 Update Wave to add update and change name
  _data/finance.yml
Labels: updated site

#4490 Updating Bitdefender to add TFA
  _data/security.yml
Labels: updated site

#4485 Add MyHeritage
  _data/health.yml
  img/health/myheritage.png
Labels: new site

#4479 Update Lloyds Bank to show 2FA methods used
  _data/banking.yml
Labels: updated site

#4478 Update Halifax show 2FA methods used
  _data/banking.yml
Labels: updated site

#4475 Add Arlo
  _data/iot.yml
  img/iot/arlo.png
Labels: new site

#4473 Add Bank Of Scotland
  _data/banking.yml
  img/banking/bankofscotland.png
Labels: new site

#4472 Rename Incapsula to Imperva
  _data/domains.yml
  img/domains/imperva.png
  img/domains/incapsula.png
Labels: updated site

#4471 Rename Australian Red Cross Blood Service to Australian Red Cross Lifeblood
  _data/health.yml
Labels: updated site

#4466 Rename Buycraft to Tebex
  _data/payments.yml
  img/payments/buycraft.png
  img/payments/tebex.png
Labels: updated site

#4465 Rename RightScale to Flexera
  _data/cloud.yml
  img/cloud/flexera.png
  img/cloud/rightscale.png
Labels: updated site

#4464 Rename Aerohive Networks to Extreme Networks
  _data/other.yml
  img/other/aerohive.png
  img/other/extremenetworks.png
Labels: updated site

#4463 Rename MaxCDN to StackPath
  _data/hosting.yml
  img/hosting/maxcdn.png
  img/hosting/stackpath.png
Labels: updated site

#4462 Rename NEFCU to Jovia Financial
  _data/banking.yml
  img/banking/jovia.png
  img/banking/nefcu.png
Labels: updated site

#4461 Rename Everbank to TIAA Bank
  _data/banking.yml
  img/banking/everbank.png
  img/banking/tiaabank.png
Labels: updated site

#4459 Update Backblaze
  _data/backup.yml
Labels: updated site

#4455 Rename WiseBanyan to Axos Invest
  _data/investing.yml
  img/investing/axosinvest.png
  img/investing/wisebanyan.png
Labels: updated site

#4453 Add Hanseatic Bank
  _data/banking.yml
  img/banking/hanseatic.png
Labels: new site

#4451 Update Hostiso
  _data/cloud.yml
Labels: updated site

#4449 Update Evernote
  _data/backup.yml
Labels: updated site

#4448 Add Elster
  _data/government.yml
  img/government/elster.png
Labels: new site

#4447 Remove Wunderlist
  _data/task.yml
  img/task/wunderlist.png
Labels: remove site

#4454 Rename Vantiv to Worldpay
  _data/payments.yml
  img/payments/vantiv.png
  img/payments/worldpay.png
Labels: updated site

#4416 Add H&R Block
  _data/finance.yml
  img/finance/hrblock.png
Labels: new site

#4240 Update ING-DiBa Austria
  _data/banking.yml
Labels: updated site

#4181 Add Caixadirecta
  _data/banking.yml
  img/banking/caixa_directa.png
Labels: new site

#4497 Update Floatplane
  _data/entertainment.yml
Labels: updated site

#4418 Update "software" method in Task Management
  _data/task.yml
Labels: updated site

#4444 Add Western Union
  _data/payments.yml
  img/payments/westernunion.png
Labels: new site

#4441 Update "software" method in Developer
  _data/developer.yml
Labels: updated site

#4428 Update "software" method in Retail
  _data/retail.yml
Labels: updated site

#4436 Update "software" method in Finance
  _data/finance.yml
Labels: updated site

#4445 Update "software" method in Betting
  _data/betting.yml
Labels: updated site

#4504 Update Wasabi
  _data/backup.yml
Labels: updated site

#4439 Update "software" method in Education
  _data/education.yml
Labels: updated site

#4432 Update "software" method in Hosting/VPS
  _data/hosting.yml
  img/hosting/hosthatch.png
  img/hosting/speedit.png
Labels: updated site

#4429 Update "software" method in Social
  _data/social.yml
Labels: updated site

#4359 Add Bank Hapoalim
  _data/banking.yml
  img/banking/poalim.png
Labels: new site

#4440 Update "software" method in Domains
  _data/domains.yml
  img/domains/domenytv.png
Labels: updated site

#4539 Add Carrd
  _data/hosting.yml
  img/hosting/carrd.png
Labels: new site

#4528 Update Tresorit
  _data/backup.yml
Labels: updated site

#4527 Update ConEd
  _data/utilities.yml
Labels: updated site

#4446 Update "software" method in Banking
  _data/banking.yml
Labels: updated site

#4526 Update Backblaze
  _data/backup.yml
Labels: updated site

#4538 Update TaxAct 2fa
  _data/finance.yml
Labels: updated site

#4524 Turbo tax
  _data/finance.yml
Labels: updated site

#4518 Update Skype exception
  _data/communication.yml
Labels: updated site

#4516 Add Tutanota exception
  _data/email.yml
Labels: updated site

#4505 Add Principal
  _data/finance.yml
  img/finance/principal.png
Labels: new site

#4532 Update "software" method in Identity Management
  _data/identity.yml
Labels: updated site

#4542 Remove software tag
  _data/backup.yml
  _data/cryptocurrencies.yml
  _data/developer.yml
  _data/hosting.yml
  img/backup/smartbox.png
  img/hosting/hostnet.png
  websites_schema.yml
Labels: enhancement, remove site, updated site

#4503 Update Treasury Direct
  _data/finance.yml
Labels: updated site

#4501 Update NexusMod
  _data/gaming.yml
Labels: updated site

#4498 Added elmah.io
  _data/developer.yml
  img/developer/elmahio.png
Labels: new site

#4496 Add UniSuper
  _data/investing.yml
  img/investing/unisuper.png
Labels: new site

#4477 Add LNER
  _data/transport.yml
  img/transport/lner.png
Labels: new site

#4493 Add Canva
  _data/other.yml
  img/other/canva.png
Labels: new site

#4178 Update+Move Baden-Württembergische Bank
  _data/banking.yml
  _data/finance.yml
  img/banking/bw-bank.png
  img/finance/bw_bank.png
Labels: updated site

#4374 Add SCHUFA
  _data/finance.yml
  img/finance/schufa.png
Labels: new site

#4535 Update Webroot 2FA status
  _data/security.yml
Labels: updated site

#4547 Fix api v1
  api/v1/data.json
Labels: bug

#4544 Update 500px
  _data/social.yml
Labels: updated site

#4546 Update Internet.bs
  _data/domains.yml
  notes/internetbs.html
Labels: updated site

#4550 Update reddit
  _data/social.yml
Labels: updated site

#4549 Remove Bitium
  _data/identity.yml
  img/identity/bitium.png
Labels: remove site

#4509 Update Bank of America
  _data/banking.yml
Labels: updated site

#4508 Update tfa support for clearscore
  _data/finance.yml
Labels: updated site

#4540 Add Opera
  _data/other.yml
  img/other/opera.png
Labels: new site

#4521 Add Dropbox exception
  _data/backup.yml
Labels: updated site

#4551 Add Namesco (Names.co.uk)
  _data/domains.yml
  img/domains/namesco.png
Labels: new site

#4219 Add McGill University
  _data/education.yml
  img/education/mcgill.png
Labels: new site
