Repository 2factorauth/twofactorauth, pull requests merged in 2020-12, with the labels that each got.

#5128 Update TD Bank Canadian Branding
  _data/banking.yml
  _data/investing.yml
Labels: multiple sites, remove site, update site

#5114 Add US Citizenship and Immigration Services
  _data/government.yml
  img/government/uscis.png
Labels: add site

#5129 Add US Postal Service
  _data/other.yml
  img/other/usps.svg
Labels: add site

#5139 Remove Bitlish
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitlish.png
Labels: remove site

#5137 Add Elastic Email
  _data/communication.yml
  img/communication/elasticemail.png
Labels: add site

#5135 Add Kuna
  _data/cryptocurrencies.yml
  img/cryptocurrencies/kuna.png
Labels: add site

#5133 Update Cloudbet
  _data/betting.yml
Labels: update site

#5127 Update T-Mobile
  _data/utilities.yml
Labels: update site

#5086 Remove MyTaxi
  _data/transport.yml
  img/transport/mytaxi.png
Labels: remove site

#5117 Update GroupMe
  _data/communication.yml
Labels: update site

#5123 Add Smarkets
  _data/betting.yml
  img/betting/smarkets.png
Labels: add site

#5118 Add MyChart by Epic
  _data/health.yml
  img/health/mychart.png
Labels: add site

#5075 Convert APIv1 to Ruby source
  .github/workflows/gh-pages.yml
  .github/workflows/jekyll.yml
  .gitignore
  _deployment/apiv1.rb
  _deployment/apiv2.rb
  api/v1/data.json
  api/v2/README.md
  api/v2/all.json
  api/v2/tfa.json
Labels: enhancement

#5131 Add Postmarkapp
  _data/communication.yml
  img/communication/postmarkapp.png
Labels: add site

#5142 Add CoinTracker
  _data/cryptocurrencies.yml
  img/cryptocurrencies/cointracker.png
Labels: add site

#5140 Add Postal and Shipping category
  _data/banking.yml
  _data/other.yml
  _data/postal.yml
  _data/sections.yml
  img/postal/auspost.png
  img/postal/dhl.png
  img/postal/dpd.png
  img/postal/gls-one.png
  img/postal/hermes.png
  img/postal/posteitaliane.png
  img/postal/ukpostbox.png
  img/postal/ups.png
  img/postal/usps.svg
  img/sections.yml
Labels: add category

#5130 Add SelfWealth
  _data/investing.yml
  img/investing/selfwealth.png
Labels: add site

#5102 Add Next
  _data/retail.yml
  img/retail/next.png
Labels: add site

#5120 Update Private Internet Access
  _data/vpn.yml
Labels: update site

#5146 Add Crypto
  _data/cryptocurrencies.yml
  img/cryptocurrencies/crypto.png
Labels: add site

#5104 Update Twitch 2FA methods
  _data/entertainment.yml
Labels: update site

#5149 Add DigitalRiver
  _data/payments.yml
  img/payments/digitalriver.png
Labels: add site

#5150 Add ProfitWell
  _data/developer.yml
  img/developer/profitwell.png
Labels: add site

#5158 Rename Quizzle to Bankrate
  _data/finance.yml
  img/finance/bankrate.png
  img/finance/quizzle.png
Labels: update site

#5157 Remove Valic
  _data/finance.yml
  img/finance/valic.png
Labels: remove site

#5085 Rename NSB to Vy
  _data/transport.yml
  img/transport/nsb.png
  img/transport/vy.png
Labels: update site

#5155 Remove HelloWallet
  _data/finance.yml
  img/finance/hellowallet.png
Labels: remove site
