Repository 2factorauth/twofactorauth, pull requests merged in 2020-09, with the labels that each got.

#4876 Add Credit Suisse
  _data/banking.yml
  img/banking/credit-suisse.png
Labels: add site

#4898 Add Bitnami
  _data/developer.yml
  img/developer/bitnami.png
Labels: add site

#4174 Add Volksbanken Raiffeisenbanken
  _data/banking.yml
  img/banking/vr.png
Labels: add site

#4226 Add Philipps-Universität Marburg
  _data/education.yml
  img/education/unimarburg.png
Labels: add site

#4555 Add HelloBank! and LCL
  _data/banking.yml
  img/banking/hellobank_fr.png
  img/banking/lcl.png
Labels: add site, multiple sites

#4912 Add static timezone suffix
  _layouts/default.html
Labels: enhancement

#4922 Add ESL
  _data/gaming.yml
  img/gaming/esl.png
Labels: add site

#4931 Add Admiral (UK)
  _data/finance.yml
  img/finance/admiral.png
Labels: add site

#4933 Add CDKeys
  _data/gaming.yml
  img/gaming/cdkeys.png
Labels: add site

#4938 Fix Twitter button not working
  js/social-media.js
Labels: bug

#4939 Add John Lewis & Partners
  _data/retail.yml
  img/retail/john-lewis.png
Labels: add site

#4847 Changed Nexmo to Vonage
  _data/developer.yml
  img/developer/nexmo.png
  img/developer/vonage.png
Labels: update site

#4944 Update Reddit doc
  _data/social.yml
Labels: update site

#4943 Performance boost for webp.sh
  _deployment/webp.sh
Labels: enhancement

#4952 Update AOL Mail
  _data/email.yml
Labels: update site

#4953 Update Yahoo Mail
  _data/email.yml
Labels: update site

#4940 Add Panther
  _data/security.yml
  img/security/panther.png
Labels: add site

#4934 Add color codes to Circle CI outputs
  _deployment/tests/alexa.rb
  _deployment/tests/facebook.sh
  _deployment/tests/twitter.rb
  _deployment/tests/twitter.sh
Labels: enhancement

#4946 Add Nebula
  _data/entertainment.yml
  img/entertainment/nebula.png
Labels: add site

#4958 Update retail.yml
  _data/retail.yml
Labels: update site

#4959 Change Centrify "doc" URL
  _data/identity.yml
Labels: update site

#4936 Add Cookiebot
  _data/developer.yml
  img/developer/cookiebot.png
Labels: add site

#4928 Add Mendeley
  _data/education.yml
  img/education/mendeley.png
Labels: add site

#4770 Add Basic Attention Token
  _data/other.yml
  img/other/basicattentiontoken.png
Labels: add site

#4819 Add Nordea Finland & fix Nordnet (FI) name
  _data/banking.yml
Labels: add site, multiple sites, update site

#4966 Update Windscribe
  _data/vpn.yml
Labels: update site

#4969 Update Indeed doc URL
  _data/other.yml
Labels: update site

#4970 Add Indeed exception
  _data/other.yml
Labels: update site

#4965 Update Microsoft services
  _data/backup.yml
  _data/email.yml
  _data/gaming.yml
  _data/social.yml
  _data/task.yml
Labels: update site

#4176 Add Deutsche Apotheker- und Ärztebank
  _data/banking.yml
  img/banking/apobank.png
Labels: add site

#4158 Add Santander DE
  _data/banking.yml
Labels: add site

#4156 Add 1822direkt
  _data/banking.yml
  img/banking/1822direkt.png
Labels: add site

#4972 Move 20i to Hosting
  _data/domains.yml
  _data/hosting.yml
  img/domains/20i.png
  img/hosting/20i.png
Labels: add site

#4977 Remove remaining "status" references
  CONTRIBUTING.md
  _data/banking.yml
  _data/developer.yml
  _data/health.yml
  _data/social.yml
  _deployment/tests/verify.rb
  _deployment/tests/websites_schema.yml
  api/v2/README.md
Labels: enhancement, multiple sites, update site

#4976 Fix various minor errors (spelling, grammar, punctuation, formatting)
  CONTRIBUTING.md
  EXCLUSION.md
  _deployment/tests/alexa.sh
  _deployment/tests/extensions.sh
  _deployment/tests/twitter.rb
Labels: enhancement

#4978 Add EasyDMARC
  _data/security.yml
  img/security/easydmarc.png
Labels: add site
