Repository 2factorauth/twofactorauth, pull requests merged in 2021-11, with the labels that each got.

#6244 Add Cultured Code Things Cloud
  entries/c/culturedcode.com.json
  img/c/culturedcode.com.svg
Labels: add site

#6245 Add Coil, Displate, Fairphone and PCPartPicker
  entries/c/coil.com.json
  entries/d/displate.com.json
  entries/f/fairphone.com.json
  entries/p/pcpartpicker.com.json
  img/c/coil.com.svg
  img/d/displate.com.svg
  img/f/fairphone.com.svg
  img/p/pcpartpicker.com.svg
Labels: add site, multiple sites

#6253 Add holded
  entries/h/holded.com.json
  img/h/holded.com.svg
Labels: add site

#6249 Add Matalan
  entries/m/matalan.co.uk.json
  img/m/matalan.co.uk.svg
Labels: add site

#6247 Add Waterstones
  entries/w/waterstones.com.json
  img/w/waterstones.com.svg
Labels: add site

#6246 Add Zara
  entries/z/zara.com.json
  img/z/zara.com.svg
Labels: add site

#6255 Add Fauna
  entries/f/fauna.com.json
  img/f/fauna.com.svg
Labels: add site

#6257 Update Ubisoft
  entries/u/ubisoft.com.json
  entries/u/uplay.ubi.com.json
  img/u/ubisoft.com.svg
Labels: update site

#6254 Add Breeze Airways
  entries/f/flybreeze.com.json
  img/f/flybreeze.com.svg
Labels: add site

#6261 Add Scalable Capital
  entries/s/scalable.capital.json
  img/s/scalable.capital.svg
Labels: add site

#6260 Add Oldenburgische Landesbank
  entries/o/olb.de.json
  img/o/olb.de.svg
Labels: add site

#6241 Add Fanduel
  entries/f/fanduel.com.json
  img/f/fanduel.com.svg
Labels: add site

#6256 Add Vancity
  entries/v/vancity.com.json
  img/v/vancity.com.svg
Labels: add site

#6258 Add Vanguard Australia
  entries/v/vanguard.com.au.json
Labels: add site

#6264 Supress validate-url.rb errors
  .github/workflows/repository.yml
  tests/validate-urls.rb
Labels: bug

#6266 Add Westpac site
  entries/w/westpac.com.au.json
  img/w/westpac.com.au.svg
Labels: add site

#6263 Update Yahoo Mail
  entries/m/mail.yahoo.com.json
Labels: update site

#6268 Update Hotjar
  entries/h/hotjar.com.json
  img/h/hotjar.com.svg
Labels: update site

#6269 Update MultCloud
  entries/m/multcloud.com.json
Labels: update site

#6270 Update Andrews Federal Credit Union
  entries/a/andrewsfcu.org.json
Labels: update site

#6271 Update Tangerine
  entries/t/tangerine.ca.json
Labels: update site

#6274 Update AT&T
  entries/a/att.com.json
Labels: update site

#6273 Update Swisscom
  entries/s/swisscom.ch.json
Labels: update site

#6285 Update Okta add custom-software
  entries/o/okta.com.json
Labels: update site

#6287 Update Salesforce add custom-software
  entries/s/salesforce.com.json
Labels: update site

#6267 Update Amtrak
  entries/a/amtrak.com.json
Labels: update site

#6275 Add Bankera
  entries/b/bankera.com.json
  img/b/bankera.com.svg
Labels: add site

#6259 Update Blizzard
  entries/b/blizzard.com.json
Labels: update site

#6276 Add SpectroCoin
  entries/s/spectrocoin.com.json
  img/s/spectrocoin.com.svg
Labels: add site

#6279 Add Plusnet
  entries/p/plus.net.json
  img/p/plus.net.svg
Labels: add site

#6280 Add TalkTalk
  entries/t/talktalk.co.uk.json
  img/t/talktalk.co.uk.svg
Labels: add site

#6277 Rename Moj Tele2 to Telemach
  entries/t/telemach.hr.json
  img/m/moj.tele2.hr.svg
  img/t/telemach.hr.svg
Labels: update site

#6286 Add auth0
  entries/a/auth0.com.json
  img/a/auth0.com.svg
Labels: add site

#6289 Update easybank
  entries/e/easybank.at.json
Labels: update site

#6290 Add ngrok
  entries/n/ngrok.com.json
  img/n/ngrok.com.svg
Labels: add site

#6292 Update icon for directmailmac.com
  img/d/directmailmac.com.png
Labels: update site

#6291 Improve consistency of org name
  about.html
Labels: enhancement

#6293 Remove Simple
  entries/s/simple.com.json
  img/s/simple.com.svg
Labels: remove site

#6278 Allow excluding regions
  entries/b/bankera.com.json
  entries/h/hsbc.com.json
  entries/v/vanguard.com.json
  scripts/regions.rb
  tests/region-codes.rb
  tests/schema.json
Labels: enhancement

#6300 Fix excluded regions
  scripts/regions.rb
Labels: bug

#6305 Fix excluded regions v3
  CONTRIBUTING.md
  api.md
  scripts/regions.rb
Labels: bug

#6307 Add ScaleGrid
  entries/s/scalegrid.io.json
  img/s/scalegrid.io.svg
Labels: add site

#6306 Update Orange
  entries/o/orange.fr.json
Labels: update site

#6297 Update Nextdoor
  entries/n/nextdoor.com.json
Labels: update site

#6294 Add Desmos
  entries/d/desmos.com.json
  img/d/desmos.com.svg
Labels: add site

#6309 Switch logo height constraint to max-height
  _includes/scss/tables.scss
Labels: bug, enhancement

#6296 Update N26
  entries/n/n26.com.json
Labels: update site

#6298 Update various logos
  entries/p/passhub.net.json
  entries/s/scalr.com.json
  img/a/admiral.com.svg
  img/a/aok.de.svg
  img/a/autodesk.com.svg
  img/b/bancoprovincia.com.ar.svg
  img/b/bybit.com.svg
  img/c/cibc.com.svg
  img/c/coindcx.com.svg
  img/c/coursera.org.svg
  img/d/deployhq.com.svg
  img/d/df.eu.svg
  img/e/edx.org.svg
  img/e/expensify.com.svg
  img/i/invoice.2go.com.svg
  img/l/launchdarkly.com.svg
  img/n/nicehash.com.svg
  img/p/paritex.com.svg
  img/p/passhub.net.png
  img/p/passhub.net.svg
  img/p/poloniex.com.svg
  img/q/quizlet.com.svg
  img/r/rebel.com.svg
  img/r/render.com.svg
  img/s/scalr.com.png
  img/s/scalr.com.svg
  img/s/statuscake.com.svg
  img/t/teamspeak.com.svg
  img/u/unfuddle.com.svg
Labels: update site, multiple sites

#6282 Add Remind
  entries/r/remind.com.json
  img/r/remind.com.svg
Labels: add site

#6284 Rename Netregistry to Webcentral, add 2FA support
  entries/n/netregistry.com.au.json
  entries/w/webcentral.com.au.json
  img/n/netregistry.com.au.svg
  img/w/webcentral.com.au.svg
Labels: update site

#6295 Add OpenWeather
  entries/o/openweathermap.org.json
  img/o/openweathermap.org.svg
Labels: add site

#6317 Add kahoot
  entries/k/kahoot.com.json
  img/k/kahoot.com.svg
Labels: add site

#6319 Remove Zaius
  entries/z/zaius.com.json
  img/z/zaius.com.svg
Labels: remove site

#6320 Add Replit
  entries/r/replit.com.json
  img/r/replit.com.svg
Labels: add site

#6314 Update Stack Exchange
  entries/s/stackexchange.com.json
Labels: update site

#6316 Add Service NSW
  entries/s/service.nsw.gov.au.json
  img/s/service.nsw.gov.au.svg
Labels: add site

#6321 Add Aspiration
  entries/a/aspiration.com.json
  img/a/aspiration.com.svg
Labels: add site

#6327 Update Hack The Box domain
  entries/h/hackthebox.com.json
  entries/h/hackthebox.eu.json
  img/h/hackthebox.com.svg
Labels: update site

#6288 Add DAB BNP Paribas
  entries/d/dab-bank.de.json
  img/d/dab-bank.de.svg
Labels: add site

#6329 Update documentation link for teamviewer
  entries/t/teamviewer.com.json
Labels: update site
