Repository 2factorauth/twofactorauth, pull requests merged in 2021-09, with the labels that each got.

#6101 Add NHS App
  entries/n/nhsapp.service.nhs.uk.json
  img/n/nhsapp.service.nhs.uk.svg
Labels: add site

#6105 Update SingPass
  entries/s/singpass.gov.sg.json
Labels: update site

#6094 Add San José State University
  entries/s/sjsu.edu.json
  img/s/sjsu.edu.svg
Labels: add site

#6103 Update Shopify
  entries/s/shopify.com.json
Labels: update site

#6104 Replace custom-hardware references with U2F
  entries/b/boxcryptor.com.json
  entries/b/braintreepayments.com.json
  entries/d/dmarcian.com.json
  entries/o/onelogin.com.json
  entries/p/porkbun.com.json
  entries/s/stripe.com.json
  entries/v/vanguard.com.json
  entries/w/weclapp.com.json
Labels: update site, multiple sites

#6109 Modify curl test
  tests/validate-urls.rb
Labels: bug

#6108 Multiple tweet messages
  _data/languages.yml
  js/social-media.js
Labels: enhancement

#6107 Use absolute paths for notes
  entries/c/chase.com.json
  entries/i/internetbs.net.json
  tests/schema.json
  tests/validate-urls.rb
Labels: bug

#6111 Use relative /notes/ path for website
  _includes/html/desktop-table.html
  _includes/html/mobile-table.html
Labels: enhancement

#6106 Add more regions
  _data/regions.yml
Labels: enhancement

#5764 Update TVTime
  entries/t/tvtime.com.json
  img/t/tvtime.com.png
  img/t/tvtime.com.svg
Labels: update site

#5910 Remove Skatteverket
  entries/s/skatteverket.se.json
  img/s/skatteverket.se.svg
Labels: remove site

#6112 Update CrashPlan
  entries/c/crashplan.com.json
Labels: update site

#6113 Modify APIv3.rb to produce tfa.json
  scripts/APIv3.rb
Labels: bug

#6114 Documentation Improvements
  CONTRIBUTING.md
  EXCLUSION.md
  README.md
  api.md
Labels: enhancement

#6118 Add Rubocop test and fix errors
  .github/workflows/repository.yml
  scripts/APIv3.rb
  scripts/convert-images.rb
  scripts/convert.rb
  scripts/join-entries.rb
  scripts/regions.rb
  tests/alexa.rb
  tests/twitter.rb
  tests/validate-images.rb
  tests/validate-urls.rb
Labels: enhancement

#6126 Add Survicate
  entries/s/survicate.com.json
  img/s/survicate.com.svg
Labels: add site

#6125 Update TD
  entries/t/td.com.json
Labels: update site

#6127 Update Crowd Supply
  entries/c/crowdsupply.com.json
  img/c/crowdsupply.com.svg
Labels: update site

#6130 Update Personal Capital
  entries/p/personalcapital.com.json
Labels: update site

#6128 Switch from cURL validation to httpclient
  Dockerfile
  Gemfile
  tests/validate-urls.rb
Labels: enhancement

#6119 Remove SMS Requirement from wise.com
  entries/w/wise.com.json
Labels: update site

#6122 Add My Plesk
  entries/m/my.plesk.com.json
  img/m/my.plesk.com.svg
Labels: add site

#6121 Update afip.gob.ar
  entries/a/afip.gob.ar.json
Labels: update site

#6133 Show custom-software/hardware values
  _includes/html/desktop-table.html
Labels: enhancement

#6143 Add Workflowy
  entries/w/workflowy.com.json
  img/w/workflowy.com.svg
Labels: add site

#6138 Update Sophos / Add Sophos Home
  entries/c/central.sophos.com.json
  entries/h/home.sophos.com.json
Labels: add site, update site

#6137 Add Ocado
  entries/o/ocado.com.json
  img/o/ocado.com.svg
Labels: add site

#6123 Update Clubhouse
  entries/c/clubhouse.io.json
  entries/s/shortcut.com.json
  img/c/clubhouse.io.svg
  img/s/shortcut.com.svg
Labels: update site

#6142 Add Eversign
  entries/e/eversign.com.json
  img/e/eversign.com.svg
Labels: add site

#6147 Update Adobe
  entries/a/adobe.com.json
Labels: update site
