Repository 2factorauth/twofactorauth, pull requests merged in 2021-04, with the labels that each got.

#5345 Update Action Network
  _data/communication.yml
Labels: update site

#5397 Add Arduino
  _data/developer.yml
  img/developer/arduino.svg
Labels: add site

#5333 Add Coda
  _data/communication.yml
  img/communication/coda.svg
Labels: add site

#5338 Add Huobi
  _data/cryptocurrencies.yml
  img/cryptocurrencies/huobi.svg
Labels: add site

#5452 Update Artstation
  _data/social.yml
Labels: update site

#5459 Update N26
  _data/banking.yml
Labels: update site

#5463 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#5457 Update Swedbank logo
  img/banking/swedbank.png
Labels: update site

#5438 Update Fastmail
  _data/email.yml
Labels: update site

#5465 Add LocalMonero
  _data/cryptocurrencies.yml
  img/cryptocurrencies/localmonero.png
Labels: add site

#5466 Add Quidax
  _data/cryptocurrencies.yml
  img/cryptocurrencies/quidax.svg
Labels: add site

#5451 Update Quickbooks
  _data/finance.yml
Labels: update site

#5306 Update Rebel
  _data/domains.yml
  img/domains/rebel.png
  img/domains/rebel.svg
Labels: update site

#5455 Update Luno
  _data/cryptocurrencies.yml
Labels: update site

#5282 Add Deputy
  _data/task.yml
  img/task/deputy.svg
Labels: add site

#5500 Add ContentStack
  _data/developer.yml
  img/developer/contentstack.svg
Labels: add site

#5518 Add ProBit
  _data/cryptocurrencies.yml
  img/cryptocurrencies/probit.svg
Labels: add site

#5073 Remove Sprint
  _data/utilities.yml
  img/utilities/sprint.png
Labels: remove site

#5494 nfcu also has sms 2fa
  _data/banking.yml
Labels: update site

#5416 Add Freewallet
  _data/cryptocurrencies.yml
  img/cryptocurrencies/freewallet.svg
Labels: add site

#5482 Add Bitso
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitso.svg
Labels: add site

#5279 Add Canada Post
  _data/postal.yml
  img/postal/canadapost.svg
Labels: add site

#5434 Add US Mobile
  _data/utilities.yml
  img/utilities/usmobile.svg
Labels: add site

#5246 Update netcup
  _data/hosting.yml
  img/hosting/netcup.png
Labels: update site

#4243 Add Pro Wrestling Tees
  _data/retail.yml
  img/retail/prowrestlingtees.png
Labels: add site

#5081 Remove Pwnie Express
  _data/security.yml
  img/security/pwnieexpress.png
Labels: remove site

#5386 Update NordVPN Teams
  _data/vpn.yml
  img/vpn/nordvpnteams.svg
Labels: update site

#5141 Clean up HTML entities in Utilities
  _data/utilities.yml
Labels: multiple sites, update site

#5125 Update M&T Bank formatting
  _data/banking.yml
  img/banking/mtbank.png
Labels: update site

#5569 Add Swyftx
  _data/cryptocurrencies.yml
  img/cryptocurrencies/swyftx.svg
Labels: add site

#5112 Add Radius Bank
  _data/banking.yml
  img/banking/radiusbank.svg
Labels: add site

#5105 Rename ThreatMetrix to LexisNexis Risk Solutions
  _data/security.yml
  img/security/lexisnexis.png
  img/security/threatmetrix.png
Labels: update site

#5138 Add EasySendy
  _data/communication.yml
  img/communication/easysendy.png
Labels: add site

#5136 Add Pepipost
  _data/communication.yml
  img/communication/pepipost.png
Labels: add site

#5509 Update Three
  _data/utilities.yml
Labels: update site

#5556 Add VRChat
  _data/gaming.yml
  img/gaming/vrchat.png
Labels: add site

#5570 Update Plivo
  _data/developer.yml
  img/developer/plivo.png
  img/developer/plivo.svg
Labels: update site

#5574 Update Enom
  _data/domains.yml
Labels: update site

#5543 Update Nexon
  _data/gaming.yml
Labels: update site

#5576 Add OnceHub
  _data/communication.yml
  img/communication/oncehub.svg
Labels: add site

#5545 Add FTX
  _data/cryptocurrencies.yml
  img/cryptocurrencies/ftx.svg
Labels: add site

#5568 Add ConvertKit
  _data/communication.yml
  img/communication/convertkit.svg
Labels: add site

#5559 Add Notejoy
  _data/communication.yml
  img/communication/notejoy.svg
Labels: add site

#5553 Clean up docs
  API.md
  EXCLUSION.md
  README.md
Labels: enhancement

#5572 Add Demio
  _data/communication.yml
  img/communication/demio.svg
Labels: add site

#5577 Remove border radius on logos
  css/main.scss
Labels: enhancement

#5291 Update Amazon, Amazon Pay
  _data/payments.yml
  _data/retail.yml
Labels: multiple sites, update site

#5528 Update CloudApp
  _data/backup.yml
  img/backup/cloudapp.png
  img/backup/cloudapp.svg
Labels: update site

#5578 Update First Tech Federal Credit Union
  _data/banking.yml
Labels: update site

#4899 Add SecurityTrails
  _data/security.yml
  img/security/securitytrails.svg
Labels: add site

#5522 Update Bitfinex
  _data/cryptocurrencies.yml
Labels: update site

#5537 Add Bonusly
  _data/communication.yml
  img/communication/bonusly.svg
Labels: add site

#5520 Remove Bcnex
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bcnex.png
Labels: remove site

#5488 Remove Bintray
  _data/developer.yml
  img/developer/bintray.png
Labels: remove site

#5147 Add RevenueCat
  _data/developer.yml
  img/developer/revenuecat.svg
Labels: add site

#5151 Add Bill
  _data/payments.yml
  img/payments/bill.svg
Labels: add site

#5426 Add Voyager
  _data/cryptocurrencies.yml
  img/cryptocurrencies/investvoyager.svg
Labels: add site

#5429 Add Balena
  _data/iot.yml
  img/iot/balena.svg
Labels: add site

#5432 Add RightCapital
  _data/finance.yml
  img/finance/rightcapital.svg
Labels: add site

#5575 Add Actionstep
  _data/legal.yml
  img/legal/actionstep.svg
Labels: add site

#5571 Add Databox
  _data/other.yml
  img/other/databox.svg
Labels: add site

#5240 Add BitSight
  _data/security.yml
  img/security/bitsight.svg
Labels: add site

#5263 Add VeeroTech
  _data/hosting.yml
  img/hosting/veerotech.png
Labels: add site

#5350 Add Bitforex
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitforex.svg
Labels: add site

#5154 Add Clover
  _data/other.yml
  img/other/clover.svg
Labels: add site

#5585 Add Macquarie Bank
  _data/banking.yml
  img/banking/macquariebank.svg
Labels: add site

#5453 Add NairaEx
  _data/cryptocurrencies.yml
  img/cryptocurrencies/nairaex.svg
Labels: add site

#5134 Add Exmo
  _data/cryptocurrencies.yml
  img/cryptocurrencies/exmo.svg
Labels: add site

#5590 Add Envoyer
  _data/developer.yml
  img/developer/envoyer.svg
Labels: add site

#5588 Add VMware
  _data/cloud.yml
  img/cloud/vmware.svg
Labels: add site

#5555 Add Whois
  _data/domains.yml
  img/domains/whois.png
Labels: add site

#5549 Fix Bug: Broken Link in noscript tag
  _layouts/default.html
Labels: bug

#5589 Add Refersion
  _data/other.yml
  img/other/refersion.svg
Labels: add site

#5561 Update Phrase
  _data/other.yml
  img/other/phrase.png
Labels: update site

#5565 Add Assembla
  _data/developer.yml
  img/developer/assembla.svg
Labels: add site

#5277 Add PGP signed API files at deployment
  .github/workflows/gh-pages.yml
  _deployment/sign.sh
Labels: enhancement

#5591 Update Radius Bank logo
  img/banking/radiusbank.svg
Labels: update site

#5598 Link to signed JSON files
  API.md
Labels: enhancement

#5601 Migros also allows SMS 2FA
  _data/retail.yml
Labels: update site

#5596 Remove ARP Networks
  _data/hosting.yml
  img/hosting/arpnetworks.png
Labels: remove site

#5595 Update Pinboard
  _data/other.yml
Labels: update site

#5594 Update Delighted
  _data/other.yml
Labels: update site

#5609 Update Twitter
  _data/social.yml
Labels: update site

#5254 Add Server.pro
  _data/hosting.yml
  img/hosting/serverpro.svg
Labels: add site

#5256 Add Oculus
  _data/gaming.yml
  img/gaming/oculus.svg
Labels: add site

#5122 Add Parimatch
  _data/betting.yml
  img/betting/parimatch.svg
Labels: add site

#5592 Update Planning Center
  _data/other.yml
  img/other/planningcenter.png
  img/other/planningcenter.svg
Labels: update site

#5597 Add CoinTiger
  _data/cryptocurrencies.yml
  img/cryptocurrencies/cointiger.svg
Labels: add site

#5602 Add Paxos
  _data/cryptocurrencies.yml
  img/cryptocurrencies/paxos.svg
Labels: add site

#5603 Add Paritex
  _data/cryptocurrencies.yml
  img/cryptocurrencies/paritex.svg
Labels: add site

#5253 Add Hypixel
  _data/gaming.yml
  img/gaming/hypixel.png
Labels: add site

#5611 Add Valr
  _data/cryptocurrencies.yml
  img/cryptocurrencies/valr.svg
Labels: add site

#5612 Add Lenovo
  _data/retail.yml
  img/retail/lenovo.svg
Labels: add site

#5614 Add Optimizely
  _data/other.yml
  img/other/optimizely.svg
Labels: add site

#5617 Add Depop
  _data/retail.yml
  img/retail/depop.svg
Labels: add site

#5616 Add MongoDB Atlas
  _data/developer.yml
  img/developer/mongodb.png
Labels: add site

#5630 Update FTX
  _data/cryptocurrencies.yml
Labels: update site

#5620 Add When I Work
  _data/task.yml
  img/task/wheniwork.svg
Labels: add site

#5579 Adding exception info to kickstarter in others.yml
  _data/other.yml
Labels: update site

#5623 Add bitrise
  _data/developer.yml
  img/developer/bitrise.svg
Labels: add site

#5624 Add OneHub
  _data/backup.yml
  img/backup/onehub.svg
Labels: add site

#5625 Add Audiense
  _data/other.yml
  img/other/audiense.svg
Labels: add site

#5626 Add Deel
  _data/finance.yml
  img/finance/letsdeel.svg
Labels: add site

#5638 Add Postman
  _data/developer.yml
  img/developer/postman.svg
Labels: add site

#5637 Add Seneca
  _data/education.yml
  img/education/seneca.svg
Labels: add site

#5639 Add Pusher
  _data/developer.yml
  img/developer/pusher.svg
Labels: add site

#5640 Update DoorDash
  _data/food.yml
Labels: update site

#5642 Update Mittwald
  _data/hosting.yml
Labels: update site

#5643 Update Media Temple
  _data/hosting.yml
Labels: update site

#5644 Remove MedicAlert
  _data/health.yml
  img/health/medicalert.png
Labels: remove site

#5645 Remove new line
  _data/hosting.yml
Labels: enhancement

#5646 Update One.com
  _data/hosting.yml
Labels: update site

#5647 Update Site5
  _data/hosting.yml
Labels: update site

#5267 Add TuneCore
  _data/entertainment.yml
  img/entertainment/tunecore.png
Labels: add site

#5605 Add Notion
  _data/communication.yml
  img/communication/notion.svg
Labels: add site

#5648 Per current ancestry.com documentation, added Email 2FA flag
  _data/other.yml
Labels: update site

#5544 Add Canary
  _data/iot.yml
  img/iot/canary.svg
Labels: add site

#5406 Remove Powerstream/Add Alectra
  _data/utilities.yml
  img/utilities/alectra.svg
  img/utilities/powerstream.png
Labels: update site

#5661 Remove PointDNS
  _data/domains.yml
  img/domains/pointdns.png
Labels: remove site

#5656 Remove ChunkHost
  _data/hosting.yml
  img/hosting/chunkhost.png
Labels: remove site

#5658 Remove 10Dollar
  _data/domains.yml
  img/domains/10dollar.png
Labels: remove site

#5667 Update Pagerduty
  _data/developer.yml
Labels: update site

#5665 Update Doodle
  _data/communication.yml
Labels: update site

#5666 Update Hotjar
  _data/developer.yml
Labels: update site

#5641 Update No-IP
  _data/domains.yml
Labels: update site

#5632 Update VoIP.ms
  _data/utilities.yml
Labels: update site

#5618 Add Alexa
  _data/other.yml
  img/other/alexa.svg
Labels: add site

#5669 Add Drift
  _data/other.yml
  img/other/drift.svg
Labels: add site
