Repository 2factorauth/twofactorauth, pull requests merged in 2021-12, with the labels that each got.

#6332 Add Etana Custody
  entries/e/etana.com.json
  img/e/etana.com.svg
Labels: add site

#6322 Add Pipedream (Requestbin)
  entries/p/pipedream.com.json
  img/p/pipedream.com.svg
Labels: add site

#6336 Standardized Yubikey OTP to Yubico OTP
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.yml
  entries/g/glesys.com.json
  entries/o/okta.com.json
Labels: update site, multiple sites

#6333 Add M1 Finance
  entries/m/m1finance.com.json
  img/m/m1finance.com.svg
Labels: add site

#6331 Add Namebase
  entries/n/namebase.io.json
  img/n/namebase.io.svg
Labels: add site

#6343 Add Wiggle
  entries/w/wiggle.co.uk.json
  img/w/wiggle.co.uk.svg
Labels: add site

#6347 Add fedex.com
  entries/f/fedex.com.json
  img/f/fedex.com.svg
Labels: add site

#6344 Add SouthXchange
  entries/s/southxchange.com.json
  img/s/southxchange.com.svg
Labels: add site

#6345 Specify firsttechfed.com custom-software implementation
  entries/f/firsttechfed.com.json
Labels: update site

#6349 Update Roblox
  entries/r/roblox.com.json
Labels: update site

#6351 bahn.com: Fix documentation link
  entries/b/bahn.com.json
Labels: update site

#6318 Update various logos
  entries/a/axosinvest.com.json
  img/a/activecampaign.com.svg
  img/a/anses.gob.ar.svg
  img/a/arcadia.com.svg
  img/a/arlo.com.svg
  img/a/avast.com.svg
  img/a/axosinvest.com.svg
  img/b/betterment.com.svg
  img/c/cyon.ch.svg
  img/d/directv.com.svg
  img/d/dteenergy.com.svg
  img/e/easydmarc.com.svg
  img/e/expressvpn.com.svg
  img/f/fandom.com.svg
  img/f/finnair.com.svg
  img/f/flatex.de.svg
  img/g/gls-one.de.svg
  img/i/immowelt.de.svg
  img/n/norton.com.svg
  img/o/osde.com.ar.svg
  img/p/plastiq.com.svg
  img/p/privacy.com.svg
  img/q/quora.com.svg
  img/r/rbltracker.com.png
  img/s/singpass.gov.sg.svg
  img/t/toggl.com.svg
  img/t/torguard.net.svg
Labels: update site, multiple sites

#6352 Update Finance Icon
  _data/categories.json
Labels: enhancement

#6354 Add T. Rowe Price
  entries/t/troweprice.com.json
  img/t/troweprice.com.svg
Labels: add site

#6355 Update termius
  entries/t/termius.com.json
Labels: update site

#6357 Disable Rubocop Style/CombinableLoops
  scripts/APIv2.rb
  scripts/APIv3.rb
Labels: bug

#6356 Add CoinMarketCap
  entries/c/coinmarketcap.com.json
  img/c/coinmarketcap.com.svg
Labels: add site

#6362 Revert rubocop workarounds
  scripts/APIv2.rb
  scripts/APIv3.rb
Labels: bug

#6353 Add eufySecurity
  entries/e/eufylife.com.json
  img/e/eufylife.com.svg
Labels: add site

#6366 Rename Pixel by Labcorp to Labcorp OnDemand
  entries/o/ondemand.labcorp.com.json
  img/o/ondemand.labcorp.com.svg
  img/p/pixel.labcorp.com.svg
Labels: update site

#6369 Add Cinemark theatre chain
  entries/c/cinemark.com.json
  img/c/cinemark.com.svg
Labels: add site
