Repository 2factorauth/twofactorauth, pull requests merged in 2021-05, with the labels that each got.

#5655 Add Register365
  _data/domains.yml
  img/domains/register365.svg
Labels: add site

#5652 Update Looker
  _data/developer.yml
  img/developer/looker.png
  img/developer/looker.svg
Labels: add site

#5653 Add Mercury to banking
  _data/banking.yml
  img/banking/mercury.svg
Labels: add site

#5663 Add Caspio
  _data/developer.yml
  img/developer/caspio.svg
Labels: add site

#5659 Add Domain
  _data/other.yml
  img/other/domain.svg
Labels: add site

#5660 Update Netim
  _data/domains.yml
  img/domains/netim.png
  img/domains/netim.svg
Labels: update site

#5650 Add Heap
  _data/other.yml
  img/other/heap.svg
Labels: add site

#5668 Add CleverTap
  _data/other.yml
  img/other/clevertap.svg
Labels: add site

#5671 Add TermsFeed
  _data/legal.yml
  img/legal/termsfeed.svg
Labels: add site

#5683 Add FastComet
  _data/hosting.yml
  img/hosting/fastcomet.svg
Labels: add site

#5682 Add Spreedly
  _data/payments.yml
  img/payments/spreedly.svg
Labels: add site

#5681 Remove Raizers
  _data/investing.yml
  img/investing/raizers.png
Labels: remove site

#5680 Update John Hancock
  _data/investing.yml
Labels: update site

#5675 Update Cox
  _data/utilities.yml
  img/utilities/cox.png
  img/utilities/cox.svg
Labels: update site

#5679 Update HealthEquity
  _data/investing.yml
Labels: update site

#5672 Add Smartly.io
  _data/other.yml
  img/other/smartlyio.svg
Labels: add site

#5678 Remove CA Technologies
  _data/other.yml
  img/other/ca-technologies.png
Labels: remove site

#5636 Add Kerboodle
  _data/education.yml
  img/education/kerboodle.svg
Labels: add site

#5676 Update signNow
  _data/other.yml
  img/other/signnow.png
  img/other/signnow.svg
Labels: update site

#5692 Add Semrush
  _data/other.yml
  img/other/semrush.svg
Labels: add site

#5622 Add QuestionPro
  _data/communication.yml
  img/communication/questionpro.svg
Labels: add site

#5621 Add StormGain
  _data/cryptocurrencies.yml
  img/cryptocurrencies/stormgain.svg
Labels: add site

#5689 Add CoinSmart
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinsmart.svg
Labels: add site

#5657 Update InMotion Hosting
  _data/hosting.yml
  img/hosting/inmotion.png
  img/hosting/inmotion.svg
Labels: update site

#5649 Add Termly
  _data/legal.yml
  img/legal/termly.svg
Labels: add site

#5582 Add Oracle Cloud
  _data/cloud.yml
  img/cloud/oracle.svg
Labels: add site

#5687 Add Coinberry
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinberry.svg
Labels: add site

#5260 Add Litmus
  _data/communication.yml
  img/communication/litmus.svg
Labels: add site

#5262 Update Box
  _data/backup.yml
Labels: update site

#5433 Add Atrium Health
  _data/health.yml
  img/health/atriumhealth.svg
Labels: add site

#5587 Add River Financial
  _data/cryptocurrencies.yml
  img/cryptocurrencies/river.svg
Labels: add site

#5586 Add Automate.io
  _data/other.yml
  img/other/automateio.svg
Labels: add site

#5584 Add Checkfront
  _data/other.yml
  img/other/checkfront.svg
Labels: add site

#5583 Add SimplyBook
  _data/other.yml
  img/other/simplybook.svg
Labels: add site

#5562 Add Frame
  _data/other.yml
  img/other/frame.svg
Labels: add site

#5550 Add Shrimpy
  _data/cryptocurrencies.yml
  img/cryptocurrencies/shrimpy.png
Labels: add site

#5548 Add 123 Form Builder
  _data/developer.yml
  img/developer/123formbuilder.svg
Labels: add site

#5560 Add Lokalise
  _data/developer.yml
  img/developer/lokalise.svg
Labels: add site

#5558 Add UpdraftPlus
  _data/backup.yml
  img/backup/updraftplus.svg
Labels: add site

#5535 Update ID.me
  _data/identity.yml
Labels: update site

#5538 Add SmartSurvey
  _data/communication.yml
  img/communication/smartsurvey.svg
Labels: add site

#5536 Update bitwarden
  _data/identity.yml
Labels: update site

#5552 Add Elastic Cloud
  _data/cloud.yml
  img/cloud/elasticcloud.svg
Labels: add site

#5542 Add Brex
  _data/finance.yml
  img/finance/brex.svg
Labels: add site

#5566 Add Frontify
  _data/communication.yml
  img/communication/frontify.svg
Labels: add site

#5541 Add Integromat
  _data/other.yml
  img/other/integromat.svg
Labels: add site

#5532 Add StockX
  _data/retail.yml
  img/retail/stockx.svg
Labels: add site

#5539 Add SoGoSurvey
  _data/communication.yml
  img/communication/sogosurvey.svg
Labels: add site

#5526 Add WordFence
  _data/security.yml
  img/security/wordfence.svg
Labels: add site

#5507 Add Atera
  _data/remote.yml
  img/remote/atera.svg
Labels: add site

#5510 Add Fathom
  _data/other.yml
  img/other/fathom.svg
Labels: add site

#5567 Add Nimbus Note
  _data/task.yml
  img/task/nimbusnote.svg
Labels: add site

#5573 Add HappyFox
  _data/other.yml
  img/other/happyfox.svg
Labels: add site

#5564 Add TherapyNotes
  _data/health.yml
  img/health/therapynotes.svg
Labels: add site

#5599 Add CoinField
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinfield.svg
Labels: add site

#5600 Add Phemex
  _data/cryptocurrencies.yml
  img/cryptocurrencies/phemex.svg
Labels: add site

#5604 Add Headspace
  _data/health.yml
  img/health/headspace.svg
Labels: add site

#5531 Add Unleashed Inventory
  _data/other.yml
  img/other/unleashed.svg
Labels: add site

#5551 Add BitBar
  _data/developer.yml
  img/developer/bitbar.svg
Labels: add site

#5527 Add EmailMeForm
  _data/communication.yml
  img/communication/emailmeform.svg
Labels: add site

#5530 Add Splashtop
  _data/remote.yml
  img/remote/splashtop.svg
Labels: add site

#5634 Add Passfolio
  _data/investing.yml
  img/investing/passfolio.svg
Labels: add site

#5523 Update Bitstamp
  _data/cryptocurrencies.yml
Labels: update site

#5519 Update Anycoin Direct
  _data/cryptocurrencies.yml
Labels: update site

#5521 Update Bitbay
  _data/cryptocurrencies.yml
Labels: update site

#5484 Add ActiveCampaign
  _data/communication.yml
  img/communication/activecampaign.svg
Labels: add site

#5486 Add HostMonster
  _data/hosting.yml
  img/hosting/hostmonster.png
Labels: add site

#5563 Add Taxdome
  _data/finance.yml
  img/finance/taxdome.svg
Labels: add site

#5613 Update Poloniex
  _data/cryptocurrencies.yml
Labels: update site

#5515 Add Hevo Data
  _data/developer.yml
  img/developer/hevodata.svg
Labels: add site

#5540 Add Infinity
  _data/communication.yml
  img/communication/infinity.svg
Labels: add site

#5265 Add Campaign Monitor
  _data/communication.yml
  img/communication/campaignmonitor.svg
Labels: add site

#5508 Update DrChrono
  _data/health.yml
  img/health/drchrono.png
Labels: update site

#5688 Add Bitbuy
  _data/cryptocurrencies.yml
  img/cryptocurrencies/bitbuy.svg
Labels: add site

#5554 Add Formsite
  _data/developer.yml
  img/developer/formsite.svg
Labels: add site

#5529 Add Firmex VDR
  _data/communication.yml
  img/communication/firmex.svg
Labels: add site

#5499 Add Coinigy
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinigy.svg
Labels: add site

#5514 Add Sisense
  _data/developer.yml
  img/developer/sisense.svg
Labels: add site

#5506 Add Currencycloud
  _data/payments.yml
  img/payments/currencycloud.svg
Labels: add site

#5619 Add YouHodler
  _data/cryptocurrencies.yml
  img/cryptocurrencies/youhodler.svg
Labels: add site

#5495 Add Name Hero
  _data/hosting.yml
  img/hosting/namehero.svg
Labels: add site

#5472 Add Xink
  _data/communication.yml
  img/communication/xink.png
Labels: add site

#5469 Add Mist
  _data/other.yml
  img/other/mist.png
Labels: add site

#5444 Add American Kennel Club
  _data/other.yml
  img/other/akc.svg
Labels: add site

#5481 Add Klaviyo
  _data/other.yml
  img/other/klaviyo.svg
Labels: add site

#5524 Update BTC Markets
  _data/cryptocurrencies.yml
Labels: update site

#5512 Add Matomo Cloud Analytics
  _data/developer.yml
  img/developer/matomo.svg
Labels: add site

#5504 Add Perimeter81
  _data/security.yml
  img/security/perimeter81.png
Labels: add site

#5491 Add ServerPilot
  _data/hosting.yml
  img/hosting/serverpilot.svg
Labels: add site

#5485 Add GoPro
  _data/retail.yml
  img/retail/gopro.svg
Labels: add site

#5445 Update Fitbit
  _data/health.yml
Labels: update site

#5443 Add BullionStar
  _data/investing.yml
  img/investing/bullionstar.svg
Labels: add site

#5474 Add Iterable
  _data/communication.yml
  img/communication/iterable.svg
Labels: add site

#5439 Update Compose
  _data/developer.yml
Labels: update site

#5475 Add DNSFilter
  _data/security.yml
  img/security/dnsfilter.svg
Labels: add site

#5483 Add SmartVault
  _data/backup.yml
  img/backup/smartvault.svg
Labels: add site

#5533 Add Memsource
  _data/other.yml
  img/other/memsource.svg
Labels: add site

#5497 Add Current RMS
  _data/other.yml
  img/other/current-rms.svg
Labels: add site

#4960 Add Ameriprise Financial
  _data/banking.yml
  img/banking/ameriprise.png
Labels: add site

#5505 Add PracticePanther
  _data/legal.yml
  img/legal/practicepanther.svg
Labels: add site

#4962 Add Wolf.bet
  _data/betting.yml
  img/betting/wolfbet.png
Labels: add site

#5698 Add Vrbo
  _data/hotels.yml
  img/hotels/vrbo.svg
Labels: add site

#5697 Update Twitter script to comply with new Twitter API auth changes
  _deployment/tests/twitter.rb
Labels: bug

#5685 Add POST
  _data/email.yml
  img/email/post.svg
Labels: add site

#5693 Add Doppler
  _data/developer.yml
  img/developer/doppler.svg
Labels: add site

#5702 Update AngelList
  _data/other.yml
Labels: update site

#5701 Update Onshape
  _data/other.yml
Labels: update site

#5700 Update Indeed
  _data/other.yml
Labels: update site

#5699 Update Kinsta
  _data/hosting.yml
Labels: update site

#5704 Add Guilded
  _data/communication.yml
  img/communication/guilded.svg
Labels: add site

#5503 Add Serverspace
  _data/cloud.yml
  img/cloud/serverspace.svg
Labels: add site

#5501 Add Quidco
  _data/other.yml
  img/other/quidco.svg
Labels: add site

#5502 Add Cashrewards
  _data/other.yml
  img/other/cashrewards.svg
Labels: add site

#5513 Add Piwik
  _data/developer.yml
  img/developer/piwik.svg
Labels: add site

#5534 Add Cliniko
  _data/health.yml
  img/health/cliniko.svg
Labels: add site

#5468 Add LaunchDarkly
  _data/developer.yml
  img/developer/launchdarkly.svg
Labels: add site

#5471 Add WatchGuard
  _data/security.yml
  img/security/watchguard.svg
Labels: add site

#5615 Add Kintone
  _data/communication.yml
  img/communication/kintone.svg
Labels: add site

#5480 Add Alchemer
  _data/communication.yml
  img/communication/alchemer.svg
Labels: add site

#5479 Add Wrike
  _data/task.yml
  img/task/wrike.svg
Labels: add site

#5477 Add CoinLoan
  _data/cryptocurrencies.yml
  img/cryptocurrencies/coinloan.svg
Labels: add site

#5446 Add Knack
  _data/other.yml
  img/other/knack.svg
Labels: add site

#5437 Add Termius
  _data/remote.yml
  img/remote/termius.svg
Labels: add site

#5476 Add Replicon
  _data/other.yml
  img/other/replicon.svg
Labels: add site

#5423 Add ScaleFusion
  _data/other.yml
  img/other/scalefusion.svg
Labels: add site

#5424 Add Podio
  _data/task.yml
  img/task/podio.svg
Labels: add site

#5419 Add Hostinger
  _data/hosting.yml
  img/hosting/hostinger.svg
Labels: add site

#5478 Add BullionVault
  _data/investing.yml
  img/investing/bullionvault.png
Labels: add site

#5417 Update Gusto
  _data/finance.yml
Labels: update site

#5418 Add Accelo
  _data/other.yml
  img/other/accelo.svg
Labels: add site

#5420 Add Dext Prepare
  _data/finance.yml
  img/finance/dext.svg
Labels: add site

#5399 Add Codebase
  _data/developer.yml
  img/developer/codebase.svg
Labels: add site

#5425 Add Zerodha
  _data/investing.yml
  img/investing/zerodha.svg
Labels: add site

#5301 Add WHC
  _data/hosting.yml
  img/hosting/whc.svg
Labels: add site

#5273 Add Rev
  _data/other.yml
  img/other/rev.svg
Labels: add site

#5440 Add Honeybadger
  _data/developer.yml
  img/developer/honeybadger.svg
Labels: add site

#5435 Add Aiven
  _data/cloud.yml
  img/cloud/aiven.svg
Labels: add site

#5422 Update WealthSimple
  _data/investing.yml
Labels: update site

#5421 Add SendSafely
  _data/communication.yml
  img/communication/sendsafely.png
Labels: add site

#5309 Update CRA
  _data/government.yml
Labels: update site

#5292 Update BT
  _data/utilities.yml
  img/utilities/bt.png
  img/utilities/bt.svg
Labels: update site

#5274 Add MyGovID
  _data/government.yml
  img/government/mygovidie.png
Labels: add site

#5294 Add Hive
  _data/iot.yml
  img/iot/hive.svg
Labels: add site

#5303 Add Particle
  _data/iot.yml
  img/iot/particle.svg
Labels: add site

#5298 Add Jamf Now
  _data/other.yml
  img/other/jamfnow.svg
Labels: add site

#5310 Update Acorns
  _data/investing.yml
Labels: update site

#5297 Add cloudHQ
  _data/cloud.yml
  img/cloud/cloudhq.png
Labels: add site

#5287 Add Travala
  _data/hotels.yml
  img/hotels/travala.png
Labels: add site

#5096 Add Hostelworld
  _data/hotels.yml
  img/hotels/hostelworld.png
Labels: add site

#5470 Add Freshworks
  _data/communication.yml
  img/communication/freshworks.svg
Labels: add site
