Repository 2factorauth/twofactorauth, pull requests merged in 2021-07, with the labels that each got.

#5897 Update Whois
  entries/w/whois.com.json
  img/w/whois.com.png
  img/w/whois.com.svg
Labels: update site

#5894 Update Google Pay
  img/p/pay.google.com.svg
Labels: update site

#5896 Update Xink
  entries/x/xink.io.json
  img/x/xink.io.png
  img/x/xink.io.svg
Labels: update site

#5899 Update SendSafely
  entries/s/sendsafely.com.json
  img/s/sendsafely.com.png
  img/s/sendsafely.com.svg
Labels: update site

#5900 Update Mist
  entries/m/mist.com.json
  img/m/mist.com.png
  img/m/mist.com.svg
Labels: update site

#5903 Update Miss Hosting
  entries/m/misshosting.com.json
  img/m/misshosting.com.png
  img/m/misshosting.com.svg
Labels: update site

#5904 Update IO Zoom
  entries/i/iozoom.com.json
  img/i/iozoom.com.png
  img/i/iozoom.com.svg
Labels: update site

#5872 Update API Documentation
  api.md
Labels: enhancement

#5902 Update Network Solutions
  entries/n/networksolutions.com.json
  img/n/networksolutions.com.png
  img/n/networksolutions.com.svg
Labels: update site

#5890 Update synology
  entries/s/synology.com.json
Labels: update site

#5905 Update Cloudinary
  entries/c/cloudinary.com.json
Labels: update site

#5901 Update Twitter
  entries/t/twitter.com.json
Labels: update site

#5906 Update HostMonster
  entries/h/hostmonster.com.json
  img/h/hostmonster.com.png
  img/h/hostmonster.com.svg
Labels: update site

#5898 Update Time4VPS
  entries/t/time4vps.com.json
  entries/t/time4vps.eu.json
  img/t/time4vps.com.svg
  img/t/time4vps.eu.png
Labels: update site

#5887 Skip empty categories
  scripts/regions.rb
Labels: enhancement

#5885 Update VRChat
  entries/h/hello.vrchat.com.json
  img/h/hello.vrchat.com.png
  img/h/hello.vrchat.com.svg
Labels: update site

#5853 Add Arkansas Tech University
  entries/a/atu.edu.json
  img/a/atu.edu.svg
Labels: add site

#5919 add email subject in italian translation
  _data/languages.yml
Labels: enhancement, international

#5918 add h&m
  entries/h/hm.com.json
  img/h/hm.com.svg
Labels: add site

#5914 Add Txbit
  entries/t/txbit.io.json
  img/t/txbit.io.svg
Labels: add site

#5917 Add chess.com
  entries/c/chess.com.json
  img/c/chess.com.png
Labels: add site

#5916 Add Rejoiner
  entries/r/rejoiner.com.json
  img/r/rejoiner.com.svg
Labels: add site

#5846 Add File Name Checking to JSON Validation Tests
  entries/3/34SP.com.json
  entries/b/banking.barclaysus.com.json
  tests/validate-json.rb
Labels: enhancement

#5893 Add recovery links
  _includes/html/desktop-table.html
  _includes/scss/desktop-table.scss
Labels: enhancement

#5913 Update SiteGround
  entries/s/siteground.com.json
Labels: update site

#5938 Add Xplenty
  entries/x/xplenty.com.json
  img/x/xplenty.com.svg
Labels: add site

#5942 Update Xfinity
  entries/x/xfinity.com.json
Labels: update site

#5912 Add Philips Hue
  entries/p/philips-hue.com.json
  img/p/philips-hue.com.svg
Labels: add site

#5941 Add URL/Domain test
  .circleci/config.yml
  tests/url.rb
Labels: enhancement

#5940 Update Coinbase
  entries/c/coinbase.com.json
  img/c/coinbase.com.svg
Labels: update site

#5920 Add Keyword Validation
  tests/validate-json.rb
Labels: enhancement

#5924 Add AltCoinTrader
  entries/a/altcointrader.co.za.json
  img/a/altcointrader.co.za.svg
Labels: add site

#5925 Add BKEX
  entries/b/bkex.com.json
  img/b/bkex.com.svg
Labels: add site

#5923 Add Alterdice
  entries/a/alterdice.com.json
  img/a/alterdice.com.svg
Labels: add site

#5929 Update Microsoft Services
  entries/o/onedrive.live.com.json
  entries/o/outlook.com.json
  entries/s/skype.com.json
  entries/t/todo.microsoft.com.json
  entries/v/visualstudio.microsoft.com.json
  entries/x/xbox.com.json
Labels: multiple sites, update site

#5939 Update Unity
  entries/u/unity.com.json
  entries/u/unity3d.com.json
  img/u/unity.com.svg
Labels: update site

#5922 Add Shift4Shop
  entries/s/shift4shop.com.json
  img/s/shift4shop.com.svg
Labels: add site

#5931 Add Listrak
  entries/l/listrak.com.json
  img/l/listrak.com.svg
Labels: add site

#5806 Add Wire
  entries/w/wire.com.json
  img/w/wire.com.svg
Labels: add site

#5737 Update Pepper
  entries/p/pepper.com.json
  img/p/pepper.com.png
  img/p/pepper.com.svg
Labels: update site

#5798 Add Open University
  entries/o/open.ac.uk.json
  img/o/open.ac.uk.svg
Labels: add site

#5787 Rename Worldpay to FIS Global
  entries/f/fisglobal.com.json
  entries/w/worldpay.com.json
  img/f/fisglobal.com.svg
  img/w/worldpay.com.png
Labels: update site

#5826 Add Localize
  entries/l/localizejs.com.json
  img/l/localizejs.com.svg
Labels: add site

#5801 Update GLS Gemeinschaftsbank
  entries/g/gls.de.json
Labels: update site

#5935 Add Stessa
  entries/s/stessa.com.json
  img/s/stessa.com.svg
Labels: add site

#5944 Switch to GitHub forms in issue templates
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.md
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.yml
  .github/ISSUE_TEMPLATE/02-add-site-without-2fa.md
  .github/ISSUE_TEMPLATE/02-add-site-without-2fa.yml
  .github/ISSUE_TEMPLATE/03-update-existing-site.md
  .github/ISSUE_TEMPLATE/03-update-existing-site.yml
  .github/ISSUE_TEMPLATE/04-remove-existing-site.md
  .github/ISSUE_TEMPLATE/04-remove-existing-site.yml
Labels: enhancement

#5926 Add Cisco
  entries/c/cisco.com.json
  img/c/cisco.com.svg
Labels: add site

#5958 Update "Support 2FA" Tweet
  _data/languages.yml
Labels: enhancement

#5957 Add Trading 212
  entries/t/trading212.com.json
  img/t/trading212.com.svg
Labels: add site

#5934 Add Cordial
  entries/c/cordial.com.json
  img/c/cordial.com.svg
Labels: add site

#5937 Add PowerReviews
  entries/p/powerreviews.com.json
  img/p/powerreviews.com.svg
Labels: add site

#5953 Update Baremetrics
  entries/b/baremetrics.com.json
Labels: update site

#5952 Update Charles Schwab
  entries/s/schwab.com.json
Labels: update site

#5950 Update myPATH
  entries/m/mypath.pa.gov.json
Labels: update site

#5949 Update President's Choice Financial
  entries/p/pcfinancial.ca.json
Labels: update site

#5948 Update Discogs
  entries/d/discogs.com.json
Labels: update site

#5956 Add Veracode
  entries/v/veracode.com.json
  img/v/veracode.com.svg
Labels: add site

#5968 Remove Zocle
  entries/z/zocle.com.json
  img/z/zocle.com.png
Labels: remove site

#5966 Update Openprovider
  entries/o/openprovider.co.uk.json
  entries/o/openprovider.com.json
  img/o/openprovider.co.uk.png
  img/o/openprovider.com.svg
Labels: update site

#5964 Add FP Markets
  entries/f/fpmarkets.com.json
  img/f/fpmarkets.com.svg
Labels: add site

#5961 Update JB Hi-Fi
  entries/j/jbhifi.com.au.json
Labels: update site

#5972 Update Bitfinex
  entries/b/bitfinex.com.json
Labels: update site

#5973 Create robots.txt
  robots.txt
Labels: enhancement

#5967 Add Braze
  entries/b/braze.com.json
  img/b/braze.com.svg
Labels: add site

#5951 Update Hilton Honors
  entries/h/hilton.com.json
Labels: update site

#5945 Update NordVPN
  entries/n/nordvpn.com.json
Labels: update site

#5980 Add Onet
  entries/o/onet.pl.json
  img/o/onet.pl.svg
Labels: add site

#5987 Add TikTok
  entries/t/tiktok.com.json
  img/t/tiktok.com.svg
Labels: add site

#5981 Add Interia
  entries/i/interia.pl.json
  img/i/interia.pl.svg
Labels: add site

#5977 Add Algorithmia
  entries/a/algorithmia.com.json
  img/a/algorithmia.com.svg
Labels: add site

#5995 Update Squarespace
  entries/s/squarespace.com.json
Labels: update site

#6000 Update ProtonMail
  entries/p/protonmail.com.json
Labels: update site

#6007 Update 1Password
  entries/1/1password.com.json
Labels: update site

#6005 Add Bitbns
  entries/b/bitbns.com.json
  img/b/bitbns.com.svg
Labels: add site

#6003 Add Bubble
  entries/b/bubble.io.json
  img/b/bubble.io.svg
Labels: add site

#5997 Add Zaius
  entries/z/zaius.com.json
  img/z/zaius.com.svg
Labels: add site

#6015 Update CoinGate
  entries/c/coingate.com.json
Labels: update site

#6006 Add chatwork
  entries/c/chatwork.com.json
  img/c/chatwork.com.svg
Labels: add site

#5921 Improve Image Validation
  tests/validate-images.rb
Labels: enhancement

#6014 Add Faucetcrypto
  entries/f/faucetcrypto.com.json
  img/f/faucetcrypto.com.svg
Labels: add site

#6018 Add FaucetPay
  entries/f/faucetpay.io.json
  img/f/faucetpay.io.svg
Labels: add site

#6004 Add Bibox
  entries/b/bibox.com.json
  img/b/bibox.com.svg
Labels: add site

#5994 Add Constellix
  entries/c/constellix.com.json
  img/c/constellix.com.svg
Labels: add site

#5996 Add MessageBird
  entries/m/messagebird.com.json
  img/m/messagebird.com.svg
Labels: add site
