Repository 2factorauth/twofactorauth, pull requests merged in 2021-08, with the labels that each got.

#6011 Add Mercury Cash
  entries/m/mercury.cash.json
  img/m/mercury.cash.svg
Labels: add site

#6016 Add Cointraffic
  entries/c/cointraffic.io.json
  img/c/cointraffic.io.svg
Labels: add site

#6012 Update LiteBit
  entries/l/litebit.eu.json
Labels: update site

#6008 Add GoSquared
  entries/g/gosquared.com.json
  img/g/gosquared.com.svg
Labels: add site

#5963 Add BlueSnap
  entries/b/bluesnap.com.json
  img/b/bluesnap.com.svg
Labels: add site

#5932 Add Maropost
  entries/m/maropost.com.json
  img/m/maropost.com.svg
Labels: add site

#5936 Add Buildium
  entries/b/buildium.com.json
  img/b/buildium.com.svg
Labels: add site

#5992 Update Uber Products
  entries/u/uber.com.json
  entries/u/ubereats.com.json
  img/u/ubereats.com.svg
Labels: add site, multiple sites, update site

#5990 Add any.run
  entries/a/any.run.json
  img/a/any.run.svg
Labels: add site

#5965 Add Plus500
  entries/p/plus500.com.json
  img/p/plus500.com.svg
Labels: add site

#5933 Add Sailthru
  entries/s/sailthru.com.json
  img/s/sailthru.com.svg
Labels: add site

#6026 Remove medium.com
  entries/m/medium.com.json
  img/m/medium.com.svg
Labels: remove site

#6025 Update Ring.
  entries/r/ring.com.json
Labels: update site

#6023 Add Pixel by Labcorp
  entries/p/pixel.labcorp.com.json
  img/p/pixel.labcorp.com.svg
Labels: add site

#5999 Update Nextdoor
  entries/n/nextdoor.com.json
Labels: update site

#5974 Update Buddy
  entries/b/buddy.works.json
Labels: update site

#6002 Add Freetrade
  entries/f/freetrade.io.json
  img/f/freetrade.io.svg
Labels: add site

#6013 Add Kriptomat
  entries/k/kriptomat.io.json
  img/k/kriptomat.io.svg
Labels: add site

#6010 Add Prostocash
  entries/p/prostocash.com.json
  img/p/prostocash.com.svg
Labels: add site

#6029 feat: check for superfluous img properties in validate-images.rb
  tests/validate-images.rb
Labels: enhancement

#5991 Update Geforce
  entries/g/geforce.com.json
Labels: update site

#5877 Update npm
  entries/n/npmjs.com.json
  img/n/npmjs.com.svg
Labels: update site

#6032 Check for superfluous url entry
  entries/u/usefathom.com.json
  tests/validate-json.rb
Labels: enhancement

#6036 Update AVG
  entries/a/avg.com.json
Labels: update site

#6035 Update Avast
  entries/a/avast.com.json
Labels: update site

#5985 Add Emma
  entries/m/myemma.com.json
  img/m/myemma.com.svg
Labels: add site

#5982 Improve Entry Tags Test
  .github/workflows/repository.yml
  tests/entry-tags.rb
  tests/schema.json
  tests/validate-json.rb
Labels: enhancement

#5979 Add WP and o2
  entries/o/o2.pl.json
  entries/w/wp.pl.json
  img/o/o2.pl.svg
  img/w/wp.pl.svg
Labels: add site, multiple sites

#5988 Add Trustpilot
  entries/b/business.trustpilot.com.json
  entries/t/trustpilot.com.json
  img/t/trustpilot.com.svg
Labels: add site

#6045 Add margin to notes pages
  _layouts/notes.html
Labels: enhancement

#5989 Update Nord products
  entries/n/nordlocker.com.json
  entries/n/nordpass.com.json
  entries/n/nordvpn.com.json
  img/n/nordlocker.com.svg
Labels: add site, update site, multiple sites

#6042 Update RBC
  entries/r/rbcroyalbank.com.json
Labels: update site

#6039 Update Report URI
  entries/r/report-uri.com.json
  img/r/report-uri.com.png
  img/r/report-uri.com.svg
Labels: update site

#6040 Add Celsius
  entries/c/celsius.network.json
  img/c/celsius.network.svg
Labels: add site

#6009 Add Tauros
  entries/t/tauros.io.json
  img/t/tauros.io.svg
Labels: add site

#5998 Update Segment
  entries/s/segment.com.json
Labels: update site

#6020 Add Bitski
  entries/b/bitski.com.json
  img/b/bitski.com.svg
Labels: add site

#5962 Update BigCommerce
  entries/b/bigcommerce.com.json
Labels: update site

#6034 Update Hargreaves Lansdown
  entries/h/hl.co.uk.json
Labels: update site

#6037 Add HashiCorp Cloud
  entries/c/cloud.hashicorp.com.json
  img/c/cloud.hashicorp.com.svg
Labels: add site

#5943 Add Redis Cloud
  entries/r/redislabs.com.json
  img/r/redislabs.com.svg
Labels: add site

#5947 Update Unstoppable Domains
  entries/u/unstoppabledomains.com.json
Labels: update site

#5946 Update Pusher
  entries/p/pusher.com.json
Labels: update site

#5993 Add Laravel Vapor
  entries/v/vapor.laravel.com.json
  img/v/vapor.laravel.com.svg
Labels: add site

#6048 Add mxtoolbox.com
  entries/m/mxtoolbox.com.json
  img/m/mxtoolbox.com.svg
Labels: add site

#5487 Add Virgin Pulse
  entries/v/virginpulse.com.json
  img/v/virginpulse.com.svg
Labels: add site

#6047 Add Recruitee.com
  entries/r/recruitee.com.json
  img/r/recruitee.com.svg
Labels: add site

#6022 Fix sorting order in APIv3.rb
  scripts/APIv3.rb
Labels: bug

#6021 Add Nandos
  entries/n/nandos.co.uk.json
  img/n/nandos.co.uk.svg
Labels: add site

#5959 Update Unfuddle
  entries/u/unfuddle.com.json
Labels: update site

#6033 Add DataRobot
  entries/d/datarobot.com.json
  img/d/datarobot.com.svg
Labels: add site

#5778 Fix margin on social buttons
  _includes/scss/social-media.scss
Labels: bug

#6043 Update WoltLab
  entries/w/woltlab.com.json
  img/w/woltlab.com.png
  img/w/woltlab.com.svg
Labels: update site

#6028 Add Maropost Commerce Cloud
  entries/n/netohq.com.json
  img/n/netohq.com.svg
Labels: add site

#5712 Add WWE Network
  entries/w/wwe.com.json
  img/w/wwe.com.svg
Labels: add site

#6001 Update netcup
  entries/n/netcup.eu.json
Labels: update site

#6056 Add Mural
  entries/m/mural.co.json
  img/m/mural.co.svg
Labels: add site

#6055 Update Telstra
  entries/t/telstra.com.au.json
Labels: update site

#6041 Add solium.com
  entries/s/shareworks.com.json
  img/s/shareworks.com.svg
Labels: add site

#6053 Add Abode
  entries/g/goabode.com.json
  img/g/goabode.com.svg
Labels: add site

#5986 Add Studio Ninja
  entries/s/studioninja.co.json
  img/s/studioninja.co.svg
Labels: add site

#6044 Fix Docker Issues
  Dockerfile
  scripts/entrypoint.sh
Labels: bug

#6054 Optimise gem installs
  .github/workflows/repository.yml
  Gemfile
Labels: enhancement

#5928 Update Code of Conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#5873 Add 'Universities' Category
  _data/categories.json
  entries/a/atu.edu.json
  entries/b/bu.edu.json
  entries/c/caltech.edu.json
  entries/c/clemson.edu.json
  entries/c/cmu.edu.json
  entries/c/cod.edu.json
  entries/c/cornell.edu.json
  entries/d/duke.edu.json
  entries/e/ecu.edu.json
  entries/e/emich.edu.json
  entries/g/gatech.edu.json
  entries/h/harvard.edu.json
  entries/k/kit.edu.json
  entries/m/mcgill.ca.json
  entries/m/miamioh.edu.json
  entries/m/mines.edu.json
  entries/m/montclair.edu.json
  entries/n/ncsu.edu.json
  entries/n/nd.edu.json
  entries/o/open.ac.uk.json
  entries/p/psu.edu.json
  entries/p/purdue.edu.json
  entries/r/royalroads.ca.json
  entries/r/ryerson.ca.json
  entries/s/sentry.rmu.edu.json
  entries/s/stanford.edu.json
  entries/t/temple.edu.json
  entries/u/udel.edu.json
  entries/u/uidaho.edu.json
  entries/u/umich.edu.json
  entries/u/uni-marburg.de.json
  entries/v/vcu.edu.json
  entries/v/vt.edu.json
  entries/w/washington.edu.json
  entries/w/web.iit.edu.json
  entries/w/web.mit.edu.json
Labels: add category

#6058 Add Fidor
  entries/f/fidor.de.json
  img/f/fidor.de.svg
Labels: add site

#6057 Add Google Chat/Meet
  entries/c/chat.google.com.json
  entries/m/meet.google.com.json
  img/c/chat.google.com.svg
  img/m/meet.google.com.svg
Labels: add site, multiple sites

#5909 Update Pepipost/Add Netcore Cloud
  entries/n/netcorecloud.com.json
  entries/p/pepipost.com.json
  img/n/netcorecloud.com.svg
  img/p/pepipost.com.png
Labels: add site, update site

#6019 Add Coinzilla
  entries/c/coinzilla.com.json
  img/c/coinzilla.com.svg
Labels: add site

#6017 Add CoinPayU
  entries/c/coinpayu.com.json
  img/c/coinpayu.com.svg
Labels: add site

#6027 Update Bitwarden
  entries/b/bitwarden.com.json
Labels: update site

#5976 Add Formspree
  entries/f/formspree.io.json
  img/f/formspree.io.svg
Labels: add site

#5978 Add Malwarebytes Products
  entries/c/cloud.malwarebytes.com.json
  entries/m/malwarebytes.com.json
  entries/o/oneview.malwarebytes.com.json
  img/m/malwarebytes.com.svg
Labels: add site, multiple sites

#6061 Rename Bitwala to Nuri
  entries/n/nuri.com.json
  img/b/bitwala.com.svg
  img/n/nuri.com.svg
Labels: update site

#5791 Add Marketo
  entries/m/marketo.com.json
  img/m/marketo.com.svg
Labels: add site

#5883 Add Regions to Food
  entries/d/deliveroo.com.json
  entries/d/doordash.com.json
  entries/t/tacobell.com.json
  entries/w/wolt.com.json
Labels: update site, multiple sites

#5889 Add Regions to Entertainment
  entries/d/disneyplus.com.json
  entries/h/hotstar.com.json
  entries/q/qobuz.com.json
  entries/r/rocketbeans.tv.json
  entries/r/roku.com.json
  entries/s/sling.com.json
  entries/t/tivo.com.json
  entries/t/tunecore.com.json
  entries/v/video.ibm.com.json
Labels: update site, multiple sites

#5984 Add Delivra
  entries/d/delivra.com.json
  img/d/delivra.com.png
Labels: add site

#6065 Update Rackspace
  entries/r/rackspace.com.json
Labels: update site

#5884 Add Regions to Finance
  entries/a/aetna.com.json
  entries/a/allianz.de.json
  entries/a/altoira.com.json
  entries/a/amundi-ee.com.json
  entries/a/aok.de.json
  entries/b/bankrate.com.json
  entries/b/bglcorp.com.json
  entries/c/clearscore.com.json
  entries/c/concur.com.json
  entries/c/creditkarma.co.uk.json
  entries/c/creditkarma.com.json
  entries/d/degiro.nl.json
  entries/d/dext.com.json
  entries/e/equifax.com.json
  entries/e/exact.com.json
  entries/e/experian.co.uk.json
  entries/f/freetaxusa.com.json
  entries/f/freshbooks.com.json
  entries/f/fundingcircle.com.json
  entries/g/geico.com.json
  entries/g/gerberlife.com.json
  entries/g/gusto.com.json
  entries/h/hellowallet.com.json
  entries/h/hl.co.uk.json
  entries/h/hrblock.com.json
  entries/i/invoice.2go.com.json
  entries/i/invoiceberry.com.json
  entries/j/justworks.com.json
  entries/l/linxo.com.json
  entries/m/meineschufa.de.json
  entries/m/mint.intuit.com.json
  entries/m/moneybird.com.json
  entries/n/northwesternmutual.com.json
  entries/p/paycor.com.json
  entries/p/paytrust.quicken.com.json
  entries/p/pcfinancial.ca.json
  entries/p/popmoney.com.json
  entries/p/principal.com.json
  entries/p/progressive.com.json
  entries/p/pushcoin.com.json
  entries/q/quickfile.co.uk.json
  entries/r/rightcapital.com.json
  entries/r/rocketmortgage.com.json
  entries/s/simpletax.ca.json
  entries/t/taxact.com.json
  entries/t/tk.de.json
  entries/t/transunion.com.json
  entries/t/treasurydirect.gov.json
  entries/t/turbotax.intuit.com.json
  entries/v/vitality.co.uk.json
  img/p/paytrust.quicken.com.png
Labels: update site, multiple sites

#5875 Update 1Password
  entries/1/1password.com.json
Labels: update site

#6066 Check for duplicate site names
  entries/e/emma.ca.json
  entries/m/myemma.com.json
  tests/validate-json.rb
Labels: enhancement

#5376 Add Intuit
  entries/i/intuit.com.json
  img/i/intuit.com.svg
Labels: add site

#6068 Adding toshl.com
  entries/t/toshl.com.json
  img/t/toshl.com.svg
Labels: add site

#5720 Update installation instructions
  README.md
Labels: enhancement

#6074 Add Dependabot for actions
  .github/dependabot.yml
Labels: enhancement

#6067 Add Docker workflow
  .github/workflows/docker.yml
Labels: enhancement

#6081 Add regions to retail
  entries/a/allegro.pl.json
  entries/a/arcaplanet.it.json
  entries/b/barnesandnoble.com.json
  entries/b/bestbuy.com.json
  entries/b/bigw.com.au.json
  entries/b/bonobos.com.json
  entries/b/boxed.com.json
  entries/c/combatgent.com.json
  entries/c/comet.it.json
  entries/c/costco.com.json
  entries/d/digitec.ch.json
  entries/e/ebay-kleinanzeigen.de.json
  entries/e/ebgames.com.au.json
  entries/e/eprice.it.json
  entries/e/eventim.de.json
  entries/f/flipkart.com.json
  entries/h/homedepot.com.json
  entries/j/jbhifi.com.au.json
  entries/j/jumbo.com.ar.json
  entries/k/kohls.com.json
  entries/l/lowes.com.json
  entries/m/macys.com.json
  entries/m/mediamarkt.de.json
  entries/m/mercadolibre.com.json
  entries/n/newegg.com.json
  entries/n/nordstrom.com.json
  entries/n/northerntool.com.json
  entries/o/officedepot.com.json
  entries/p/pccasegear.com.json
  entries/p/purse.io.json
  entries/r/rakuten.com.json
  entries/r/rcwilley.com.json
  entries/s/saturn.de.json
  entries/s/shift4shop.com.json
  entries/s/shopify.com.json
  entries/s/snapdeal.com.json
  entries/s/speedcube.com.au.json
  entries/s/staples.com.json
  entries/t/target.com.json
  entries/t/thalia.de.json
  entries/t/thebay.com.json
  entries/t/tokopedia.com.json
  entries/t/trademe.co.nz.json
  entries/w/walgreens.com.json
  entries/w/walmart.com.json
  entries/w/warbyparker.com.json
  entries/w/wayfair.com.json
  entries/z/zappos.com.json
  entries/z/zooplus.com.json
  img/c/combatgent.com.png
  img/n/nordstrom.com.svg
  img/s/speedcube.com.au.png
Labels: update site, multiple sites

#6063 Update Boursorama
  entries/b/boursorama.com.json
Labels: update site

#6084 add note that fastmail requires SMS as a backup
  entries/f/fastmail.com.json
Labels: update site

#6078 Rename Radius Bank
  entries/b/bank.lendingclub.com.json
  entries/l/lendingclub.com.json
  entries/r/radiusbank.com.json
  img/r/radiusbank.com.svg
Labels: update site

#6086 Replace PNG by SVG icons
  entries/b/bhfcu.com.json
  entries/c/cosmolex.com.json
  entries/l/linxo.com.json
  entries/m/max.se.json
  entries/p/pairdomains.com.json
  entries/r/rge.com.json
  img/b/bhfcu.com.png
  img/b/bhfcu.com.svg
  img/c/cosmolex.com.png
  img/c/cosmolex.com.svg
  img/l/linxo.com.png
  img/l/linxo.com.svg
  img/m/max.se.png
  img/m/max.se.svg
  img/p/pairdomains.com.png
  img/p/pairdomains.com.svg
  img/r/rge.com.png
  img/r/rge.com.svg
Labels: update site, multiple sites

#6087 Fix file extension check for img/...
  tests/file-extensions.sh
Labels: enhancement

#6088 Add missing regions to banking
  entries/b/bbbank.de.json
  entries/b/bethpagefcu.com.json
  entries/c/communityamerica.com.json
  entries/d/dkb.de.json
  entries/h/holvi.com.json
  entries/k/key.com.json
  entries/m/mercury.com.json
  entries/s/suntrust.com.json
  entries/s/szkb.ch.json
Labels: update site, multiple sites

#6089 Add Educative
  entries/e/educative.io.json
  img/e/educative.io.svg
Labels: add site

#6085 Add Mineplex
  entries/m/mineplex.com.json
  img/m/mineplex.com.png
Labels: add site

#6091 Add BnkToTheFuture
  entries/b/bnktothefuture.com.json
  img/b/bnktothefuture.com.svg
Labels: add site

#6083 Rewrite cURL test
  .circleci/config.yml
  .github/workflows/repository.yml
  tests/url.rb
  tests/validate-urls.rb
Labels: enhancement

#6095 Fix curl test issues
  .github/workflows/repository.yml
  Dockerfile
Labels: bug

#6096 Modify docker workflow
  .github/workflows/docker.yml
Labels: bug

#6098 Docker workflow fix v3
  .github/workflows/docker.yml
Labels: bug

#6099 Only run docker publish on main repo
  .github/workflows/docker.yml
Labels: enhancement

#6093 Update Axos Bank
  entries/a/axosbank.com.json
Labels: update site

#6100 Add MBNA UK
  entries/m/mbna.co.uk.json
Labels: add site
