Repository 2factorauth/twofactorauth, pull requests merged in 2021-10, with the labels that each got.

#6150 Workaround for old CAs in httpclient
  tests/validate-urls.rb
Labels: bug

#6149 Add Render (render.com)
  entries/r/render.com.json
  img/r/render.com.svg
Labels: add site

#6153 Fix URL test not following redirects
  tests/validate-urls.rb
Labels: bug

#6148 Update jekyll exclusions & add site title
  .gitignore
  _config.yml
Labels: enhancement

#6151 Add eukhost.com
  entries/e/eukhost.com.json
  img/e/eukhost.com.svg
Labels: add site

#6152 Contribution guide clarifications
  CONTRIBUTING.md
Labels: enhancement

#6156 Add Hatch
  entries/h/hatchinvest.nz.json
  img/h/hatchinvest.nz.svg
Labels: add site

#6145 Standardize user agents
  bot.md
  css/bot.md.scss
  tests/facebook.rb
  tests/language-codes.rb
  tests/region-codes.rb
  tests/validate-urls.rb
Labels: bug, enhancement

#6144 Add Note on Passwordless to Definitions
  CONTRIBUTING.md
Labels: enhancement

#6124 Append URL to tweet message
  _config.yml
  js/social-media.js
Labels: bug

#6155 Add Nifty
  entries/n/niftypm.com.json
  img/n/niftypm.com.svg
Labels: add site

#6139 Update Dropbox
  entries/d/dropbox.com.json
  img/d/dropbox.com.svg
Labels: update site

#6146 Update Scotiabank
  entries/s/scotiabank.com.json
Labels: update site

#6157 Show TOTP on hover over checkmark
  _includes/html/desktop-table.html
Labels: enhancement

#6132 Add quality checks for entries
  .github/workflows/repository.yml
  tests/quality-checks.rb
Labels: enhancement

#6115 Add Flexera Software Vulnerability Research
  entries/a/app.flexera.com.json
  entries/f/flexera.com.json
  img/f/flexera.com.svg
Labels: add site

#6164 Add CoinRemitter.com
  entries/c/coinremitter.com.json
  img/c/coinremitter.com.svg
Labels: add site

#6163 Repurpose regions.json API file
  scripts/APIv3.rb
  scripts/regions.rb
Labels: enhancement

#6165 Add Datto
  entries/d/datto.com.json
  img/d/datto.com.svg
Labels: add site

#6243 Add Linktree
  entries/l/linktr.ee.json
  img/l/linktr.ee.svg
Labels: add site

#6229 Add Fahren Lernen
  entries/f/fahren-lernen.de.json
  img/f/fahren-lernen.de.svg
Labels: add site

#6251 Add Ko-fi
  entries/k/ko-fi.com.json
  img/k/ko-fi.com.svg
Labels: add site

#6248 Add RingCentral
  entries/r/ringcentral.com.json
  img/r/ringcentral.com.svg
Labels: add site
