Repository 2factorauth/twofactorauth, pull requests merged in 2022-03, with the labels that each got.

#6568 Update NoIP
  entries/n/noip.com.json
Labels: update site

#6463 Update Dashlane
  entries/d/dashlane.com.json
Labels: update site

#6560 Add sefcu.com (State Employees Federal Credit Union) to the directory
  entries/s/sefcu.com.json
  img/s/sefcu.com.svg
Labels: add site

#6577 Update Interactive Brokers
  entries/i/interactivebrokers.com.json
Labels: update site

#6564 Update 1Password logo
  img/1/1password.com.svg
Labels: update site

#6209 Add Metro Bank
  entries/c/commercial.metrobankonline.co.uk.json
  entries/m/metrobankonline.co.uk.json
  img/m/metrobankonline.co.uk.svg
Labels: add site

#6574 Add au
  entries/a/au.com.json
  img/a/au.com.svg
Labels: add site

#6585 Update Digital Surge
  entries/d/digitalsurge.com.au.json
Labels: update site

#6576 Update FP Markets
  entries/f/fpmarkets.com.json
Labels: update site

#6538 Add Mizuho Bank
  entries/m/mizuhobank.co.jp.json
  img/m/mizuhobank.co.jp.svg
Labels: add site

#6571 Add Morgan Stanley
  entries/m/morganstanley.com.json
  img/m/morganstanley.com.svg
Labels: add site

#6553 Add Mercari Japan
  entries/j/jp.mercari.com.json
  img/j/jp.mercari.com.svg
Labels: add site

#6593 Add Keepa
  entries/k/keepa.com.json
  img/k/keepa.com.svg
Labels: add site

#6563 Rename BitBay to Zonda
  entries/b/bitbay.net.json
  entries/z/zondaglobal.com.json
  img/b/bitbay.net.svg
  img/z/zondaglobal.com.svg
Labels: update site

#6599 Add Rewind
  entries/r/rewind.com.json
  img/r/rewind.com.svg
Labels: add site

#6597 Update Plaid
  entries/p/plaid.com.json
Labels: update site

#6600 Update Stripe
  entries/s/stripe.com.json
Labels: update site

#6601 Update Uphold
  entries/u/uphold.com.json
Labels: update site

#6590 Add Ekinet
  entries/e/eki-net.com.json
  img/e/eki-net.com.svg
Labels: add site

#6547 Add Rakuten Mobile
  entries/n/network.mobile.rakuten.co.jp.json
  img/n/network.mobile.rakuten.co.jp.svg
Labels: add site

#6566 Update MyDomain logo
  entries/m/mydomain.com.json
  img/m/mydomain.com.png
  img/m/mydomain.com.svg
Labels: update site

#6602 Update CoinTracking
  entries/c/cointracking.info.json
Labels: update site

#6605 Update HUK-Coburg
  entries/h/huk.de.json
Labels: update site

#6562 Remove unranked sites
  entries/0/007names.com.json
  entries/a/aa.net.uk.json
  entries/a/axosbank.com.json
  entries/a/axosinvest.com.json
  entries/b/bitbond.com.json
  entries/b/blackdesertonline.com.json
  entries/b/brightbox.com.json
  entries/c/cacert.org.json
  entries/c/credly.com.json
  entries/d/deutschepost.de.json
  entries/e/easy.gr.json
  entries/e/endomondo.com.json
  entries/e/epost.de.json
  entries/j/jovia.org.json
  entries/j/joviafinancial.com.json
  entries/k/kualto.com.json
  entries/m/mammoth.net.au.json
  entries/n/namespro.ca.json
  entries/n/noez.de.json
  entries/n/nordlayer.com.json
  entries/n/nordvpnteams.com.json
  entries/p/playblackdesert.com.json
  entries/r/rbcommons.com.json
  entries/s/sharkhosting.co.uk.json
  entries/t/thexyz.com.json
  entries/t/tinfoilsecurity.com.json
  entries/v/verpex.com.json
  entries/v/vpnunlimitedapp.com.json
  entries/y/youracclaim.com.json
  img/0/007names.com.png
  img/a/aa.net.uk.svg
  img/b/bitbond.com.svg
  img/b/blackdesertonline.com.svg
  img/b/brightbox.com.svg
  img/c/cacert.org.png
  img/c/credly.com.svg
  img/d/deutschepost.de.svg
  img/e/easy.gr.svg
  img/e/endomondo.com.svg
  img/e/epost.de.svg
  img/j/jovia.org.svg
  img/j/joviafinancial.com.svg
  img/k/kualto.com.svg
  img/m/mammoth.net.au.png
  img/n/namespro.ca.png
  img/n/noez.de.svg
  img/n/nordlayer.com.svg
  img/n/nordvpnteams.com.svg
  img/p/playblackdesert.com.svg
  img/r/rbcommons.com.png
  img/s/sharkhosting.co.uk.svg
  img/t/thexyz.com.svg
  img/t/tinfoilsecurity.com.png
  img/v/verpex.com.svg
  img/v/vpnunlimitedapp.com.svg
  img/y/youracclaim.com.svg
Labels: update site, remove site, multiple sites

#6575 Add Monex
  entries/m/monex.co.jp.json
  img/m/monex.co.jp.svg
Labels: add site

#6591 Docker workflow - Use major version instead of exact
  .github/workflows/docker.yml
Labels: enhancement

#6615 Update OKX
  entries/o/okex.com.json
  entries/o/okx.com.json
  img/o/okex.com.svg
  img/o/okx.com.svg
Labels: update site

#6565 Add SolarWinds
  entries/p/papertrailapp.com.json
  entries/p/pingdom.com.json
  entries/s/solarwinds.com.json
  img/p/papertrailapp.com.svg
  img/p/pingdom.com.svg
  img/s/solarwinds.com.svg
Labels: add site, update site

#6616 Adds SaxoTraderGo
  entries/h/home.saxo.json
  img/h/home.saxo.svg
Labels: add site

#6621 Add Epidemic Sound
  entries/e/epidemicsound.com.json
  img/e/epidemicsound.com.svg
Labels: add site

#6623 Add Storyblocks
  entries/s/storyblocks.com.json
  img/s/storyblocks.com.svg
Labels: add site

#6627 Add Sendcloud
  entries/s/sendcloud.com.json
  img/s/sendcloud.com.svg
Labels: add site

#6625 Update Trovo
  entries/t/trovo.live.json
Labels: update site

#6603 Add CommSec
  entries/c/commsec.com.au.json
  img/c/commsec.com.au.svg
Labels: add site

#6628 Add PostNL
  entries/p/postnl.nl.json
  img/p/postnl.nl.svg
Labels: add site

#6630 Update JustGiving
  entries/j/justgiving.com.json
Labels: update site
