Repository 2factorauth/twofactorauth, pull requests merged in 2022-08, with the labels that each got.

#6886 Update Firefox & Pocket
  entries/a/accounts.firefox.com.json
  entries/g/getpocket.com.json
Labels: update site

#6885 Update Planning Center
  entries/p/planningcenter.com.json
Labels: update site

#6889 OCI domains updated
  entries/c/cloud.oracle.com.json
  img/c/cloud.oracle.com.svg
Labels: update site

#6856 Add missing custom-* data (part 3)
  entries/b/bitcoin.de.json
  entries/b/blockchain.com.json
  entries/b/blockchain.info.json
  entries/c/caltech.edu.json
  entries/c/capitalone.com.json
  entries/c/cmu.edu.json
  entries/c/connectwise.com.json
  entries/c/cornell.edu.json
  entries/c/cryptonator.com.json
  entries/d/desjardins.com.json
  entries/d/dreamhost.com.json
  entries/d/duke.edu.json
  entries/f/finnair.com.json
  entries/g/garena.sg.json
  entries/g/gemini.com.json
  entries/i/infomaniak.com.json
  entries/i/ing.lu.json
  entries/i/interactivebrokers.com.json
  entries/j/join.me.json
  entries/m/mailbox.org.json
  entries/m/mercadopago.com.json
  entries/n/navyfederal.org.json
  entries/n/nd.edu.json
  entries/p/pobox.com.json
  entries/u/ukfast.co.uk.json
  entries/u/usaa.com.json
  entries/w/washington.edu.json
  img/b/blockchain.com.svg
Labels: update site, multiple sites

#6891 Add University of Pennsylvania
  entries/u/upenn.edu.json
  img/u/upenn.edu.svg
Labels: add site

#6894 Add DMOJ
  entries/d/dmoj.ca.json
  img/d/dmoj.ca.svg
Labels: add site

#6895 Add Mattermost
  entries/m/mattermost.com.json
  img/m/mattermost.com.svg
Labels: add site

#6892 Add University of Cambridge
  entries/c/cam.ac.uk.json
  img/c/cam.ac.uk.png
Labels: add site

#6893 Add University of Oxford
  entries/o/ox.ac.uk.json
  img/o/ox.ac.uk.svg
Labels: add site

#6896 Add bol.com
  entries/b/bol.com.json
  img/b/bol.com.svg
Labels: add site

#6880 Add baloise.ch
  entries/b/baloise.ch.json
  img/b/baloise.ch.svg
Labels: add site

#6901 Update dependencies
  Gemfile
Labels: dependencies

#6906 Update host & specify PAGES_REPO_NWO for jekyll
  .github/workflows/repository.yml
Labels: bug

#6897 Add Swedish public transport
  entries/s/skanetrafiken.se.json
  entries/v/vasttrafik.se.json
  img/s/skanetrafiken.se.svg
  img/v/vasttrafik.se.svg
Labels: add site

#6904 Add Teleport
  entries/g/goteleport.com.json
  img/g/goteleport.com.svg
Labels: add site

#6907 Update Twitter Card
  _config.yml
  img/icons/social-card.png
Labels: enhancement

#6911 Update BMO Harris Bank (#6908)
  entries/b/bmoharris.com.json
Labels: update site

#6909 Add Revolut
  entries/r/revolut.com.json
  img/r/revolut.com.svg
Labels: add site

#6912 Exclude entries dir from Jekyll build
  _config.yml
Labels: enhancement

#6914 Add zyBooks
  entries/z/zybooks.com.json
  img/z/zybooks.com.svg
Labels: add site

#6922 Update issue template "add-site-with-2fa"
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.yml
Labels: enhancement

#6917 Add Y!mobile
  entries/y/ymobile.jp.json
  img/y/ymobile.jp.svg
Labels: add site

#6921 Add Arizona State University
  entries/a/asu.edu.json
  img/a/asu.edu.svg
Labels: add site

#6927 Update Optum Bank
  entries/o/optumbank.com.json
Labels: update site

#6933 Update bitFlyer
  entries/b/bitflyer.com.json
Labels: update site

#6930 Add PayPay
  entries/p/paypay.ne.jp.json
  img/p/paypay.ne.jp.svg
Labels: add site

#6937 Update Paysafecard
  entries/p/paysafecard.com.json
Labels: update site

#6934 Add Bilibili
  entries/b/bilibili.com.json
  img/b/bilibili.com.svg
Labels: add site

#6936 Update CEX.io
  entries/c/cex.io.json
Labels: update site

#6939 Add Freehostia
  entries/f/freehostia.com.json
  img/f/freehostia.com.svg
Labels: add site

#6941 Add System76
  entries/s/system76.com.json
  img/s/system76.com.svg
Labels: add site
