Repository 2factorauth/twofactorauth, pull requests merged in 2022-01, with the labels that each got.

#6370 Add pandadoc
  entries/p/pandadoc.com.json
  img/p/pandadoc.com.svg
Labels: add site

#6375 Add Qantas
  entries/q/qantas.com.json
  img/q/qantas.com.svg
Labels: add site

#6379 Add Prezi
  entries/p/prezi.com.json
  img/p/prezi.com.svg
Labels: add site

#6367 Add Home Assistant to IOT category
  entries/h/home-assistant.io.json
  img/h/home-assistant.io.svg
Labels: add site

#6371 Add Larian
  entries/l/larian.com.json
  img/l/larian.com.png
Labels: add site

#6363 Add Canada Computers & Electronics
  entries/c/canadacomputers.com.json
  img/c/canadacomputers.com.svg
Labels: add site

#6386 Remove Houseparty
  entries/h/houseparty.com.json
  img/h/houseparty.com.svg
Labels: remove site

#6373 Add MyAnimeList
  entries/m/myanimelist.net.json
  img/m/myanimelist.net.svg
Labels: add site

#6380 Update some doc links
  entries/c/cloudflare.com.json
  entries/n/nordvpn.com.json
  entries/u/ui.com.json
Labels: update site, multiple sites

#6372 Add CardMarket
  entries/c/cardmarket.com.json
  img/c/cardmarket.com.svg
Labels: add site

#6376 Add Stake/HelloStake
  entries/h/hellostake.com.json
  img/h/hellostake.com.svg
Labels: add site

#6378 Change 'Global' region href to /int/
  _includes/html/navbar.html
Labels: enhancement

#6374 Add OzBargain
  entries/o/ozbargain.com.au.json
  img/o/ozbargain.com.au.svg
Labels: add site

#6387 Add Letterboxd
  entries/l/letterboxd.com.json
  img/l/letterboxd.com.svg
Labels: add site

#6384 Update CoinSpot
  entries/c/coinspot.com.au.json
  img/c/coinspot.com.au.svg
Labels: update site

#6383 Add Polywork
  entries/p/polywork.com.json
  img/p/polywork.com.svg
Labels: add site

#6397 Add Rumble Network Discovery
  entries/r/rumble.run.json
  img/r/rumble.run.svg
Labels: add site

#6389 Add PTV
  entries/p/ptv.vic.gov.au.json
  img/p/ptv.vic.gov.au.svg
Labels: add site

#6385 Add Digital Surge
  entries/d/digitalsurge.com.au.json
  img/d/digitalsurge.com.au.svg
Labels: add site

#6392 Add AfterPay
  entries/a/afterpay.com.json
  img/a/afterpay.com.svg
Labels: add site

#6394 Add Amazing Marvin
  entries/a/amazingmarvin.com.json
  img/a/amazingmarvin.com.png
Labels: add site

#6161 Add Mos.ru
  entries/m/mos.ru.json
  img/m/mos.ru.svg
Labels: add site

#6401 Add Zip
  entries/z/zip.co.json
  img/z/zip.co.svg
Labels: add site

#6403 Add Otto.de
  entries/o/otto.de.json
  img/o/otto.de.svg
Labels: add site

#6406 Update Steam
  entries/s/store.steampowered.com.json
Labels: update site

#6408 Add Getscreen.me
  entries/g/getscreen.me.json
  img/g/getscreen.me.svg
Labels: add site

#6398 Add Bupa
  entries/b/bupa.com.au.json
  img/b/bupa.com.au.svg
Labels: add site

#6364 Add Green Man Gaming
  entries/g/greenmangaming.com.json
  img/g/greenmangaming.com.svg
Labels: add site

#6299 Update guildwars2.com.json to include arena.net
  entries/g/guildwars2.com.json
Labels: update site

#6302 Update HSBC UK
  entries/h/hsbc.co.uk.json
Labels: update site

#6303 Add HSBC US
  entries/u/us.hsbc.com.json
Labels: add site

#6360 Add Brilliant
  entries/b/brilliant.org.json
  img/b/brilliant.org.svg
Labels: add site

#6410 Update PCCaseGear
  entries/p/pccasegear.com.json
Labels: update site

#6407 Add Nutstore
  entries/j/jianguoyun.com.json
  img/j/jianguoyun.com.svg
Labels: add site

#6391 Improve search performance
  js/search.js
Labels: enhancement

#6400 Add region tags to food entries
  entries/s/starbucks.com.json
  entries/z/zomato.com.json
Labels: update site

#6411 Update Square Enix authentication methods and domain.
  entries/n/na.square-enix.com.json
  entries/s/square-enix-games.com.json
  img/s/square-enix-games.com.svg
Labels: update site

#6416 Add Service Victoria
  entries/s/service.vic.gov.au.json
  img/s/service.vic.gov.au.svg
Labels: add site

#6412 Add TaxBit
  entries/t/taxbit.com.json
  img/t/taxbit.com.svg
Labels: add site

#6350 Add Poli Systems
  entries/p/polisystems.ch.json
  img/p/polisystems.ch.svg
Labels: add site

#6418 Update Steam
  entries/s/store.steampowered.com.json
Labels: update site

#6419 Remove Bananatag
  entries/b/bananatag.com.json
  img/b/bananatag.com.svg
Labels: remove site

#6281 Clean up education category
  entries/a/antagning.se.json
  entries/c/collegeboard.org.json
  entries/c/csn.se.json
  entries/c/cwnp.com.json
  entries/k/knowbe4.com.json
  entries/m/mysqa.org.uk.json
  entries/u/ucas.com.json
  img/c/cwnp.com.png
Labels: update site, multiple sites

#6424 Remove favicon.ico
  img/icons/favicon.ico
  tests/file-extensions.sh
Labels: enhancement

#6423 Remove various sites due to Alexa rank
  entries/b/basiscode.com.json
  entries/c/chatgrape.com.json
  entries/c/cloud.ca.json
  entries/c/coinapult.com.json
  entries/c/coincafe.com.json
  entries/f/fruux.com.json
  entries/g/glesys.com.json
  entries/i/icuk.net.json
  entries/l/linxo.com.json
  entries/m/metaname.net.json
  entries/n/nimbox.co.uk.json
  entries/o/oderland.se.json
  entries/p/passhub.net.json
  entries/r/rbltracker.com.json
  entries/s/syspectr.com.json
  entries/u/userify.com.json
  entries/w/watchmanmonitoring.com.json
  img/b/basiscode.com.png
  img/c/chatgrape.com.svg
  img/c/cloud.ca.svg
  img/c/coinapult.com.svg
  img/c/coincafe.com.png
  img/f/fruux.com.svg
  img/g/glesys.com.svg
  img/i/icuk.net.png
  img/l/linxo.com.svg
  img/m/metaname.net.png
  img/n/nimbox.co.uk.png
  img/o/oderland.se.svg
  img/p/passhub.net.svg
  img/r/rbltracker.com.png
  img/s/syspectr.com.png
  img/u/userify.com.svg
  img/w/watchmanmonitoring.com.png
Labels: remove site, multiple sites

#6324 Add Typeracer
  entries/t/typeracer.com.json
  img/t/typeracer.com.png
Labels: add site

#6425 Update LogMeIn
  entries/l/logmein.com.json
Labels: update site

#6427 Add Quicken
  entries/q/quicken.com.json
  img/q/quicken.com.svg
Labels: add site

#6426 Add 3Commas
  entries/3/3commas.io.json
  img/3/3commas.io.svg
Labels: add site

#6377 Update U2F icon
  _includes/scss/desktop-table.scss
  img/u2f.svg
Labels: enhancement

#6429 Add Payback Loyalty Program
  entries/p/payback.de.json
  img/p/payback.de.svg
Labels: add site

#6420 Add ALDImobile
  entries/a/aldimobile.com.au.json
  img/a/aldimobile.com.au.svg
Labels: add site

#6438 Add Santa Clara University
  entries/s/scu.edu.json
  img/s/scu.edu.svg
Labels: add site

#6443 Update StockX
  img/s/stockx.com.svg
Labels: update site

#6436 Update CommunityAmerica CU
  entries/c/communityamerica.com.json
  img/c/communityamerica.com.svg
Labels: update site

#6449 Subdirectory name test
  tests/validate-json.rb
Labels: enhancement

#6444 Add Finary
  entries/f/finary.com.json
  img/f/finary.com.svg
Labels: add site

#6455 Add Similarweb
  entries/s/similarweb.com.json
  img/s/similarweb.com.svg
Labels: add site

#6452 Add Stan
  entries/s/stan.com.au.json
  img/s/stan.com.au.svg
Labels: add site

#6348 Focus and select search input
  js/main.js
Labels: enhancement

#6451 Add Jetstar
  entries/j/jetstar.com.json
  img/j/jetstar.com.svg
Labels: add site

#6213 Add regions to investing
  entries/a/acorns.com.json
  entries/a/axosinvest.com.json
  entries/b/betterment.com.json
  entries/c/capitalgroup.com.json
  entries/e/etoro.com.json
  entries/e/etrade.com.json
  entries/f/flatex.de.json
  entries/i/ig.com.json
  entries/j/johnhancock.com.json
  entries/m/manulife.ca.json
  entries/m/merrilledge.com.json
  entries/n/nutmeg.com.json
  entries/o/onvista-bank.de.json
  entries/p/passfolio.us.json
  entries/p/personalcapital.com.json
  entries/p/prudential.com.json
  entries/q/questrade.com.json
  entries/r/rbcdirectinvesting.com.json
  entries/r/robinhood.com.json
  entries/s/sigfig.com.json
  entries/s/stash.com.json
  entries/s/sunsuper.com.au.json
  entries/t/tiaa-cref.org.json
  entries/u/unisuper.com.au.json
  entries/w/wealthfront.com.json
  entries/w/wealthsimple.com.json
  entries/w/weltsparen.de.json
  entries/y/youinvest.co.uk.json
Labels: update site, multiple sites

#6445 Add Spaceship
  entries/s/spaceship.com.au.json
  img/s/spaceship.com.au.svg
Labels: add site

#6453 Ignore exclusions for regions.json
  scripts/APIv2.rb
  scripts/APIv3.rb
Labels: international, ruby
