Repository 2factorauth/twofactorauth, pull requests merged in 2022-12, with the labels that each got.

#7099 Make dark scroll bar in dark theme for Chromium-based browsers
  _includes/scss/search.scss
  css/main.scss
Labels: Website enhancement

#7040 Readme: Fix command to build with Docker on Windows
  README.md
Labels: enhancement

#7035 Add Trumf
  entries/t/trumf.no.json
  img/t/trumf.no.svg
Labels: add site

#7103 Update VK
  entries/v/vk.com.json
Labels: update site

#7102 Add Miro
  entries/m/miro.com.json
  img/m/miro.com.svg
Labels: add site

#7107 Update Gaijin
  entries/g/gaijin.net.json
Labels: update site

#7041 Scroll to category when it is opened (fixes table outside of viewport)
  js/main.js
Labels: Website enhancement

#7110 Update Coursera
  entries/c/coursera.org.json
Labels: update site

#7111 Update Adafruit
  entries/a/adafruit.com.json
Labels: update site

#7113 Update Cinemark
  entries/c/cinemark.com.json
Labels: update site

#7112 Add ProduBanco
  entries/p/produbanco.com.ec.json
  img/p/produbanco.com.ec.svg
Labels: update site

#7115 Update Wikipedia
  entries/w/wikipedia.org.json
Labels: update site

#7116 Update Postman
  entries/p/postman.com.json
Labels: update site

#7117 Update Instagram
  entries/i/instagram.com.json
Labels: update site

#7119 Add Qiwi
  entries/q/qiwi.com.json
  img/q/qiwi.com.svg
Labels: add site

#7122 Add Cathay Pacific
  entries/c/cathaypacific.com.json
  img/c/cathaypacific.com.svg
Labels: add site

#7127 Add Seton Hall University
  entries/s/shu.edu.json
  img/s/shu.edu.svg
Labels: add site

#7128 Add Cal Poly SLO
  entries/c/calpoly.edu.json
  img/c/calpoly.edu.svg
Labels: add site

#7130 Update Synology
  entries/s/synology.com.json
Labels: update site

#7129 Add UC Berkeley
  entries/b/berkeley.edu.json
  img/b/berkeley.edu.png
Labels: add site

#7134 Update Pushover
  entries/p/pushover.net.json
Labels: update site

#7133 Update Nozbe
  entries/n/nozbe.com.json
Labels: update site

#7132 Update Nordlayer
  entries/n/nordlayer.com.json
Labels: update site

#7131 Update Mailfence
  entries/m/mailfence.com.json
Labels: update site

#7136 Update Ti.to
  entries/t/ti.to.json
Labels: update site

#7137 Update Uniregistry
  entries/u/uniregistry.com.json
Labels: update site

#7138 Update Unleashedsoftware
  entries/u/unleashedsoftware.com.json
Labels: update site

#7147 Update Xfinity
  entries/x/xfinity.com.json
Labels: update site

#7139 Update Uphold
  entries/u/uphold.com.json
Labels: update site

#7140 Update Upcloud
  entries/u/upcloud.com.json
Labels: update site

#7141 Update Nulab
  entries/n/nulab.com.json
Labels: update site

#7142 Update Termius
  entries/t/termius.com.json
Labels: update site

#7143 Update Sumologic
  entries/s/sumologic.com.json
Labels: update site

#7144 Update Rightcapital
  entries/r/rightcapital.com.json
Labels: update site

#7123 Add Internet Archive
  entries/a/archive.org.json
  img/a/archive.org.svg
Labels: add site

#7125 Add Allegiant Air
  entries/a/allegiantair.com.json
  img/a/allegiantair.com.svg
Labels: add site

#7126 Add FanFiction.Net
  entries/f/fanfiction.net.json
  img/f/fanfiction.net.png
Labels: add site

#7121 Add Meta
  entries/m/meta.com.json
  img/m/meta.com.svg
Labels: add site

#7148 Add Knowt
  entries/k/knowt.io.json
  img/k/knowt.io.svg
Labels: add site

#7152 Update README badge and installation instructions
  README.md
Labels: enhancement

#7151 Add GIPHY
  entries/g/giphy.com.json
  img/g/giphy.com.svg
Labels: add site

#7149 Add FlightAware
  entries/f/flightaware.com.json
  img/f/flightaware.com.svg
Labels: add site

#7155 Update Barmenia
  entries/b/barmenia.de.json
Labels: update site

#7156 Add TopCashback
  entries/t/topcashback.co.uk.json
  img/t/topcashback.co.uk.svg
Labels: add site

#7159 Fix git diff in Algolia.rb
  scripts/Algolia.rb
Labels: bug

#7158 Add logwien
  entries/l/log.wien.json
  img/l/log.wien.svg
Labels: add site

#7150 Add Forem
  entries/f/forem.com.json
  img/f/forem.com.png
Labels: add site

#7167 Add Supabase
  entries/s/supabase.com.json
  img/s/supabase.com.svg
Labels: add site

#7168 Add LibraryThing
  entries/l/librarything.com.json
  img/l/librarything.com.svg
Labels: add site

#7169 Update MyChart
  entries/m/mychart.com.json
Labels: update site

#7160 Update API references
  API.md
  README.md
Labels: enhancement

#7124 Add Wattpad
  entries/w/wattpad.com.json
  img/w/wattpad.com.svg
Labels: add site

#7171 Add Brigham Young University
  entries/b/byu.edu.json
  img/b/byu.edu.svg
Labels: add site

#7173 Add TeslaFi
  entries/t/teslafi.com.json
  img/t/teslafi.com.png
Labels: add site

#7172 Add NetEase Mail
  entries/m/mail.163.com.json
  img/m/mail.163.com.svg
Labels: add site

#7174 Add Shinsei Bank
  entries/s/shinseibank.com.json
  img/s/shinseibank.com.svg
Labels: add site

#7176 Add AutoTask
  entries/a/autotask.net.json
  img/a/autotask.net.svg
Labels: add site

#7181 Update The Ohio State University
  entries/o/osu.edu.json
Labels: update site

#7175 Replace Air France with Flying Blue
  entries/a/airfrance.com.json
  entries/f/flyingblue.com.json
  img/a/airfrance.com.svg
  img/f/flyingblue.com.svg
Labels: add site, remove site

#7197 Fix/remove outdated information
  CONTRIBUTING.md
Labels: enhancement

#7188 Add myfritz.net
  entries/m/myfritz.net.json
  entries/s/sso.myfritz.net.json
  img/m/myfritz.net.svg
  img/s/sso.myfritz.net.svg
Labels: update site

#7199 Add Stiftung Warentest
  entries/t/test.de.json
  img/t/test.de.svg
Labels: add site

#7190 Update TD Bank
  entries/t/td.com.json
Labels: update site
