Repository 2factorauth/twofactorauth, pull requests merged in 2022-05, with the labels that each got.

#6687 Add Wyre
  entries/s/sendwyre.com.json
  img/s/sendwyre.com.svg
Labels: add site

#6691 Update Lowes
  entries/l/lowes.com.json
Labels: update site

#6693 Update College Board
  entries/c/collegeboard.org.json
Labels: update site

#6697 Wrike: Clarify restrictions
  entries/w/wrike.com.json
Labels: update site

#6626 Add LIHKG
  entries/l/lihkg.com.json
  img/l/lihkg.com.svg
Labels: add site

#6698 Update dependencies
  _layouts/default.html
  css/about.html.scss
Labels: enhancement

#6694 Update lhv.ee
  entries/l/lhv.ee.json
Labels: update site

#6632 Update DEGIRO
  entries/d/degiro.nl.json
Labels: update site

#6647 Add additional domains
  entries/b/bankofamerica.com.json
  entries/c/citi.com.json
  entries/d/discover.com.json
  entries/m/merrilledge.com.json
  entries/p/playstation.com.json
  entries/t/tdameritrade.com.json
  entries/w/wellsfargo.com.json
Labels: update site, multiple sites

#6661 Add IO Interactive
  entries/i/ioi.dk.json
  img/i/ioi.dk.svg
Labels: add site

#6705 Update GitLab
  img/g/gitlab.com.svg
Labels: update site

#6721 Update npm
  entries/n/npmjs.com.json
Labels: update site

#6695 Update PayPal
  entries/p/paypal.com.json
Labels: update site

#6704 Add DraftKings
  entries/d/draftkings.com.json
  img/d/draftkings.com.svg
Labels: add site

#6686 Update logos
  img/c/codeberg.org.svg
  img/c/coinfield.com.svg
  img/d/docker.com.svg
  img/i/invisionapp.com.svg
  img/l/localizejs.com.svg
Labels: enhancement

#6720 Add arin.net
  entries/a/arin.net.json
  img/a/arin.net.svg
Labels: add site

#6718 add practice better
  entries/p/practicebetter.io.json
  img/p/practicebetter.io.svg
Labels: add site

#6715 Add AnonAddy
  entries/a/anonaddy.com.json
  img/a/anonaddy.com.svg
Labels: add site

#6729 Add ShipStation
  entries/s/shipstation.com.json
  img/s/shipstation.com.svg
Labels: add site

#6696 Add NerdWallet
  entries/n/nerdwallet.com.json
  img/n/nerdwallet.com.svg
Labels: add site

#6717 Add CloudAMQP
  entries/c/cloudamqp.com.json
  img/c/cloudamqp.com.svg
Labels: add site

#6728 Add Deliverr
  entries/d/deliverr.com.json
  img/d/deliverr.com.svg
Labels: add site

#6733 Add FragDenStaat
  entries/f/fragdenstaat.de.json
  img/f/fragdenstaat.de.svg
Labels: add site

#6713 Fix flag-icons CSS classes
  _includes/html/navbar.html
  css/navbar.scss
Labels: bug

#6631 Update SCHUFA
  entries/m/meineschufa.de.json
Labels: update site

#6646 Add Vagaro
  entries/v/vagaro.com.json
  img/v/vagaro.com.svg
Labels: add site

#6669 Accessibility improvements
  _layouts/default.html
  about.html
  css/main.scss
  index.html
  scripts/regions.rb
Labels: enhancement

#6689 more additonal domains
  entries/a/autodesk.com.json
  entries/d/discord.com.json
  entries/d/docusign.com.json
  entries/d/dropbox.com.json
  entries/f/facebook.com.json
  entries/m/mtb.com.json
  entries/p/paypal.com.json
  entries/s/schwab.com.json
  entries/t/tesla.com.json
Labels: update site, multiple sites

#6716 Add simplelogin
  entries/s/simplelogin.io.json
  img/s/simplelogin.io.svg
Labels: add site

#6723 Add University of Otago
  entries/o/otago.ac.nz.json
  img/o/otago.ac.nz.svg
Labels: add site

#6742 Add Bokio Sweden
  entries/b/bokio.se.json
  img/b/bokio.se.svg
Labels: add site

#6743 Add GNU version of tar
  Dockerfile
Labels: bug

#6727 Update Vimeo
  entries/v/vimeo.com.json
Labels: update site

#6594 Add Mora
  entries/m/mora.jp.json
  img/m/mora.jp.svg
Labels: add site

#6517 Add Pixiv
  entries/p/pixiv.net.json
  img/p/pixiv.net.svg
Labels: add site

#6458 Add Trimble
  entries/t/trimble.com.json
  img/t/trimble.com.svg
Labels: add site

#6272 Update Udemy
  entries/u/udemy.com.json
Labels: update site

#6561 Update Versio image
  entries/v/versio.nl.json
  img/v/versio.nl.png
  img/v/versio.nl.svg
Labels: update site

#6543 Add Profil zaufany
  entries/p/pz.gov.pl.json
  img/p/pz.gov.pl.svg
Labels: add site

#6747 Update GLS
  entries/g/gls.de.json
Labels: update site

#6724 Add Tableau
  entries/t/tableau.com.json
  img/t/tableau.com.svg
Labels: add site

#6749 Add VicRoads
  entries/v/vicroads.vic.gov.au.json
  img/v/vicroads.vic.gov.au.svg
Labels: add site

#6752 Update Geico
  entries/g/geico.com.json
Labels: update site

#6668 Fix some accessibility issues
  _includes/html/category-button.html
  _includes/html/desktop-table.html
  _includes/html/navbar.html
  _includes/scss/desktop-table.scss
  _includes/scss/mobile-table.scss
  js/main.js
Labels: enhancement

#6607 Fix bug closing categories directly after opening
  _includes/html/category-button.html
  js/main.js
Labels: bug

#6753 Add more regions
  _data/regions.yml
  _includes/html/navbar.html
  css/navbar.scss
Labels: enhancement

#6757 Add Aware Super
  entries/a/aware.com.au.json
  img/a/aware.com.au.svg
Labels: add site

#6750 Mountain America Credit Union now supports TOTP
  entries/m/macu.com.json
Labels: update site
