Repository 2factorauth/twofactorauth, pull requests merged in 2022-02, with the labels that each got.

#6456 Update UK2
  entries/u/uk2.net.json
Labels: update site

#6413 Update Clipper
  entries/c/clippercard.com.json
  img/c/clippercard.com.svg
Labels: update site

#6457 Add Independer
  entries/i/independer.nl.json
  img/i/independer.nl.svg
Labels: add site

#6454 Add Binge
  entries/b/binge.com.au.json
  img/b/binge.com.au.svg
Labels: add site

#6441 Update LastPass
  entries/l/lastpass.com.json
Labels: update site

#6162 Add gosuslugi.ru
  entries/g/gosuslugi.ru.json
  img/g/gosuslugi.ru.svg
Labels: add site

#6459 Add Linkt
  entries/l/linkt.com.au.json
  img/l/linkt.com.au.svg
Labels: add site

#6442 Update GitHub
  entries/g/github.com.json
Labels: update site

#6464 Remove Coinfloor
  entries/c/coinfloor.co.uk.json
  img/c/coinfloor.co.uk.png
Labels: remove site

#6466 Update LNER
  entries/l/lner.co.uk.json
  img/l/lner.co.uk.png
  img/l/lner.co.uk.svg
Labels: update site

#6465 Update No-IP logo
  entries/n/noip.com.json
  img/n/noip.com.png
  img/n/noip.com.svg
Labels: update site

#6467 Update Forum Exclusion
  EXCLUSION.md
Labels: enhancement

#6471 Update Volksbanken Raiffeisenbanken
  entries/v/vr.de.json
Labels: update site

#6469 Update ING-DiBa Deutschland
  entries/i/ing.de.json
Labels: update site

#6468 Add WPScan
  entries/w/wpscan.com.json
  img/w/wpscan.com.svg
Labels: add site

#6477 Update Kaspersky
  entries/k/kaspersky.com.json
Labels: update site

#6478 Remove Pushcoin
  entries/p/pushcoin.com.json
  img/p/pushcoin.com.png
Labels: remove site

#6480 Update Microsoft Products
  entries/a/azure.microsoft.com.json
  entries/o/office.microsoft.com.json
  entries/s/skype.com.json
  entries/t/todo.microsoft.com.json
  entries/v/visualstudio.microsoft.com.json
  entries/x/xbox.com.json
Labels: update site, multiple sites

#6476 Update Webroot
  entries/w/webroot.com.json
Labels: update site

#6440 Add Tweakers
  entries/t/tweakers.net.json
  img/t/tweakers.net.svg
Labels: add site

#6262 Add more region tags
  entries/a/alaskaair.com.json
  entries/a/auspost.com.au.json
  entries/b/bullionexchanges.com.json
  entries/c/conrad.com.json
  entries/c/conrad.de.json
  entries/c/copaair.com.json
  entries/d/dhl.de.json
  entries/d/dpd.de.json
  entries/f/flyfrontier.com.json
  entries/h/hawaiianairlines.com.json
  entries/h/hypop.com.au.json
  entries/l/legalmail.it.json
  entries/m/mail.ru.json
  entries/m/mail.tim.it.json
  entries/m/myhermes.de.json
  entries/n/namespro.ca.json
  entries/r/redbus.in.json
  entries/r/registro.br.json
  entries/s/seznam.cz.json
  entries/s/sierra.com.json
  entries/s/smartrip.wmata.com.json
  entries/s/southwest.com.json
  entries/t/t-online.de.json
  entries/t/thalia.de.json
  entries/u/uk2.net.json
  entries/u/ukpostbox.com.json
  entries/u/united-domains.de.json
  entries/u/uniteddomains.com.json
  entries/w/web.de.json
  img/c/conrad.com.svg
  img/c/conrad.de.svg
  tests/facebook.rb
Labels: update site, multiple sites

#6483 Update Redis
  entries/r/redis.com.json
  img/r/redis.com.svg
Labels: update site

#6479 Add NS&I
  entries/n/nsandi.com.json
  img/n/nsandi.com.svg
Labels: add site

#6409 Add NextDNS.io
  entries/n/nextdns.io.json
  img/n/nextdns.io.png
Labels: add site

#6472 Add Ticketmaster
  entries/t/ticketmaster.com.json
  img/t/ticketmaster.com.svg
Labels: add site

#6473 Add Ticketek
  entries/t/ticketek.com.au.json
  img/t/ticketek.com.au.svg
Labels: add site

#6481 Update Fathom Analytics
  entries/u/usefathom.com.json
Labels: update site

#6474 Add SeatGeek
  entries/s/seatgeek.com.json
  img/s/seatgeek.com.svg
Labels: add site

#6492 Generate regions in parallel
  Gemfile
  scripts/regions.rb
Labels: enhancement

#6488 Add category "Tickets and Events"
  _data/categories.json
  entries/e/eventbrite.com.json
  entries/e/eventim.de.json
  entries/s/seatgeek.com.json
  entries/t/ticketek.com.au.json
  entries/t/ticketmaster.com.json
Labels: add category

#6484 New theme proposal
  _config.yml
  _includes/html/category-button.html
  _includes/html/mobile-table.html
  _includes/html/navbar.html
  _includes/scss/categories.scss
  _includes/scss/desktop-table.scss
  _includes/scss/mobile-table.scss
  _layouts/default.html
  css/main.scss
  css/navbar.scss
  index.html
  js/main.js
  js/search.js
Labels: enhancement

#6231 Add Rocket League Garage
  entries/r/rocket-league.com.json
  img/r/rocket-league.com.png
Labels: add site

#6500 Remove HelloWallet
  entries/h/hellowallet.com.json
  img/h/hellowallet.com.png
Labels: remove site

#6450 Update Image Validation
  tests/validate-images.rb
Labels: enhancement

#6200 Update win2day
  entries/w/win2day.at.json
Labels: update site

#6315 Add Riot Games
  entries/l/leagueoflegends.com.json
  entries/r/riotgames.com.json
  img/l/leagueoflegends.com.svg
  img/r/riotgames.com.svg
Labels: add site

#6448 Add Chegg
  entries/c/chegg.com.json
  img/c/chegg.com.svg
Labels: add site

#6503 Add Hostplus
  entries/h/hostplus.com.au.json
  img/h/hostplus.com.au.svg
Labels: add site

#6414 Add DCS
  entries/d/digitalcombatsimulator.com.json
  img/d/digitalcombatsimulator.com.svg
Labels: add site

#6508 Update Nando's UK
  entries/n/nandos.co.uk.json
Labels: update site

#6506 Update HashiCorp Cloud Platform
  entries/c/cloud.hashicorp.com.json
Labels: update site

#6505 Update Patelco Credit Union
  entries/p/patelco.org.json
Labels: update site

#6496 Add Caffeine
  entries/c/caffeine.tv.json
  img/c/caffeine.tv.svg
Labels: add site

#6446 Similarweb rank check
  .circleci/config.yml
  .github/workflows/repository.yml
  Gemfile
  tests/similarweb.rb
Labels: enhancement

#6447 Add ADT Pulse
  entries/a/adt.com.json
  img/a/adt.com.svg
Labels: add site

#6490 Add HP
  entries/h/hp.com.json
  img/h/hp.com.svg
Labels: add site

#6519 Add Sony Bank
  entries/m/moneykit.net.json
  img/m/moneykit.net.svg
Labels: add site

#6523 Excluded Regions: Skrill
  entries/s/skrill.com.json
Labels: update site

#6524 Excluded Regions: Neteller
  entries/n/neteller.com.json
Labels: update site

#6509 Add SBI Sumishin Net Bank
  entries/n/netbk.co.jp.json
  img/n/netbk.co.jp.svg
Labels: add site

#6530 Add Outbrain
  entries/o/outbrain.com.json
  img/o/outbrain.com.svg
Labels: add site

#6535 Update Windscribe
  entries/w/windscribe.com.json
Labels: update site

#6536 Update Zip
  entries/z/zip.co.json
Labels: update site

#6541 Update itslearning
  entries/i/itslearning.com.json
Labels: update site

#6532 Add MUFG Bank
  entries/b/bk.mufg.jp.json
  img/b/bk.mufg.jp.svg
Labels: add site

#6537 Update Sailthru
  entries/s/sailthru.com.json
Labels: update site

#6522 Remove embedded raster images
  img/a/agenziaentrate.gov.it.svg
  img/a/airfrance.com.svg
  img/f/fi.google.com.svg
Labels: update site, multiple sites

#6521 Add Buy Me a Coffee
  entries/b/buymeacoffee.com.json
  img/b/buymeacoffee.com.svg
Labels: add site

#6501 Add Remitly
  entries/r/remitly.com.json
  img/r/remitly.com.svg
Labels: add site

#6540 Update Hi-Rez Studios
  entries/h/hirezstudios.com.json
  img/h/hirezstudios.com.png
  img/h/hirezstudios.com.svg
Labels: update site

#6534 Replace inline styling
  _includes/html/category-button.html
  _includes/html/desktop-table.html
  _includes/html/mobile-table.html
  _includes/html/navbar.html
  _layouts/default.html
  about.html
  index.html
Labels: enhancement

#6491 Add York University
  entries/y/yorku.ca.json
  img/y/yorku.ca.svg
Labels: add site

#6482 Update MongoDB products
  entries/c/cloud.mongodb.com.json
  entries/m/mongodb.com.json
  img/m/mongodb.com.svg
Labels: update site, multiple sites

#6546 Add Starbucks Japan
  entries/s/starbucks.co.jp.json
  entries/s/starbucks.com.json
Labels: add site

#6544 Add regions to Klarna
  entries/k/klarna.com.json
Labels: add site

#6497 Add whalefin
  entries/w/whalefin.com.json
  img/w/whalefin.com.svg
Labels: add site

#6494 Add 15Five
  entries/1/15five.com.json
  img/1/15five.com.svg
Labels: add site

#6557 Add NAGA
  entries/n/naga.com.json
  img/n/naga.com.svg
Labels: add site

#6558 Remove unused files
  .github/PULL_REQUEST_TEMPLATE/01-add-site.md
  .github/PULL_REQUEST_TEMPLATE/02-update-site.md
  .github/PULL_REQUEST_TEMPLATE/03-remove-site.md
  img/logo.png
Labels: enhancement

#6542 Update WP and o2
  entries/o/o2.pl.json
  entries/w/wp.pl.json
Labels: update site, multiple sites

#6462 Update Foursquare
  entries/f/foursquare.com.json
Labels: update site

#6551 Update Zoho
  entries/z/zoho.com.json
  img/z/zoho.com.svg
Labels: update site
