Repository 2factorauth/twofactorauth, pull requests merged in 2022-11, with the labels that each got.

#7027 Update CIBC
  entries/c/cibc.com.json
Labels: update site

#7030 letsdeel.com become deel.com
  entries/d/deel.com.json
  img/d/deel.com.svg
Labels: update site

#7028 Add N-able
  entries/n/n-able.com.json
  img/n/n-able.com.svg
Labels: add site

#7031 Add note for proton.me
  entries/p/proton.me.json
Labels: update site

#7036 Update Actionstep
  entries/a/actionstep.com.json
Labels: update site

#7044 Update Algolia
  img/a/algolia.com.svg
Labels: update site

#7043 Update Action Network
  img/a/actionnetwork.org.svg
Labels: update site

#7045 Add Cal Poly Pomona
  entries/c/cpp.edu.json
  img/c/cpp.edu.svg
Labels: add site

#7048 Update Ally
  entries/a/ally.com.json
Labels: update site

#7046 YoYo Games became GameMaker
  entries/g/gamemaker.io.json
  img/g/gamemaker.io.svg
  img/y/yoyogames.com.svg
Labels: update site

#7038 Update AWS
  entries/a/aws.amazon.com.json
Labels: update site

#7053 Update A2 Hosting
  entries/a/a2hosting.com.json
Labels: update site

#7052 Update 20i
  entries/2/20i.com.json
Labels: update site

#7051 Update Hetzner
  entries/h/hetzner.com.json
Labels: update site

#7037 Add HSBC CA
  entries/h/hsbc.ca.json
Labels: add site

#7058 Update Roblox
  entries/r/roblox.com.json
Labels: update site

#7054 Update Etrade
  img/e/etrade.com.svg
Labels: update site

#7042 Update Atera
  img/a/atera.com.svg
Labels: update site

#7034 Add Khan Academy
  entries/k/khanacademy.org.json
  img/k/khanacademy.org.svg
Labels: add site

#7057 Add Common App
  entries/c/commonapp.org.json
  img/c/commonapp.org.svg
Labels: add site

#7061 Add Masterclass
  entries/m/masterclass.com.json
  img/m/masterclass.com.svg
Labels: add site

#7062 Add SignUpGenius
  entries/s/signupgenius.com.json
  img/s/signupgenius.com.svg
Labels: add site

#7063 Add Gumroad
  entries/g/gumroad.com.json
  img/g/gumroad.com.svg
Labels: add site

#7065 Add Unsplash
  entries/u/unsplash.com.json
  img/u/unsplash.com.svg
Labels: add site

#7066 Add Beacons
  entries/b/beacons.ai.json
  img/b/beacons.ai.svg
Labels: add site

#7068 Add EVgo
  entries/e/evgo.com.json
  img/e/evgo.com.svg
Labels: add site

#7069 Add TripAdvisor
  entries/t/tripadvisor.com.json
  img/t/tripadvisor.com.svg
Labels: add site

#7082 Update Action Network's 2FA options
  entries/a/actionnetwork.org.json
Labels: update site

#7084 Add Vodafone NL
  entries/v/vodafone.nl.json
Labels: add site

#7083 Add Logitech
  entries/l/logitech.com.json
  img/l/logitech.com.svg
Labels: add site

#7078 Add ToneDen
  entries/t/toneden.io.json
  img/t/toneden.io.svg
Labels: add site

#7070 Add Vudu
  entries/v/vudu.com.json
  img/v/vudu.com.svg
Labels: add site

#7075 Update IONOS
  entries/i/ionos.com.json
  img/i/ionos.com.svg
Labels: update site

#7071 Add Peacock
  entries/p/peacocktv.com.json
  img/p/peacocktv.com.svg
Labels: add site

#7056 Added E.ON
  entries/e/eon.de.json
  img/e/eon.de.svg
Labels: add site

#7074 Add Hackster.io
  entries/h/hackster.io.json
  img/h/hackster.io.svg
Labels: add site

#7073 Add ChargePoint
  entries/c/chargepoint.com.json
  img/c/chargepoint.com.svg
Labels: add site

#7087 Update Service NSW
  entries/s/service.nsw.gov.au.json
Labels: update site

#7088 Update Aussie Broadband
  entries/a/aussiebroadband.com.au.json
Labels: update site

#6663 Update Chase 2FA options
  entries/c/chase.com.json
Labels: update site

#6935 Add Aozora Bank
  entries/a/aozorabank.co.jp.json
  img/a/aozorabank.co.jp.svg
Labels: add site

#6962 Add povo
  entries/p/povo.jp.json
  img/p/povo.jp.svg
Labels: add site

#6965 Add IIJmio
  entries/i/iijmio.jp.json
  img/i/iijmio.jp.png
Labels: add site

#7019 Add Marktplaats
  entries/m/marktplaats.nl.json
  img/m/marktplaats.nl.svg
Labels: add site, hacktoberfest-accepted

#7020 Add Banco Pichincha
  entries/p/pichincha.com.json
  img/p/pichincha.com.svg
Labels: add site, hacktoberfest-accepted

#7021 Add Banco Guayaquil
  entries/b/bancoguayaquil.com.json
  img/b/bancoguayaquil.com.svg
Labels: add site, hacktoberfest-accepted

#7092 Add Scorptec
  entries/s/scorptec.com.au.json
  img/s/scorptec.com.au.svg
Labels: add site

#6955 Add Typeform
  entries/t/typeform.com.json
  img/t/typeform.com.svg
Labels: add site

#7079 Add PlugShare
  entries/p/plugshare.com.json
  img/p/plugshare.com.svg
Labels: add site

#7022 Add Turo
  entries/t/turo.com.json
  img/t/turo.com.svg
Labels: add site

#7023 Add Banco Internacional
  entries/b/bancointernacional.com.ec.json
  img/b/bancointernacional.com.ec.svg
Labels: add site

#7024 Add Minna no Ginko
  entries/m/minna-no-ginko.com.json
  img/m/minna-no-ginko.com.svg
Labels: add site

#7086 Add Mastodon
  entries/j/joinmastodon.org.json
  img/j/joinmastodon.org.svg
Labels: add site

#7076 Update Centrify
  entries/c/centrify.com.json
  entries/d/delinea.com.json
  img/c/centrify.com.svg
  img/d/delinea.com.svg
Labels: update site

#7067 Add Teamsnap
  entries/t/teamsnap.com.json
  img/t/teamsnap.com.svg
Labels: add site

#7095 Add cohost
  entries/c/cohost.org.json
  img/c/cohost.org.svg
Labels: add site

#6976 Update SFFCU
  entries/s/sffirecu.org.json
Labels: update site

#7096 Add Payfit
  entries/p/payfit.com.json
  img/p/payfit.com.svg
Labels: add site

#7097 Add DMM
  entries/d/dmm.com.json
  img/d/dmm.com.svg
Labels: add site

#7077 Add Wolfram
  entries/w/wolfram.com.json
  img/w/wolfram.com.svg
Labels: add site

#7098 Update UniSuper
  entries/u/unisuper.com.au.json
Labels: update site
