Repository 2factorauth/twofactorauth, pull requests merged in 2022-06, with the labels that each got.

#6761 Update Standard Notes
  entries/s/standardnotes.com.json
  img/s/standardnotes.com.svg
Labels: update site

#6751 Add Warner Bros. Games
  entries/w/warnerbrosgames.com.json
  img/w/warnerbrosgames.com.svg
Labels: add site

#6731 Update doc links
  entries/a/angel.co.json
  entries/a/audiense.com.json
  entries/a/auth0.com.json
  entries/b/brex.com.json
  entries/b/bugcrowd.com.json
  entries/c/cashrewards.com.au.json
  entries/c/changelly.com.json
  entries/c/clio.com.json
  entries/c/cm.com.json
  entries/c/cobalt.io.json
  entries/c/coinberry.com.json
  entries/c/coingate.com.json
  entries/d/datarobot.com.json
  entries/d/dnsfilter.com.json
  entries/e/engineyard.com.json
  entries/f/formstack.com.json
  entries/h/hanseaticbank.de.json
  entries/h/hint.com.json
  entries/l/leaseweb.com.json
  entries/l/letsdeel.com.json
  entries/m/mint.intuit.com.json
  entries/o/okcupid.com.json
  entries/o/osf.io.json
  entries/p/purse.io.json
  entries/p/pusher.com.json
  entries/s/santander.de.json
  entries/s/sjsu.edu.json
  entries/s/stex.com.json
Labels: update site, multiple sites

#6758 Add Skinport
  entries/s/skinport.com.json
  img/s/skinport.com.svg
Labels: add site

#6759 Add Whimsical
  entries/w/whimsical.com.json
  img/w/whimsical.com.svg
Labels: add site

#6745 Update Proton entries
  entries/p/proton.me.json
  entries/p/protonmail.com.json
  entries/p/protonvpn.com.json
  img/p/proton.me.svg
  img/p/protonmail.com.svg
  img/p/protonvpn.com.svg
Labels: update site, multiple sites

#6766 Add Coles
  entries/c/coles.com.au.json
  img/c/coles.com.au.svg
Labels: add site

#6769 Add Volkswagen Financial Services
  entries/v/vwfs.de.json
  img/v/vwfs.de.png
Labels: add site

#6776 Add Aussie Broadband
  entries/a/aussiebroadband.com.au.json
  img/a/aussiebroadband.com.au.svg
Labels: add site

#6770 Add & Update Vodafone's
  entries/v/vodafone.co.nz.json
  entries/v/vodafone.co.uk.json
  entries/v/vodafone.com.au.json
  entries/v/vodafone.de.json
  entries/v/vodafone.ie.json
  entries/v/vodafone.it.json
Labels: add site

#6771 Add AGL Energy
  entries/a/agl.com.au.json
  img/a/agl.com.au.svg
Labels: add site

#6779 Update Adobe ID
  entries/a/adobe.com.json
Labels: update site

#6778 Add SteelSeries
  entries/s/steelseries.com.json
  img/s/steelseries.com.svg
Labels: add site

#6777 Re-add TOTP support for Paycor
  entries/p/paycor.com.json
Labels: update site

#6787 Add Bunnings Warehouse
  entries/b/bunnings.com.au.json
  img/b/bunnings.com.au.svg
Labels: add site

#6783 Update hide.me
  entries/h/hide.me.json
Labels: update site

#6785 Update Atlassian
  entries/i/id.atlassian.com.json
  entries/s/statuspage.io.json
  entries/t/trello.com.json
  img/t/trello.com.svg
Labels: update site

#6786 Update Linktree
  entries/l/linktr.ee.json
  img/l/linktr.ee.svg
Labels: update site

#6780 Add Winamax
  entries/w/winamax.fr.json
  img/w/winamax.fr.svg
Labels: add site

#6772 Update SE banking 2fa options
  entries/a/avanza.se.json
  entries/c/credit-suisse.com.json
  entries/d/danskebank.se.json
  entries/h/handelsbanken.se.json
  entries/i/icabanken.se.json
  entries/l/lansforsakringar.se.json
  entries/n/nordea.se.json
  entries/n/nordnet.se.json
  entries/s/seb.se.json
  entries/s/swedbank.se.json
Labels: update site

#6788 add Wefunder
  entries/w/wefunder.com.json
  img/w/wefunder.com.svg
Labels: add site

#6791 Add POEditor
  entries/p/poeditor.com.json
  img/p/poeditor.com.svg
Labels: add site

#6737 Update kraken
  entries/k/kraken.com.json
  img/k/kraken.com.svg
Labels: update site

#6792 Update Volkswagen Financial Services
  entries/v/vwfs.de.json
  img/v/vwfs.de.png
  img/v/vwfs.de.svg
Labels: update site

#6768 Add vse.cz (Vysoká škola ekonomická v Praze)
  entries/v/vse.cz.json
  img/v/vse.cz.svg
Labels: add site

#6794 Add Parallels
  entries/p/parallels.com.json
  img/p/parallels.com.svg
Labels: add site

#6796 Update indeed
  entries/i/indeed.com.json
Labels: update site

#6795 Update Oui.sncf
  entries/o/oui.sncf.json
  entries/s/sncf-connect.com.json
  img/o/oui.sncf.svg
  img/s/sncf-connect.com.svg
Labels: update site

#6801 Add BNPL sites
  entries/l/latitudepay.com.json
  entries/l/laybuy.com.json
  entries/s/shophumm.com.json
  img/l/latitudepay.com.svg
  img/l/laybuy.com.svg
  img/s/shophumm.com.svg
Labels: add site

#6803 Add Bowens
  entries/b/bowens.com.au.json
  img/b/bowens.com.au.svg
Labels: add site

#6798 Add Star One Credit Union
  entries/s/starone.org.json
  img/s/starone.org.svg
Labels: add site

#6806 Add LeetCode and CodeSignal
  entries/c/codesignal.com.json
  entries/l/leetcode.com.json
  img/c/codesignal.com.svg
  img/l/leetcode.com.svg
Labels: add site, multiple sites

#6808 add Masaryk University
  entries/m/muni.cz.json
  img/m/muni.cz.svg
Labels: add site

#6816 Update Binance
  entries/b/binance.com.json
Labels: update site

#6814 Update Epic Games
  entries/e/epicgames.com.json
Labels: update site

#6815 Add Filen
  entries/f/filen.io.json
  img/f/filen.io.svg
Labels: add site

#6821 Add Mailo
  entries/m/mailo.com.json
  img/m/mailo.com.svg
Labels: add site

#6823 Add OnlyDomains
  entries/o/onlydomains.com.json
  img/o/onlydomains.com.svg
Labels: add site

#6813 Add PSNProfiles
  entries/p/psnprofiles.com.json
  img/p/psnprofiles.com.svg
Labels: add site

#6825 Add MLP
  entries/m/mlp.de.json
  img/m/mlp.de.svg
Labels: add site

#6824 Replace PNGs by SVGs
  entries/c/cloudhq.net.json
  entries/c/commuterbenefits.com.json
  entries/t/threatx.com.json
  img/c/cloudhq.net.png
  img/c/cloudhq.net.svg
  img/c/commuterbenefits.com.png
  img/c/commuterbenefits.com.svg
  img/t/threatx.com.png
  img/t/threatx.com.svg
Labels: update site, multiple sites

#6822 Add Buyee
  entries/b/buyee.jp.json
  img/b/buyee.jp.svg
Labels: add site

#6831 Add Smarty
  entries/s/smarty.co.uk.json
  img/s/smarty.co.uk.png
Labels: add site

#6829 Update Optus
  entries/o/optus.com.au.json
Labels: update site

#6832 Update EE
  img/e/ee.co.uk.svg
Labels: update site
