Repository 2factorauth/twofactorauth, pull requests merged in 2023-11, with the labels that each got.

#7822 Update Chase
  entries/c/chase.com.json
Labels: update site

#7824 Update Supabase
  entries/s/supabase.com.json
Labels: update site

#7827 Update Meridian Credit Union
  entries/m/meridiancu.ca.json
Labels: update site

#7826 Update ngrok
  entries/n/ngrok.com.json
Labels: update site

#7834 Update Wefunder
  entries/w/wefunder.com.json
Labels: update site

#7836 add: portu.cz
  entries/p/portu.cz.json
  img/p/portu.cz.svg
Labels: add site

#7843 Update Passwordless Authentication documentation
  CONTRIBUTING.md
Labels: enhancement

#7841 Add SWITCH edu-ID
  entries/e/eduid.ch.json
  img/e/eduid.ch.svg
Labels: add site

#7837 Update o2switch
  entries/o/o2switch.fr.json
Labels: update site

#7847 Update eBay
  entries/e/ebay.com.json
Labels: update site

#7848 Add Monarch Money
  entries/m/monarchmoney.com.json
  img/m/monarchmoney.com.svg
Labels: add site
