Repository 2factorauth/twofactorauth, pull requests merged in 2023-02, with the labels that each got.

#7360 Update AirCanada
  entries/a/aircanada.com.json
Labels: update site

#7357 Update Actionstep
  entries/a/actionstep.com.json
Labels: update site

#7356 Update Acorns
  entries/a/acorns.com.json
Labels: update site

#7359 Update Adobe
  entries/a/adobe.com.json
Labels: update site

#7361 Remove Boxcryptor
  entries/b/boxcryptor.com.json
  img/b/boxcryptor.com.svg
Labels: remove site

#7337 Update Glorious
  entries/g/gloriousgaming.com.json
  entries/p/pcgamingrace.com.json
  img/g/gloriousgaming.com.svg
  img/p/pcgamingrace.com.svg
Labels: update site

#7366 Replace ING-DiBa Austria by bank99
  entries/b/bank99.at.json
  entries/i/ing.at.json
  img/b/bank99.at.svg
Labels: add site, remove site

#7353 Update 15five
  entries/1/15five.com.json
Labels: update site

#7351 Add custom-hardware/software entries
  entries/1/1822direkt.de.json
  entries/a/allianz.de.json
  entries/a/apobank.de.json
  entries/b/bbbank.de.json
  entries/b/bw-bank.de.json
  entries/c/comdirect.de.json
  entries/c/commerzbank.de.json
  entries/c/consorsbank.de.json
  entries/d/degussa-bank.de.json
  entries/d/deutsche-bank.de.json
  entries/d/deutsche-rentenversicherung.de.json
  entries/d/dkb.de.json
  entries/e/elster.de.json
  entries/h/hypovereinsbank.de.json
  entries/m/mail.de.json
  entries/n/norisbank.de.json
  entries/p/postbank.de.json
  entries/s/santander.de.json
  entries/s/serviceportal.hamburg.de.json
  entries/s/sparda.de.json
  entries/s/sparkasse.de.json
  entries/t/targobank.de.json
  entries/t/tk.de.json
  entries/u/uni-marburg.de.json
Labels: update site, multiple sites

#7367 Support relative redirects
  tests/validate-urls.rb
Labels: enhancement

#7368 Add file permission validation
  .circleci/config.yml
  .github/workflows/repository.yml
  img/u2f.svg
  tests/file-extensions.sh
  tests/validate-fs.sh
Labels: enhancement

#7373 Prevent infinite loop
  tests/validate-urls.rb
Labels: bug

#7376 Update Ko-fi
  entries/k/ko-fi.com.json
Labels: update site

#7371 Add Pachca
  entries/p/pachca.com.json
  img/p/pachca.com.svg
Labels: add site

#7372 Update doc links
  entries/a/altoira.com.json
  entries/b/biggerpockets.com.json
  entries/b/bittrex.com.json
  entries/c/central.sophos.com.json
  entries/c/clickup.com.json
  entries/c/coinpayments.net.json
  entries/c/crashplan.com.json
  entries/d/deputy.com.json
  entries/e/epik.com.json
  entries/f/fax.plus.json
  entries/g/growingio.com.json
  entries/h/hootsuite.com.json
  entries/i/id.me.json
  entries/i/investvoyager.com.json
  entries/l/liquid.com.json
  entries/n/ndax.io.json
  entries/n/nordlocker.com.json
  entries/o/okx.com.json
  entries/o/oneview.malwarebytes.com.json
  entries/p/paxful.com.json
  entries/p/powerreviews.com.json
  entries/r/rackspace.com.json
  entries/u/ukraine.com.ua.json
  entries/v/virginpulse.com.json
  entries/w/wasabi.com.json
  entries/w/windscribe.com.json
Labels: update site, multiple sites

#7379 Remove totp from Personal Capital
  entries/p/personalcapital.com.json
Labels: update site

#7378 Add link to frontend repo
  README.md
Labels: enhancement

#7370 Update Bitrix24
  entries/b/bitrix24.com.json
Labels: add site

#7374 Update 1Password
  entries/1/1password.com.json
Labels: update site

#7380 Add Line 6
  entries/l/line6.com.json
  img/l/line6.com.svg
Labels: add site

#7383 Add Sellix
  entries/s/sellix.io.json
  img/s/sellix.io.svg
Labels: add site

#7384 Add RestoreCord
  entries/r/restorecord.com.json
  img/r/restorecord.com.svg
Labels: add site

#7386 Add AllMyLinks
  entries/a/allmylinks.com.json
  img/a/allmylinks.com.svg
Labels: add site

#7385 Add Paddle
  entries/p/paddle.com.json
  img/p/paddle.com.svg
Labels: add site

#7390 Update Wise
  entries/w/wise.com.json
Labels: update site

#7387 Update Skrill
  entries/s/skrill.com.json
Labels: update site

#7389 Update Clemson University
  entries/c/clemson.edu.json
Labels: update site

#7393 Add Categories section in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#7388 Update Boston University
  entries/b/bu.edu.json
Labels: update site

#7363 `url` Deleted Based on `domain`: The `B`s
  entries/b/babbel.com.json
  entries/b/balena.io.json
  entries/b/bankhapoalim.co.il.json
  entries/b/banking.barclaysus.com.json
  entries/b/bankofamerica.com.json
  entries/b/bankofscotland.co.uk.json
  entries/b/barnesandnoble.com.json
  entries/b/bbva.com.ar.json
  entries/b/becu.org.json
  entries/b/bendigobank.com.au.json
  entries/b/betfair.com.json
  entries/b/bethpagefcu.com.json
  entries/b/betterment.com.json
  entries/b/betvictor.com.json
  entries/b/bglcorp.com.json
  entries/b/bigcommerce.com.json
  entries/b/biggerpockets.com.json
  entries/b/bigw.com.au.json
  entries/b/bill.com.json
  entries/b/binance.com.json
  entries/b/bitdefender.com.json
  entries/b/bitgo.com.json
  entries/b/bithumb.com.json
  entries/b/bitmex.com.json
  entries/b/bitpanda.com.json
  entries/b/bitrise.io.json
  entries/b/bladeandsoul.com.json
  entries/b/blau.de.json
  entries/b/bluehost.com.json
  entries/b/bna.com.ar.json
  entries/b/bochk.com.json
  entries/b/bohemia.net.json
  entries/b/booking.com.json
  entries/b/boots.com.json
  entries/b/boursedirect.fr.json
  entries/b/box.com.json
  entries/b/boxed.com.json
  entries/b/brack.ch.json
  entries/b/braintreepayments.com.json
  entries/b/breeze.pm.json
  entries/b/brex.com.json
  entries/b/britishairways.com.json
  entries/b/bsag.de.json
  entries/b/bt.com.json
  entries/b/btcbox.co.jp.json
  entries/b/btcmarkets.net.json
  entries/b/bu.edu.json
  entries/b/buda.com.json
  entries/b/bulb.co.uk.json
  entries/b/bullionexchanges.com.json
  entries/b/bullionstar.com.json
  entries/b/bybit.com.json
  entries/g/grupobancolombia.com.json
  entries/l/leumi.co.il.json
  entries/m/macro.com.ar.json
Labels: update site, multiple sites

#7377 Add custom-hardware/software entries
  entries/a/airbank.cz.json
  entries/a/arubacloud.com.json
  entries/b/bankofscotland.co.uk.json
  entries/b/bu.edu.json
  entries/c/coned.com.json
  entries/c/csas.cz.json
  entries/c/csob.cz.json
  entries/d/danskebank.dk.json
  entries/d/digid.nl.json
  entries/d/dnb.no.json
  entries/e/emich.edu.json
  entries/f/finecobank.com.json
  entries/l/lloydsbank.com.json
  entries/l/lmcu.org.json
Labels: update site, multiple sites

#7397 Add nic.ru
  entries/n/nic.ru.json
  img/n/nic.ru.svg
Labels: add site

#7398 Remove Fidor Bank
  entries/f/fidor.de.json
  img/f/fidor.de.svg
Labels: remove site

#7400 remove Udemy notes
  entries/u/udemy.com.json
Labels: update site

#7402 Add Aura
  entries/a/aura.com.json
  img/a/aura.com.svg
Labels: add site

#7399 Add Bonsai
  entries/h/hellobonsai.com.json
  img/h/hellobonsai.com.svg
Labels: add site

#7394 Send webhook to CF via workflows
  .github/workflows/repository.yml
Labels: enhancement

#7406 Add olg.ca
  entries/o/olg.ca.json
  img/o/olg.ca.svg
Labels: add site

#7407 Update Twitter
  entries/t/twitter.com.json
Labels: update site

#7404 Add TV Tropes
  entries/t/tvtropes.org.json
  img/t/tvtropes.org.png
Labels: add site

#6520 SVG Lint test
  tests/svg-lint.rb
Labels: enhancement

#7410 Update SVG lint test
  .github/workflows/repository.yml
  Gemfile
Labels: enhancement

#7412 Add AppFigures
  entries/a/appfigures.com.json
  img/a/appfigures.com.svg
Labels: add site

#7411 Add Scribd
  entries/s/scribd.com.json
  img/s/scribd.com.svg
Labels: add site

#7414 Update North Carolina State University
  entries/n/ncsu.edu.json
Labels: update site

#7415 Add BrowserStack
  entries/b/browserstack.com.json
  img/b/browserstack.com.svg
Labels: add site

#7428 Add TinyURL
  entries/t/tinyurl.com.json
  img/t/tinyurl.com.svg
Labels: add site

#7421 Update Pennsylvania State University
  entries/p/psu.edu.json
Labels: update site

#7422 Update Purdue University
  entries/p/purdue.edu.json
Labels: update site

#7425 Update University of Michigan
  entries/u/umich.edu.json
Labels: update site

#7423 Update Stanford University
  entries/s/stanford.edu.json
Labels: update site

#7426 Update Virginia Commonwealth University
  entries/v/vcu.edu.json
Labels: update site

#7427 Update Virginia Tech
  entries/v/vt.edu.json
Labels: update site

#7420 Add Kanopy
  entries/k/kanopy.com.json
  img/k/kanopy.com.svg
Labels: add site

#7419 Add OverDrive
  entries/o/overdrive.com.json
  img/o/overdrive.com.svg
Labels: add site

#7417 Add LottieFiles
  entries/l/lottiefiles.com.json
  img/l/lottiefiles.com.svg
Labels: add site

#7424 Update University of Idaho
  entries/u/uidaho.edu.json
Labels: update site

#7418 Add Serverless
  entries/s/serverless.com.json
  img/s/serverless.com.svg
Labels: add site

#7409 Update Microsoft 365
  entries/o/office.com.json
  img/o/office.com.svg
  img/o/office.microsoft.com.svg
Labels: update site

#7416 Add JustWatch
  entries/j/justwatch.com.json
  img/j/justwatch.com.svg
Labels: add site

#7432 Add CMG (Checkmate Gaming)
  entries/c/checkmategaming.com.json
  img/c/checkmategaming.com.png
Labels: add site

#7431 Update Microsoft 365
  img/o/office.com.svg
Labels: update site

#7437 Add Speedway
  entries/s/speedway.com.json
  img/s/speedway.com.svg
Labels: add site

#7440 Update Bank of America
  entries/b/bankofamerica.com.json
Labels: update site

#7441 Add Peet's Coffee
  entries/p/peets.com.json
  img/p/peets.com.svg
Labels: add site

#7442 Add Lucidchart
  entries/l/lucidchart.com.json
  img/l/lucidchart.com.svg
Labels: add site

#7443 Add KeyCDN
  entries/k/keycdn.com.json
  img/k/keycdn.com.svg
Labels: add site

#7444 Add Odysee
  entries/o/odysee.com.json
  img/o/odysee.com.svg
Labels: add site
