Repository 2factorauth/twofactorauth, pull requests merged in 2023-08, with the labels that each got.

#7694 Added various additional domains that Schibsted owns
  entries/s/schibsted.com.json
Labels: update site

#7697 Add Raisin
  entries/r/raisin.com.json
  img/r/raisin.com.svg
Labels: add site

#7700 Update Proton
  entries/p/proton.me.json
Labels: update site

#7701 Add Australian Super
  entries/a/australiansuper.com.json
  img/a/australiansuper.com.svg
Labels: add site

#7703 Add Rest Super
  entries/r/rest.com.au.json
  img/r/rest.com.au.svg
Labels: add site

#7696 Add Lemmy
  entries/j/join-lemmy.org.json
  img/j/join-lemmy.org.svg
Labels: add site

#7704 Update Tutanota
  entries/t/tutanota.com.json
Labels: update site

#7705 updated twitter logo
  img/t/twitter.com.svg
Labels: update site

#7706 Rename Twitter to X
  entries/t/twitter.com.json
Labels: update site

#7708 Add OMNY
  entries/o/omny.info.json
  img/o/omny.info.svg
Labels: add site

#7680 Add Axios
  entries/a/axios.com.json
  img/a/axios.com.svg
Labels: add site

#7681 Update IONOS
  entries/i/ionos.com.json
Labels: update site

#7713 Update Big W
  entries/b/bigw.com.au.json
Labels: update site

#7715 Temporarily remove Rubocop test
  .github/workflows/repository.yml
Labels: bug

#7710 Remove anonaddy
  entries/a/anonaddy.com.json
  img/a/anonaddy.com.svg
Labels: update site

#7719 Add gmx.at to gmx.net
  entries/g/gmx.net.json
Labels: update site

#7721 Update University of Colorado Boulder
  entries/c/colorado.edu.json
Labels: update site

#7722 Update Pixiv
  entries/p/pixiv.net.json
Labels: update site

#7723 Re-enable Rubocop
  .github/workflows/repository.yml
Labels: enhancement

#7728 Add SoCalGas
  entries/s/socalgas.com.json
  img/s/socalgas.com.svg
Labels: add site

#7729 Add Fidelity NetBenefits
  entries/n/nb.fidelity.com.json
Labels: add site

#7730 Update standardnotes.com.json
  entries/s/standardnotes.com.json
Labels: update site
