Repository 2factorauth/twofactorauth, pull requests merged in 2023-07, with the labels that each got.

#7674 Add ING Bank Slaski [PL]
  entries/i/ing.pl.json
Labels: add site

#7677 Update Pinterest
  entries/p/pinterest.com.json
Labels: update site

#7656 Add CNN
  entries/c/cnn.com.json
  img/c/cnn.com.svg
Labels: add site

#7683 Adding Citadel Credit Union
  entries/c/citadelbanking.com.json
  img/c/citadelbanking.com.svg
Labels: add site

#7679 Add Transifex
  entries/t/transifex.com.json
  img/t/transifex.com.svg
Labels: add site

#7690 Add note about the `.editorconfig`
  CONTRIBUTING.md
Labels: enhancement

#7684 Add Australian Universities
  entries/d/deakin.edu.au.json
  entries/l/latrobe.edu.au.json
  entries/m/monash.edu.json
  entries/s/swinburne.edu.au.json
  entries/s/sydney.edu.au.json
  entries/u/unimelb.edu.au.json
  entries/u/unsw.edu.au.json
  entries/u/uq.edu.au.json
  entries/u/uts.edu.au.json
  img/d/deakin.edu.au.svg
  img/l/latrobe.edu.au.svg
  img/m/monash.edu.png
  img/s/swinburne.edu.au.svg
  img/s/sydney.edu.au.svg
  img/u/unimelb.edu.au.png
  img/u/unsw.edu.au.png
  img/u/uq.edu.au.svg
  img/u/uts.edu.au.svg
Labels: add site, multiple sites

#7691 Add lexoffice
  entries/l/lexoffice.de.json
  img/l/lexoffice.de.svg
Labels: add site

#7689 Add NY.gov ID
  entries/m/my.ny.gov.json
  img/m/my.ny.gov.svg
Labels: add site
