Repository 2factorauth/twofactorauth, pull requests merged in 2023-04, with the labels that each got.

#7501 Update OnlyDomains
  entries/o/onlydomains.com.json
Labels: update site

#7500 Add WakaTime
  entries/w/wakatime.com.json
  img/w/wakatime.com.svg
Labels: add site

#7499 Add Life360
  entries/l/life360.com.json
  img/l/life360.com.svg
Labels: add site

#7502 Update CoinMarketCap
  entries/c/coinmarketcap.com.json
Labels: update site

#7503 Update MessageBird
  entries/m/messagebird.com.json
  img/m/messagebird.com.svg
Labels: update site

#7504 Update Developer sites
  entries/b/buddy.works.json
  entries/p/phrase.com.json
  entries/r/rumble.run.json
  img/r/rumble.run.svg
Labels: update site, multiple sites

#7506 Clarify no 2FA site documentation
  CONTRIBUTING.md
Labels: enhancement

#7511 Update Buffer
  entries/b/buffer.com.json
Labels: update site

#7509 Update Zendesk
  entries/z/zendesk.com.json
Labels: update site

#7510 Update Porkbun
  entries/p/porkbun.com.json
Labels: update site

#7514 Add Edabit
  entries/e/edabit.com.json
  img/e/edabit.com.png
Labels: add site

#7515 Add Pexels
  entries/p/pexels.com.json
  img/p/pexels.com.svg
Labels: add site

#7517 Add CryptoPanic
  entries/c/cryptopanic.com.json
  img/c/cryptopanic.com.svg
Labels: add site

#7518 Update Mastodon
  entries/j/joinmastodon.org.json
Labels: update site

#7519 Clarify email and contact form documentation
  CONTRIBUTING.md
Labels: enhancement

#7520 Update SVG test
  tests/svg-lint.rb
Labels: enhancement

#7521 Add SANS
  entries/s/sans.org.json
  img/s/sans.org.svg
Labels: add site

#7512 Add raindrop.io
  entries/r/raindrop.io.json
  img/r/raindrop.io.svg
Labels: add site

#7523 Update Social sites
  entries/v/vanillaforums.com.json
  img/a/ask.fm.svg
  img/v/vanillaforums.com.svg
  img/w/wattpad.com.svg
Labels: update site, multiple sites

#7505 Add forms
  entries/a/anz.com.au.json
  entries/b/bendigobank.com.au.json
  entries/d/deviantart.com.json
  entries/f/flaticon.com.json
  entries/g/greatsouthernbank.com.au.json
  entries/i/imgur.com.json
  entries/l/latitudepay.com.json
  entries/l/laybuy.com.json
  entries/n/nab.com.au.json
  entries/s/spotify.com.json
  entries/s/stan.com.au.json
  entries/w/westpac.com.au.json
Labels: update site, multiple sites

#7524 Update vcu.edu.json - Remove "Call" option
  entries/v/vcu.edu.json
Labels: update site

#7525 fix: Update Tokopedia URL
  entries/t/tokopedia.com.json
Labels: update site

#7528 Add Engadget (as non-2FA website)
  entries/e/engadget.com.json
  img/e/engadget.com.svg
Labels: add site

#7522 Add UC Merced
  entries/u/ucmerced.edu.json
  img/u/ucmerced.edu.svg
Labels: add site

#7529 Added mytax.illinois.gov
  entries/m/mytax.illinois.gov.json
  img/m/mytax.illinois.gov.png
Labels: add site

#7531 Remove Facebook U2F exception
  entries/f/facebook.com.json
Labels: update site

#7530 Add CQUniversity
  entries/c/cqu.edu.au.json
  img/c/cqu.edu.au.svg
Labels: add site

#7534 Add missing custom-* data (part 5)
  entries/1/1password.com.json
  entries/a/addiko.hr.json
  entries/a/atu.edu.json
  entries/b/bca.co.id.json
  entries/b/bitmex.com.json
  entries/b/bochk.com.json
  entries/b/bu.edu.json
  entries/c/caribbean.rbcroyalbank.com.json
  entries/c/commbank.com.au.json
  entries/d/dbs.com.sg.json
  entries/d/directnic.com.json
  entries/f/fiverr.com.json
  entries/g/gatech.edu.json
  entries/i/intesasanpaolo.com.json
  entries/k/kit.edu.json
  entries/l/launchpad.net.json
  entries/m/markmonitor.com.json
  entries/m/mcgill.ca.json
  entries/m/miamioh.edu.json
Labels: update site, multiple sites

#7535 Add CoSpaces
  entries/c/cospaces.io.json
  img/c/cospaces.io.svg
Labels: add site

#7539 Remove sites
  entries/c/commuterbenefits.com.json
  entries/f/forem.com.json
  entries/i/imgix.com.json
  img/c/commuterbenefits.com.svg
  img/f/forem.com.png
  img/i/imgix.com.svg
Labels: remove site, multiple sites

#7538 Update Elster
  entries/e/elster.de.json
Labels: update site

#7541 Add AllTrails
  entries/a/alltrails.com.json
  img/a/alltrails.com.svg
Labels: add site

#7542 Add Elfster
  entries/e/elfster.com.json
  img/e/elfster.com.png
Labels: add site

#7544 Add missing custom-* data (part 6)
  entries/m/mines.edu.json
  entries/m/mojedatovaschranka.cz.json
  entries/o/onlinesbi.com.json
  entries/o/otpbanka.hr.json
  entries/p/park.io.json
  entries/p/passpack.com.json
  entries/p/payeer.com.json
  entries/r/rabobank.nl.json
  entries/r/rb.cz.json
  entries/s/saaspass.com.json
  entries/s/sailpoint.com.json
  img/s/saaspass.com.svg
Labels: update site, multiple sites

#7546 Update Notion
  entries/n/notion.so.json
Labels: update site

#7492 Update SVGs
  img/1/1822direkt.de.svg
  img/2/23andme.com.svg
  img/a/adobe.com.svg
  img/a/adp.com.svg
  img/a/appfolio.com.svg
  img/b/barnesandnoble.com.svg
  img/b/bethesda.net.svg
  img/b/boots.com.svg
  img/b/breeze.pm.svg
  img/b/bugsnag.com.svg
  img/d/detectify.com.svg
  img/d/duolingo.com.svg
Labels: update site, multiple sites

#7547 Update README
  README.md
Labels: enhancement

#7489 Add Raspberry Pi
  entries/r/raspberrypi.com.json
  img/r/raspberrypi.com.svg
Labels: add site

#7549 Move workflow secrets
  .github/workflows/repository.yml
Labels: enhancement

#7551 Add Placeit
  entries/e/envato.com.json
Labels: add site

#7552 Update IRS
  entries/i/irs.gov.json
Labels: update site

#7553 Update VA
  entries/v/va.gov.json
Labels: update site

#7554 Add wealthfront to the banking category (Wealthfront Cash)
  entries/w/wealthfront.com.json
Labels: update site

#7555 Add Betterment to the banking category (Betterment Cash management)
  entries/b/betterment.com.json
Labels: update site

#7550 Add Turnitin
  entries/t/turnitin.com.json
  img/t/turnitin.com.svg
Labels: add site

#7557 Add Pinata
  entries/p/pinata.cloud.json
  img/p/pinata.cloud.svg
Labels: add site

#7559 Add 2K Games
  entries/2/2k.com.json
  img/2/2k.com.svg
Labels: add site
