Repository 2factorauth/twofactorauth, pull requests merged in 2023-03, with the labels that each got.

#7445 Update Mercado Bitcoin
  entries/m/mercadobitcoin.com.br.json
Labels: update site

#7448 Update PKO BP - Add custom software
  entries/p/pkobp.pl.json
Labels: update site

#7451 Update Spotify for Artists
  entries/a/artists.spotify.com.json
  img/a/artists.spotify.com.svg
Labels: update site

#7452 Update Spotify
  img/s/spotify.com.svg
Labels: update site

#7449 add artifacthub.io
  entries/a/artifacthub.io.json
  img/a/artifacthub.io.svg
Labels: add site

#7453 Add Oracle NetSuite
  entries/n/netsuite.com.json
  img/n/netsuite.com.svg
Labels: add site

#7456 Update WP Engine
  entries/w/wpengine.com.json
Labels: update site

#7455 Update You Need A Budget (YNAB)
  entries/y/youneedabudget.com.json
Labels: update site

#7450 Add Kick
  entries/k/kick.com.json
  img/k/kick.com.svg
Labels: add site

#7458 Update Fandom
  entries/f/fandom.com.json
Labels: update site

#7454 Update npm
  entries/n/npmjs.com.json
Labels: update site

#7459 Update ESL
  entries/p/play.eslgaming.com.json
  img/p/play.eslgaming.com.svg
Labels: update site

#7460 Add Grafana
  entries/g/grafana.com.json
  img/g/grafana.com.svg
Labels: add site

#7461 Add SurveyMonkey
  entries/s/surveymonkey.com.json
  img/s/surveymonkey.com.svg
Labels: add site

#7466 Update Telnyx
  img/t/telnyx.com.svg
Labels: update site

#7467 Update JumpCloud
  entries/j/jumpcloud.com.json
Labels: update site

#7470 add Ajax Systems
  entries/a/ajax.systems.json
  img/a/ajax.systems.svg
Labels: add site

#7472 Remove unused img/icons directory
  img/icons/apple-icon.svg
  img/icons/apple-icon_128x128.png
  img/icons/apple-icon_180x180.png
  img/icons/apple-icon_192x192.png
  img/icons/apple-icon_512x512.png
  img/icons/icon.svg
  img/icons/icon_180x180.png
  img/icons/icon_192x192.png
  img/icons/icon_310x310.png
  img/icons/icon_32x32.png
  img/icons/icon_512x512.png
  img/icons/maskable_icon.png
  img/icons/social-card.png
  img/icons/splashscreens/ipad_splash.png
  img/icons/splashscreens/ipadpro1_splash.png
  img/icons/splashscreens/ipadpro2_splash.png
  img/icons/splashscreens/ipadpro3_splash.png
  img/icons/splashscreens/iphone5_splash.png
  img/icons/splashscreens/iphone6_splash.png
  img/icons/splashscreens/iphoneplus_splash.png
  img/icons/splashscreens/iphonex_splash.png
  img/icons/splashscreens/iphonexr_splash.png
  img/icons/splashscreens/iphonexsmax_splash.png
Labels: enhancement

#7471 Add Coingecko
  entries/c/coingecko.com.json
  img/c/coingecko.com.svg
Labels: add site

#7473 Added Expo
  entries/e/expo.dev.json
  img/e/expo.dev.svg
Labels: add site

#7474 Add UFC Fight Pass
  entries/u/ufcfightpass.com.json
  img/u/ufcfightpass.com.svg
Labels: add site

#7475 Add cron-job.org
  entries/c/cron-job.org.json
  img/c/cron-job.org.png
Labels: add site

#7479 Add Alchemy
  entries/a/alchemy.com.json
  img/a/alchemy.com.svg
Labels: add site

#7480 Add Theta.tv
  entries/t/theta.tv.json
  img/t/theta.tv.png
Labels: add site

#7482 Add USPTO
  entries/u/uspto.gov.json
  img/u/uspto.gov.svg
Labels: add site

#7484 Add bitvavo
  entries/b/bitvavo.com.json
  img/b/bitvavo.com.svg
Labels: add site

#7483 Add Magnet.me
  entries/m/magnet.me.json
  img/m/magnet.me.svg
Labels: add site

#7487 Enhance SimilarWeb test
  tests/similarweb.rb
Labels: enhancement

#7488 Fix CircleCI Cache
  .circleci/config.yml
Labels: enhancement

#7490 Update Deliveroo
  entries/d/deliveroo.com.json
Labels: update site

#7491 Update Wise
  entries/w/wise.com.json
  img/w/wise.com.svg
Labels: update site

#7493 Remove sites
  entries/d/dnsmadeeasy.com.json
  entries/f/fabulous.com.json
  entries/g/globat.com.json
  entries/n/nearlyfreespeech.net.json
  entries/r/register4less.com.json
  entries/s/site5.com.json
  entries/v/veerotech.net.json
  img/d/dnsmadeeasy.com.svg
  img/f/fabulous.com.png
  img/g/globat.com.png
  img/n/nearlyfreespeech.net.png
  img/r/register4less.com.png
  img/s/site5.com.png
  img/v/veerotech.net.png
Labels: remove site, multiple sites

#7494 Add LIGA Bank
  entries/l/ligabank.de.json
  img/l/ligabank.de.svg
Labels: add site

#7495 Add Eastern Bank
  entries/e/easternbank.com.json
  img/e/easternbank.com.svg
Labels: add site

#7497 Fix CircleCI Bundler cache
  .circleci/config.yml
Labels: enhancement
