Repository 2factorauth/twofactorauth, pull requests merged in 2023-09, with the labels that each got.

#7734 Update Dynadot
  entries/d/dynadot.com.json
Labels: update site

#7733 Add Gradintelligence
  entries/g/gradintel.com.json
  img/g/gradintel.com.svg
Labels: add site

#7736 Update documentation urls
  entries/a/allianz.de.json
  entries/a/autotask.net.json
  entries/b/braze.com.json
  entries/b/brex.com.json
  entries/b/btcturk.com.json
  entries/c/cloud.hashicorp.com.json
  entries/d/databox.com.json
  entries/f/fauna.com.json
  entries/i/intigriti.com.json
  entries/l/leaseweb.com.json
  entries/n/naga.com.json
  entries/n/ndax.io.json
  entries/o/okta.com.json
  entries/p/payfit.com.json
  entries/p/platform360.io.json
  entries/p/probit.com.json
  entries/r/rackspace.com.json
  entries/s/server.nitrado.net.json
  entries/s/simplisafe.com.json
  entries/t/target.com.json
  entries/u/uber.com.json
  entries/v/veem.com.json
Labels: update site, multiple sites

#7735 Add oikotie.fi and tori.fi to Schibsted. Remove Tori as a separate entry.
  entries/s/schibsted.com.json
  entries/t/tori.fi.json
  img/t/tori.fi.svg
Labels: update site, remove site

#7742 Add Obsidian
  entries/o/obsidian.md.json
  img/o/obsidian.md.svg
Labels: add site

#7741 Add Hogeschool van Amsterdam
  entries/h/hva.nl.json
  img/h/hva.nl.svg
Labels: add site

#7743 Update CEX
  entries/c/cex.io.json
Labels: update site

#7744 Update Changelly
  entries/c/changelly.com.json
Labels: update site

#7746 Update Netlify
  img/n/netlify.com.svg
Labels: update site

#7748 Update Open Collective
  entries/o/opencollective.com.json
Labels: update site

#7747 Update OneSignal
  img/o/onesignal.com.svg
Labels: update site

#7749 Update Wellfound
  entries/w/wellfound.com.json
Labels: update site

#7751 Update Datto
  entries/d/datto.com.json
Labels: update site

#7750 Update Airtable
  entries/a/airtable.com.json
Labels: update site

#7753 Add Epayslips
  entries/e/epayslips.co.uk.json
  img/e/epayslips.co.uk.svg
Labels: add site

#7759 Add Bluesky
  entries/b/bsky.app.json
  img/b/bsky.app.png
Labels: add site

#7760 Update Dreamhost
  entries/d/dreamhost.com.json
Labels: update site

#7763 Update Shinsei Bank
  entries/s/sbishinseibank.co.jp.json
  img/s/sbishinseibank.co.jp.svg
Labels: update site

#7762 Add e-hon
  entries/e/e-hon.ne.jp.json
  img/e/e-hon.ne.jp.svg
Labels: add site

#7765 Update ConvertKit
  entries/c/convertkit.com.json
Labels: add site

#7766 Add Lnk.Bio
  entries/l/lnk.bio.json
  img/l/lnk.bio.svg
Labels: add site

#7767 Update Zoho logo
  img/z/zoho.com.svg
Labels: update site

#7768 Update Home Assistant
  img/h/home-assistant.io.svg
Labels: update site

#7769 Remove IberiaBank
  entries/i/iberiabank.com.json
  img/i/iberiabank.com.svg
Labels: remove site

#7770 Remove UBI Banca
  entries/u/ubibanca.com.json
  img/u/ubibanca.com.svg
Labels: remove site

#7772 Remove Flowdock
  entries/f/flowdock.com.json
  img/f/flowdock.com.svg
Labels: remove site

#7777 Update Deutsche Post
  entries/d/deutschepost.de.json
Labels: update site

#7776 Update Telekom
  entries/t/telekom.de.json
Labels: update site

#7779 Remove CoinField
  entries/c/coinfield.com.json
  img/c/coinfield.com.svg
Labels: remove site

#7780 Remove LocalBitcoins
  entries/l/localbitcoins.com.json
  img/l/localbitcoins.com.svg
Labels: remove site

#7781 Remove STEX
  entries/s/stex.com.json
  img/s/stex.com.svg
Labels: remove site

#7782 Remove Tauros
  entries/t/tauros.io.json
  img/t/tauros.io.svg
Labels: remove site

#7783 Remove Txbit
  entries/t/txbit.io.json
  img/t/txbit.io.svg
Labels: remove site

#7778 Rename BitcoinTrade to Ripio
  entries/b/bitcointrade.com.br.json
  entries/r/ripio.com.json
  img/b/bitcointrade.com.br.svg
  img/r/ripio.com.svg
Labels: add site, remove site

#7788 Add Aéza
  entries/a/aeza.net.json
  img/a/aeza.net.svg
Labels: add site
