Repository 2factorauth/twofactorauth, pull requests merged in 2023-12, with the labels that each got.

#7851 Add Fakturoid
  entries/f/fakturoid.cz.json
  img/f/fakturoid.cz.svg
Labels: add site

#7855 Add KTH
  entries/k/kth.se.json
  img/k/kth.se.png
Labels: add site

#7857 Update Tuta/Tutanota
  entries/t/tuta.com.json
  entries/t/tutanota.com.json
  img/t/tuta.com.svg
Labels: update site

#7859 Update SoundCloud
  entries/s/soundcloud.com.json
Labels: update site

#7860 Update T-Online
  entries/t/t-online.de.json
  img/t/t-online.de.svg
Labels: update site

#7861 Add GMO Aozora Net Bank
  entries/g/gmo-aozora.com.json
  img/g/gmo-aozora.com.svg
Labels: add site

#7862 Clean up SVG code
  img/b/bankhapoalim.co.il.svg
  img/b/bendigobank.com.au.svg
  img/b/bitdefender.com.svg
  img/c/caremark.com.svg
  img/c/cloudflare.com.svg
  img/c/csn.se.svg
  img/d/degiro.nl.svg
  img/d/donateblood.com.au.svg
  img/p/providentmetals.com.svg
  img/r/roblox.com.svg
  img/s/sncf-connect.com.svg
  img/t/techsmith.com.svg
  img/t/telstra.com.au.svg
  img/t/tfl.gov.uk.svg
  img/t/thelevelup.com.svg
  img/t/twitter.com.svg
  img/u/uptimerobot.com.svg
Labels: enhancement

#7864 Add McDonald's
  entries/m/mcdonalds.com.json
  img/m/mcdonalds.com.svg
Labels: add site

#7867 Add Postype
  entries/p/postype.com.json
  img/p/postype.com.svg
Labels: add site

#7872 Update Crowdin
  entries/c/crowdin.com.json
Labels: update site

#7873 Update Bluesky icon
  entries/b/bsky.app.json
  img/b/bsky.app.png
  img/b/bsky.app.svg
Labels: update site

#7874 Update muni.cz links
  entries/m/muni.cz.json
Labels: update site

#7868 Remove Republic Wireless
  entries/r/republicwireless.com.json
  img/r/republicwireless.com.svg
Labels: remove site

#7877 Update markdown alert format
  .github/workflows/stale.yml
Labels: enhancement
