Repository 2factorauth/twofactorauth, pull requests merged in 2023-01, with the labels that each got.

#7200 Fix Algoia.rb handling of file deletions
  scripts/Algolia.rb
Labels: bug

#7195 Add OpenAI
  entries/o/openai.com.json
  img/o/openai.com.svg
Labels: add site

#7182 Add Up
  entries/u/up.com.au.json
  img/u/up.com.au.svg
Labels: add site

#7201 Add entry for Aruba Instant On
  entries/a/arubainstanton.com.json
  img/a/arubainstanton.com.svg
Labels: add site

#7206 Add APNIC
  entries/a/apnic.net.json
  img/a/apnic.net.svg
Labels: add site

#7207 Add Schneider Electric
  entries/s/se.com.json
  img/s/se.com.svg
Labels: add site

#7194 Add CU Boulder
  entries/c/colorado.edu.json
  img/c/colorado.edu.svg
Labels: add site

#7211 Update Adobe
  entries/a/adobe.com.json
Labels: update site

#7177 Update Cal Poly Pomona
  entries/c/cpp.edu.json
Labels: update site

#7146 Add DATEV
  entries/d/datev.de.json
  img/d/datev.de.svg
Labels: add site

#7178 Update University of Wisconsin, Madison
  entries/w/wisc.edu.json
Labels: update site

#7180 Add Cooperativa JEP
  entries/j/jep.coop.json
  img/j/jep.coop.svg
Labels: add site

#7186 Add Icedrive
  entries/i/icedrive.net.json
  img/i/icedrive.net.png
Labels: add site

#7189 Update TD Ameritrade
  entries/t/tdameritrade.com.json
Labels: update site

#7191 Add Oregon State University
  entries/o/oregonstate.edu.json
  img/o/oregonstate.edu.svg
Labels: add site

#7193 Add Embry-Riddle Aeronautical University
  entries/e/erau.edu.json
  img/e/erau.edu.svg
Labels: add site

#7202 Add fuboTV
  entries/f/fubo.tv.json
  img/f/fubo.tv.svg
Labels: add site

#7179 Add Harvey Mudd College
  entries/h/hmc.edu.json
  img/h/hmc.edu.svg
Labels: add site

#7212 Add dotdigital
  entries/d/dotdigital.com.json
  img/d/dotdigital.com.svg
Labels: add site

#7187 Add Mullvad
  entries/m/mullvad.net.json
  img/m/mullvad.net.svg
Labels: add site

#7214 Add TicketSource
  entries/t/ticketsource.co.uk.json
  img/t/ticketsource.co.uk.svg
Labels: add site

#7216 Add Vivup
  entries/v/vivup.co.uk.json
  img/v/vivup.co.uk.png
Labels: add site

#7219 Update Depop
  entries/d/depop.com.json
Labels: update site

#7215 Add HUK24
  entries/h/huk24.de.json
  img/h/huk24.de.svg
Labels: add site

#7220 Update Healthcare.gov
  entries/h/healthcare.gov.json
Labels: update site

#7222 Update Wyze
  entries/w/wyze.com.json
Labels: update site

#7225 Remove Nuri
  entries/n/nuri.com.json
  img/n/nuri.com.svg
Labels: remove site

#7218 Add BookBeat
  entries/b/bookbeat.com.json
  img/b/bookbeat.com.svg
Labels: add site

#7223 Add swile.co
  entries/s/swile.co.json
  img/s/swile.co.svg
Labels: add site

#7118 Add WebMoney
  entries/w/webmoney.ru.json
  img/w/webmoney.ru.svg
Labels: add site

#7226 Add Asos
  entries/a/asos.com.json
  img/a/asos.com.svg
Labels: add site

#7230 Update Transport for London
  entries/t/tfl.gov.uk.json
Labels: update site

#7232 Test for invalid categories
  .github/workflows/repository.yml
  tests/validate-categories.rb
Labels: enhancement

#7233 Noridian Medicare Portal
  entries/n/noridianmedicareportal.com.json
  img/n/noridianmedicareportal.com.svg
Labels: add site

#7234 Add o2switch.fr
  entries/o/o2switch.fr.json
  img/o/o2switch.fr.svg
Labels: add site

#7239 Add HBO Max
  entries/h/hbomax.com.json
  img/h/hbomax.com.svg
Labels: add site

#7238 Add HSL (hsl.fi)
  entries/h/hsl.fi.json
  img/h/hsl.fi.svg
Labels: add site

#7240 Minimize ProduBanco icon
  img/p/produbanco.com.ec.svg
Labels: update site

#7241 Minify o2switch.fr.svg
  img/o/o2switch.fr.svg
Labels: enhancement

#7231 Update CIBC
  entries/c/cibc.com.json
Labels: update site

#7245 Add veem.com
  entries/v/veem.com.json
  img/v/veem.com.svg
Labels: add site

#7244 Add BeReal
  entries/b/bereal.com.json
  img/b/bereal.com.svg
Labels: add site

#7242 Add Finnkino
  entries/f/finnkino.fi.json
  img/f/finnkino.fi.svg
Labels: add site

#7246 Add Availity Essentials
  entries/a/availity.com.json
  img/a/availity.com.svg
Labels: add site

#7198 Update Uber
  entries/u/uber.com.json
Labels: update site

#7252 Update Bitwarden note
  entries/b/bitwarden.com.json
Labels: update site

#7247 Implement form element
  tests/schema.json
Labels: enhancement

#7254 Add `form` documentation
  CONTRIBUTING.md
Labels: enhancement

#7255 add stubhub
  entries/s/stubhub.com.json
  img/s/stubhub.com.svg
Labels: add site

#7263 Update outdated link republicwireless.com
  entries/r/republicwireless.com.json
Labels: update site

#7260 Add Mentimeter
  entries/m/mentimeter.com.json
  img/m/mentimeter.com.svg
Labels: add site

#7257 Add Tori
  entries/t/tori.fi.json
  img/t/tori.fi.svg
Labels: add site

#7264 Add Anthem
  entries/a/anthem.com.json
  img/a/anthem.com.svg
Labels: add site

#7253 Add Bourse Direct
  entries/b/boursedirect.fr.json
  img/b/boursedirect.fr.svg
Labels: add site

#7269 Update Wix
  entries/w/wix.com.json
Labels: update site

#7270 Update Tori
  entries/t/tori.fi.json
Labels: update site

#7258 Add Slideshare
  entries/s/slideshare.net.json
  img/s/slideshare.net.svg
Labels: add site

#7273 Update Namecheap
  entries/n/namecheap.com.json
Labels: update site

#7256 Add Spotify for Artists
  entries/a/artists.spotify.com.json
Labels: add site

#7272 Update issue templates
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.yml
  .github/ISSUE_TEMPLATE/02-add-site-without-2fa.yml
  .github/ISSUE_TEMPLATE/04-remove-existing-site.yml
  .gitignore
Labels: enhancement

#7277 Use threads instead of processes for parallel processing
  tests/language-codes.rb
  tests/validate-json.rb
Labels: bug

#7261 Add Lyyti
  entries/l/lyyti.com.json
  img/l/lyyti.com.svg
Labels: add site

#7274 Add WeTransfer
  entries/w/wetransfer.com.json
  img/w/wetransfer.com.svg
Labels: add site

#7276 Specify net-http instead of httpclient in header
  tests/language-codes.rb
  tests/region-codes.rb
Labels: enhancement

#7280 Add actual rank value to check output
  tests/similarweb.rb
Labels: enhancement

#7262 Replace svgo with nano in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#7275 Add myPrimobox
  entries/m/myprimobox.net.json
  img/m/myprimobox.net.svg
Labels: add site

#7282 Add BambooHR
  entries/b/bamboohr.com.json
  img/b/bamboohr.com.svg
Labels: add site

#7281 add pleo.io
  entries/p/pleo.io.json
  img/p/pleo.io.svg
Labels: add site

#7279 Add lippu.fi
  entries/l/lippu.fi.json
  img/l/lippu.fi.svg
Labels: add site

#7278 Add Yle
  entries/y/yle.fi.json
  img/y/yle.fi.svg
Labels: add site

#7283 Add Tiketti
  entries/t/tiketti.fi.json
  img/t/tiketti.fi.svg
Labels: add site

#7288 Add Killstar
  entries/k/killstar.com.json
  img/k/killstar.com.png
Labels: add site

#7285 Add Discovery Plus
  entries/d/discoveryplus.com.json
  img/d/discoveryplus.com.png
Labels: add site

#7286 Remove duplicate files
  Bots.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#7289 Add EMP
  entries/e/emp-online.com.json
  img/e/emp-online.com.svg
Labels: add site

#7287 Clean up validate-urls.rb
  Gemfile
  tests/validate-urls.rb
Labels: enhancement

#7295 Update Itslearning
  entries/i/itslearning.com.json
Labels: update site

#7293 Add Retroachievements
  entries/r/retroachievements.org.json
  img/r/retroachievements.org.svg
Labels: add site

#7294 Add Capcom ID
  entries/c/capcom.com.json
  img/c/capcom.com.svg
Labels: add site

#7296 Remove LocalCryptos
  entries/l/localcryptos.com.json
  img/l/localcryptos.com.svg
Labels: remove site

#7297 Remove netbank
  entries/n/netbank.de.json
  img/n/netbank.de.svg
Labels: remove site

#7300 Remove Jelastic
  entries/j/jelastic.com.json
  img/j/jelastic.com.svg
Labels: remove site

#7301 Remove Hangouts
  entries/h/hangouts.google.com.json
  img/h/hangouts.google.com.svg
Labels: remove site

#7299 Update icons
  entries/o/openshift.com.json
  img/c/canva.com.svg
  img/c/capsulecrm.com.svg
  img/c/carbonite.com.svg
  img/c/cdbaby.com.svg
  img/d/doodle.com.svg
  img/f/fxhome.com.svg
  img/k/koofr.eu.svg
  img/l/labanquepostale.fr.svg
  img/m/markmonitor.com.svg
  img/m/mural.co.svg
  img/n/nordea.svg
  img/o/openshift.com.svg
  img/o/optumbank.com.svg
  img/r/remind.com.svg
  img/r/replit.com.svg
  img/s/shinseibank.com.svg
  img/s/sketch.com.svg
  img/v/vapor.laravel.com.svg
Labels: update site, multiple sites

#7303 Remove Celsius
  entries/c/celsius.network.json
  img/c/celsius.network.svg
Labels: remove site

#7302 Rename SoGoSurvey to Sogolytics
  entries/s/sogolytics.com.json
  entries/s/sogosurvey.com.json
  img/s/sogolytics.com.svg
  img/s/sogosurvey.com.svg
Labels: update site

#7304 Remove FTX
  entries/f/ftx.com.json
  img/f/ftx.com.svg
Labels: remove site

#7307 Remove Paritex
  entries/p/paritex.com.json
  img/p/paritex.com.svg
Labels: remove site

#7306 Update icons
  img/b/batch.com.svg
  img/e/exmo.com.svg
  img/f/faucetpay.io.svg
  img/f/fogbugz.com.svg
  img/g/gate.io.svg
  img/l/latoken.com.svg
  img/l/launchpad.net.svg
  img/l/logicmonitor.com.svg
  img/l/luno.com.svg
  img/m/mercadobitcoin.com.br.svg
  img/n/newrelic.com.svg
  img/p/phemex.com.svg
  img/p/phrase.com.svg
  img/r/rapidapi.com.svg
  img/t/txbit.io.svg
Labels: update site, multiple sites

#7309 Remove Edmodo
  entries/e/edmodo.com.json
  img/e/edmodo.com.svg
Labels: remove site

#7308 Remove Algorithmia
  entries/a/algorithmia.com.json
  img/a/algorithmia.com.svg
Labels: remove site

#7305 Update Adobe ID
  entries/a/adobe.com.json
Labels: update site

#7311 Add hardware key support for Apple/iCloud
  entries/a/appleid.apple.com.json
  entries/i/icloud.com.json
Labels: update site

#7310 Add CodePen
  entries/c/codepen.io.json
  img/c/codepen.io.svg
Labels: add site

#7313 Merge SimpleTax into Wealthsimple
  entries/s/simpletax.ca.json
  entries/w/wealthsimple.com.json
  img/s/simpletax.ca.svg
Labels: update site, remove site

#7312 Update icons
  img/a/altoira.com.svg
  img/c/carta.com.svg
  img/c/cinemark.com.svg
  img/d/dnsmadeeasy.com.svg
  img/d/domaintools.com.svg
  img/e/emma.ca.svg
  img/e/enom.com.svg
  img/f/finnkino.fi.svg
  img/g/guideline.com.svg
  img/k/kerio.com.svg
  img/l/loopia.se.svg
  img/m/m1finance.com.svg
  img/o/opensrs.com.svg
  img/p/play.google.com.svg
  img/r/rightcapital.com.svg
  img/s/shoeboxed.com.svg
Labels: update site, multiple sites

#7315 Update Ubiquiti logo
  img/u/ui.com.svg
Labels: update site

#7316 Update iPage
  entries/i/ipage.com.json
Labels: update site

#7314 Update Schneider Electric category
  entries/s/se.com.json
Labels: update site

#7320 Remove Passfolio
  entries/p/passfolio.us.json
  img/p/passfolio.us.svg
Labels: remove site

#7321 Add American Century Investments
  entries/a/americancentury.com.json
  img/a/americancentury.com.svg
Labels: add site

#7318 Update icons
  entries/k/knownhost.com.json
  img/c/cdnsun.com.svg
  img/c/cronometer.com.svg
  img/g/gosuslugi.ru.svg
  img/h/hostek.com.svg
  img/k/knownhost.com.png
  img/k/knownhost.com.svg
  img/m/mittwald.de.svg
  img/m/myfitnesspal.com.svg
  img/n/nexcess.net.svg
  img/o/okta.com.svg
  img/r/runsignup.com.svg
  img/s/sailpoint.com.svg
  img/s/shadow.tech.svg
  img/v/virginpulse.com.svg
Labels: update site, multiple sites

#7317 Update Apple
  entries/a/appleid.apple.com.json
  entries/i/icloud.com.json
Labels: update site

#7322 Add Meltwater
  entries/m/meltwater.com.json
  img/m/meltwater.com.svg
Labels: add site

#7323 Add Onnibus
  entries/o/onnibus.com.json
  img/o/onnibus.com.svg
Labels: add site

#7324 Add Cmore
  entries/c/cmore.se.json
  img/c/cmore.se.svg
Labels: add site

#7326 Update icons
  img/b/bandcamp.com.svg
  img/b/bitwarden.com.svg
  img/b/bluehost.com.svg
  img/b/braintreepayments.com.svg
  img/c/clover.com.svg
  img/c/cordial.com.svg
  img/c/costco.com.svg
  img/d/degiro.nl.svg
  img/e/everlane.com.svg
  img/f/fathomhq.com.svg
  img/g/groupon.com.svg
  img/l/lastpass.com.svg
  img/m/mintos.com.svg
  img/o/onelogin.com.svg
  img/o/orcid.org.svg
  img/p/passpack.com.svg
  img/p/product.gree.net.svg
  img/r/runpanther.io.svg
  img/s/sendgrid.com.svg
  img/s/spectrum.com.svg
  img/t/truekey.com.svg
  img/w/westernunion.com.svg
  img/z/zalando.com.svg
Labels: update site

#7327 Replace PNG icons
  entries/i/iijmio.jp.json
  entries/n/nextdns.io.json
  entries/s/smarty.co.uk.json
  entries/s/smythstoys.com.json
  entries/v/vivup.co.uk.json
  img/i/iijmio.jp.png
  img/i/iijmio.jp.svg
  img/n/nextdns.io.png
  img/n/nextdns.io.svg
  img/s/smarty.co.uk.png
  img/s/smarty.co.uk.svg
  img/s/smythstoys.com.png
  img/s/smythstoys.com.svg
  img/v/vivup.co.uk.png
  img/v/vivup.co.uk.svg
Labels: update site, multiple sites

#7325 Add SDFCU
  entries/s/sdfcu.org.json
  img/s/sdfcu.org.svg
Labels: add site

#7328 Rename Falcon to Brandwatch
  entries/b/brandwatch.com.json
  entries/f/falcon.io.json
  img/b/brandwatch.com.svg
  img/f/falcon.io.svg
Labels: update site

#7319 Add Trustage
  entries/t/trustage.com.json
  img/t/trustage.com.svg
Labels: add site

#7330 Rename AngelList to Wellfound
  entries/w/wellfound.com.json
  img/a/angel.co.svg
  img/w/wellfound.com.svg
Labels: update site

#7331 Remove Automate.io
  entries/a/automate.io.json
  img/a/automate.io.svg
Labels: remove site

#7332 Merge Memsource into Phrase
  entries/m/memsource.com.json
  entries/p/phrase.com.json
  img/m/memsource.com.svg
Labels: update site, remove site

#7329 Update icons
  entries/h/hellosign.com.json
  entries/m/marketo.com.json
  entries/n/nest.com.json
  img/d/demio.com.svg
  img/e/everlaw.com.svg
  img/h/hellosign.com.svg
  img/h/hootsuite.com.svg
  img/k/klaviyo.com.svg
  img/m/marketo.com.svg
  img/m/maropost.com.svg
  img/n/nest.com.svg
  img/n/netcorecloud.com.svg
  img/o/onstar.com.svg
  img/p/particle.io.svg
  img/r/refersion.com.svg
  img/t/termsfeed.com.svg
Labels: update site, multiple sites

#7333 Add GoTo and merge join.me+LogMeIn
  entries/g/goto.com.json
  entries/j/join.me.json
  entries/l/logmein.com.json
  img/g/goto.com.svg
  img/j/join.me.svg
  img/l/logmein.com.svg
Labels: add site, remove site, multiple sites

#7336 Remove FastTech
  entries/f/fasttech.com.json
  img/f/fasttech.com.svg
Labels: remove site

#7335 Remove Comixology
  entries/c/comixology.com.json
  img/c/comixology.com.svg
Labels: remove site

#7338 Rename Blur to IronVest
  entries/a/abine.com.json
  entries/i/ironvest.com.json
  img/a/abine.com.svg
  img/i/ironvest.com.svg
Labels: update site

#7339 Update icons
  img/a/apnic.net.svg
  img/a/arcaplanet.it.svg
  img/c/conrad.com.svg
  img/g/gocardless.com.svg
  img/k/knowbe4.com.svg
  img/l/linksyssmartwifi.com.svg
  img/p/paysafecard.com.svg
  img/p/preyproject.com.svg
  img/r/rev.com.svg
  img/s/smartsimple.com.svg
  img/s/spreedly.com.svg
  img/t/threatconnect.com.svg
  img/w/webroot.com.svg
  img/w/wpscan.com.svg
Labels: update site, multiple sites

#7340 Adding General Motors
  entries/g/gm.com.json
  img/g/gm.com.svg
Labels: add site

#7346 Rename Socialbakers to Emplifi
  entries/e/emplifi.io.json
  img/e/emplifi.io.svg
  img/s/socialbakers.com.svg
Labels: update site

#7347 Rename RCN to Astound Broadband
  entries/a/astound.com.json
  img/a/astound.com.svg
  img/r/rcn.com.svg
Labels: update site

#7342 Update Banco Galicia
  entries/g/galicia.ar.json
  img/g/galicia.ar.svg
Labels: update site

#7349 Update icons
  img/f/frontier.com.svg
  img/p/purevpn.com.svg
  img/s/sdge.com.svg
  img/v/voip.ms.svg
Labels: update site, multiple sites

#7350 Add DooDrive
  entries/d/doodrive.com.json
  img/d/doodrive.com.svg
Labels: add site

#7334 Replace MeisterTask with Meister
  entries/m/meister.co.json
  entries/m/meistertask.com.json
  img/m/meister.co.svg
  img/m/meistertask.com.svg
Labels: update site

#7341 Replace Cablevisión Fibertel with Personal
  entries/c/cablevisionfibertel.com.ar.json
  entries/p/personal.com.ar.json
  img/c/cablevisionfibertel.com.ar.svg
  img/p/personal.com.ar.svg
Labels: update site

#7344 Add LEGO
  entries/l/lego.com.json
  img/l/lego.com.svg
Labels: add site

#7352 Update to namebase.io
  entries/n/namebase.io.json
Labels: update site

#7345 Update FirstBank
  entries/e/efirstbank.com.json
Labels: update site

#7354 Update 1password.com
  entries/1/1password.com.json
Labels: update site
