Repository 2factorauth/twofactorauth, pull requests merged in 2024-09, with the labels that each got.

#8182 Updated 123-Reg.co.uk to include TOTP Support
  entries/1/123-reg.co.uk.json
Labels: update site

#8183 update United
  entries/u/united.com.json
Labels: update site

#8184 Update PSNProfiles
  entries/p/psnprofiles.com.json
Labels: update site

#8185 Update ee
  entries/e/ee.co.uk.json
Labels: update site

#8188 Added additional adguard domains
  entries/a/adguard.com.json
Labels: update site

#8187 Update DeviantArt
  entries/d/deviantart.com.json
  img/d/deviantart.com.svg
Labels: update site

#8189 Add Cisco Network Academy
  entries/n/netacad.com.json
Labels: add site

#8190 Update FreshBooks
  entries/f/freshbooks.com.json
  img/f/freshbooks.com.svg
Labels: update site

#8191 Add RACQ
  entries/r/racq.com.au.json
  img/r/racq.com.au.svg
Labels: add site

#8192 Add Affinity
  entries/s/serif.com.json
  img/s/serif.com.svg
Labels: add site

#8194 Fix regions test
  tests/regions.js
Labels: bug

#8193 Add Sucuri
  entries/s/sucuri.net.json
  img/s/sucuri.net.svg
Labels: add site

#8199 Add Appodeal
  entries/a/appodeal.com.json
  img/a/appodeal.com.svg
Labels: add site

#8197 Remove Bitsight
  entries/b/bitsight.com.json
  img/b/bitsight.com.svg
Labels: remove site

#8196 Update Bupa
  img/b/bupa.com.au.svg
Labels: update site

#8198 Update McAfee
  entries/m/mcafee.com.json
  img/m/mcafee.com.svg
Labels: update site

#8201 Add Zillow
  entries/z/zillow.com.json
  img/z/zillow.com.svg
Labels: add site

#8205 Add SideQuest
  entries/s/sidequestvr.com.json
  img/s/sidequestvr.com.svg
Labels: add site

#8207 added kagi.com
  entries/k/kagi.com.json
  img/k/kagi.com.svg
Labels: add site
