Repository 2factorauth/twofactorauth, pull requests merged in 2024-06, with the labels that each got.

#8057 Add Instant Gaming
  entries/i/instant-gaming.com.json
  img/i/instant-gaming.com.svg
Labels: add site

#8062 Update Mozilla
  entries/a/accounts.firefox.com.json
  img/a/accounts.firefox.com.svg
Labels: update site

#8063 Add Aqara
  entries/a/aqara.com.json
  img/a/aqara.com.svg
Labels: add site

#8059 Add Origin Energy
  entries/o/originenergy.com.au.json
  img/o/originenergy.com.au.svg
Labels: add site

#8064 Add Aesop
  entries/a/aesop.com.json
  img/a/aesop.com.svg
Labels: add site

#8065 Add OVO Energy
  entries/o/ovoenergy.com.json
  img/o/ovoenergy.com.svg
Labels: add site

#8066 Add Red Energy
  entries/r/redenergy.com.au.json
  img/r/redenergy.com.au.svg
Labels: add site

#8067 Update Binge
  entries/b/binge.com.au.json
  entries/h/hubbl.com.au.json
  img/b/binge.com.au.svg
  img/h/hubbl.com.au.svg
Labels: update site

#8060 Add Energy Australia
  entries/e/energyaustralia.com.au.json
  img/e/energyaustralia.com.au.png
Labels: add site

#8072 Add ASB Bank
  entries/a/asb.co.nz.json
  img/a/asb.co.nz.svg
Labels: add site

#8074 Update Up Bank
  entries/u/up.com.au.json
Labels: update site

#8071 Update CommBank
  entries/c/commbank.com.au.json
Labels: update site

#8076 Add IMB Bank
  entries/i/imb.com.au.json
  img/i/imb.com.au.svg
Labels: add site

#8075 Add AMP
  entries/a/amp.com.au.json
  img/a/amp.com.au.svg
Labels: add site

#8077 Add Rabobank AU
  entries/r/rabobank.com.au.json
  entries/r/rabobank.nl.json
  img/r/rabobank.nl.svg
  img/r/rabobank.svg
Labels: add site

#8078 Add MyState Bank
  entries/m/mystate.com.au.json
  img/m/mystate.com.au.svg
Labels: add site

#8079 Add Adelaide Bank
  entries/a/adelaidebank.com.au.json
  img/a/adelaidebank.com.au.svg
Labels: add site

#8080 Add Bank of Melbourne
  entries/b/bankofmelbourne.com.au.json
  img/b/bankofmelbourne.com.au.svg
Labels: add site

#8081 Add BankSA
  entries/b/banksa.com.au.json
  img/b/banksa.com.au.svg
Labels: add site

#8082 Add Beyond Bank
  entries/b/beyondbank.com.au.json
  img/b/beyondbank.com.au.svg
Labels: add site

#8085 Add St.George Bank
  entries/s/stgeorge.com.au.json
  img/s/stgeorge.com.au.svg
Labels: add site

#8083 Add Teachers Mutual Bank
  entries/t/tmbank.com.au.json
  img/t/tmbank.com.au.svg
Labels: add site

#8087 Add Patient Access
  entries/p/patientaccess.com.json
  img/p/patientaccess.com.svg
Labels: add site

#8084 Add Suncorp Bank & Insurance
  entries/s/suncorp.com.au.json
  entries/s/suncorpbank.com.au.json
  img/s/suncorp.svg
Labels: add site, multiple sites

#8088 Add AAMI
  entries/a/aami.com.au.json
  img/a/aami.com.au.svg
Labels: add site

#8089 Edit Huggingface
  entries/h/huggingface.co.json
Labels: update site

#8090 Replace CircleCI with CF Worker
  .circleci/config.yml
  .github/workflows/pull_request.yml
  tests/facebook.rb
  tests/similarweb.rb
  tests/twitter.rb
Labels: enhancement

#8094 Add leboncoin
  entries/l/leboncoin.fr.json
  img/l/leboncoin.fr.svg
Labels: add site

#8092 Add Clubhouse
  entries/c/clubhouse.com.json
  img/c/clubhouse.com.svg
Labels: add site

#8097 Add corporatefinanceinstitute.com
  entries/c/corporatefinanceinstitute.com.json
  img/c/corporatefinanceinstitute.com.svg
Labels: add site

#8099 Add Youi Insurance
  entries/y/youi.com.au.json
  img/y/youi.com.au.svg
Labels: add site

#8096 Split GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  .github/workflows/repository.yml
  package.json
  tests/language-codes.rb
  tests/languages.js
  tests/region-codes.rb
  tests/regions.js
  tests/validate-fs.sh
Labels: enhancement

#8093 Add Rapidgator
  entries/r/rapidgator.net.json
  img/r/rapidgator.net.svg
Labels: add site

#8101 Migrate Ruby tests (part 2)
  .github/workflows/pull_request.yml
  Gemfile
  package.json
  tests/categories.js
  tests/images.js
  tests/json.js
  tests/quality-checks.rb
  tests/schema.json
  tests/validate-categories.rb
  tests/validate-images.rb
  tests/validate-json.rb
Labels: enhancement

#8098 Add Everyday Insurance
  entries/i/insurance.everyday.com.au.json
  img/i/insurance.everyday.com.au.svg
Labels: add site

#8102 Update Withings
  entries/w/withings.com.json
  img/w/withings.com.svg
Labels: update site

#8104 Format tests
  tests/categories.js
  tests/images.js
  tests/json.js
  tests/languages.js
  tests/regions.js
Labels: enhancement

#8103 Add an "Insurance" category
  CONTRIBUTING.md
  entries/a/aami.com.au.json
  entries/a/admiral.com.json
  entries/a/aetna.com.json
  entries/a/allianz.de.json
  entries/a/anthem.com.json
  entries/a/aok.de.json
  entries/a/australiansuper.com.json
  entries/b/baloise.ch.json
  entries/b/barmenia.de.json
  entries/b/bupa.com.au.json
  entries/e/emma.ca.json
  entries/g/geico.com.json
  entries/g/gerberlife.com.json
  entries/h/healthcare.gov.json
  entries/h/huk.de.json
  entries/h/huk24.de.json
  entries/h/humana.com.json
  entries/i/independer.nl.json
  entries/i/insurance.everyday.com.au.json
  entries/m/my.cigna.com.json
  entries/n/nbc.ca.json
  entries/n/noridianmedicareportal.com.json
  entries/n/northwesternmutual.com.json
  entries/p/principal.com.json
  entries/p/progressive.com.json
  entries/r/rest.com.au.json
  entries/s/statefarm.com.json
  entries/s/suncorp.com.au.json
  entries/s/swisslife.ch.json
  entries/t/tk.de.json
  entries/t/trustage.com.json
  entries/v/vitality.co.uk.json
  entries/y/youi.com.au.json
Labels: update site, add category, multiple sites

#8105 Change frontend repo url
  tests/categories.js
Labels: bug

#8108 Add Dodo
  entries/d/dodo.com.json
  img/d/dodo.com.svg
Labels: add site

#8110 Add Tangerine Telecom
  entries/t/tangerinetelecom.com.au.json
  img/t/tangerinetelecom.com.au.svg
Labels: add site

#8107 Add Circles Life
  entries/c/circles.life.json
  img/c/circles.life.svg
Labels: add site

#8113 Clean up workflows
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  tests/images.js
  tests/validate-urls.rb
Labels: enhancement

#8111 Add TPG
  entries/t/tpg.com.au.json
  img/t/tpg.com.au.svg
Labels: add site

#8106 Add Boost Mobile
  entries/b/boost.com.au.json
  img/b/boost.com.au.svg
Labels: add site
