Repository 2factorauth/twofactorauth, pull requests merged in 2024-01, with the labels that each got.

#7879 Add HuggingFace
  entries/h/huggingface.co.json
  img/h/huggingface.co.svg
Labels: add site

#7881 Add Lunch Money
  entries/l/lunchmoney.app.json
  img/l/lunchmoney.app.png
Labels: add site

#7880 Add Cineplex
  entries/c/cineplex.com.json
  img/c/cineplex.com.svg
Labels: add site

#7884 Add LIDL [DE]
  entries/l/lidl.de.json
  img/l/lidl.de.svg
Labels: add site

#7886 Add Teachable
  entries/t/teachable.com.json
  img/t/teachable.com.svg
Labels: add site

#7889 Add Lifesum
  entries/l/lifesum.com.json
  img/l/lifesum.com.svg
Labels: add site

#7888 Add Koho
  entries/k/koho.ca.json
  img/k/koho.ca.svg
Labels: add site

#7892 Update Buy Me a Coffee
  entries/b/buymeacoffee.com.json
Labels: update site

#7893 Add Cengage
  entries/c/cengage.com.json
  img/c/cengage.com.svg
Labels: add site

#7896 Add SingleKey ID
  entries/s/singlekey-id.com.json
  img/s/singlekey-id.com.svg
Labels: add site

#7894 Set issue titles using action
  .github/ISSUE_TEMPLATE/01-add-site-with-2fa.yml
  .github/ISSUE_TEMPLATE/02-add-site-without-2fa.yml
  .github/workflows/issues.yml
Labels: enhancement

#7900 Update Clio
  entries/c/clio.com.json
Labels: update site

#7899 Update Bubble
  entries/b/bubble.io.json
Labels: update site
