Repository 2factorauth/twofactorauth, pull requests merged in 2024-04, with the labels that each got.

#7973 Update AOL Mail
  entries/m/mail.aol.com.json
Labels: update site

#7971 Update Miro
  entries/m/miro.com.json
Labels: update site

#7975 Update Disney+
  img/d/disneyplus.com.svg
Labels: update site

#7976 Add PowerSchool
  entries/p/powerschool.com.json
  img/p/powerschool.com.svg
Labels: add site

#7978 Add Dinero
  entries/d/dinero.dk.json
  img/d/dinero.dk.svg
Labels: add site

#7979 Add MangaDex
  entries/m/mangadex.org.json
  img/m/mangadex.org.svg
Labels: add site

#7983 Update Walmart Canada
  entries/w/walmart.ca.json
Labels: update site

#7984 Add Zeplin
  entries/z/zeplin.io.json
  img/z/zeplin.io.svg
Labels: add site

#7985 Update issue-title-action
  .github/workflows/issues.yml
Labels: enhancement

#7987 Update Minds
  entries/m/minds.com.json
Labels: update site

#7988 Add BenefitsCal
  entries/b/benefitscal.com.json
  img/b/benefitscal.com.svg
Labels: add site

#7991 Add Accountable
  entries/a/accountable.eu.json
  img/a/accountable.eu.svg
Labels: add site

#7996 Update Marriott Bonvoy
  entries/m/marriott.com.json
Labels: update site

#7997 Update Bluesky
  entries/b/bsky.app.json
Labels: update site

#7999 Add Blackbaud
  entries/b/blackbaud.com.json
  img/b/blackbaud.com.png
Labels: add site

#8004 Update SendGrid
  img/s/sendgrid.com.svg
Labels: update site

#8003 Update GroupMe
  entries/g/groupme.com.json
  img/g/groupme.com.svg
Labels: update site

#8000 Update Beeper
  img/b/beeper.com.svg
Labels: update site

#8009 Add UBank
  entries/u/ubank.com.au.json
  img/u/ubank.com.au.svg
Labels: add site

#8008 Add ME Bank
  entries/m/mebank.com.au.json
  img/m/mebank.com.au.svg
Labels: add site

#8007 Update AU Banks
  entries/m/macquarie.com.au.json
  entries/n/nab.com.au.json
  img/a/anz.com.au.svg
  img/m/macquarie.com.au.svg
  img/n/nab.com.au.svg
  img/u/up.com.au.svg
  img/w/westpac.com.au.svg
Labels: update site, multiple sites

#8010 Remove Google Domains
  entries/d/domains.google.com.json
  img/d/domains.google.com.svg
Labels: remove site

#8011 Update OnlyDomains
  entries/o/onlydomains.com.json
Labels: update site

#8002 Add Sign.Plus
  entries/s/sign.plus.json
  img/s/sign.plus.svg
Labels: add site

#8001 Update Fax.Plus
  entries/f/fax.plus.json
  img/f/fax.plus.svg
Labels: update site
