Repository 2factorauth/twofactorauth, pull requests merged in 2024-07, with the labels that each got.

#8119 Add RACV
  entries/r/racv.com.au.json
  img/r/racv.com.au.svg
Labels: add site

#8118 Updated of LabCorp Patient entry
  entries/p/patient.labcorp.com.json
Labels: update site

#8122 Remove Caffeine
  entries/c/caffeine.tv.json
  img/c/caffeine.tv.svg
Labels: remove site

#8126 Remove Skiff
  entries/s/skiff.com.json
  img/s/skiff.com.svg
Labels: remove site

#8125 Add Glovo
  entries/g/glovoapp.com.json
  img/g/glovoapp.com.svg
Labels: add site

#8127 Rewrite scripts
  .github/workflows/publish.yml
  Gemfile
  package.json
  scripts/APIv3.js
  scripts/APIv3.rb
  scripts/Algolia.js
  scripts/Algolia.rb
  scripts/Sign.rb
  scripts/Sign.sh
  tests/validate-fs.sh
Labels: enhancement

#8129 Remove LocalMonero
  entries/l/localmonero.co.json
  img/l/localmonero.co.svg
Labels: remove site

#8128 Rewrite final Ruby tests
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  .prettierignore
  Gemfile
  package.json
  tests/svg-lint.rb
  tests/svg.js
  tests/urls.js
  tests/validate-fs.sh
  tests/validate-urls.rb
Labels: enhancement

#8132 Add railway.app
  entries/r/railway.app.json
  img/r/railway.app.svg
Labels: add site

#8133 Update SoFi
  entries/s/sofi.com.json
Labels: update site

#8137 Markdown changes
  LICENSE.md
  README.md
Labels: enhancement

#8136 Create API v4 & rework API v3
  .github/workflows/publish.yml
  .prettierrc.json
  entries/3/34SP.com.json
  img/3/34SP.com.svg
  package.json
  scripts/APIv3.js
  scripts/APIv4.js
  tests/json.js
  tests/schemas/APIv3.json
  tests/schemas/APIv4.json
  tests/schemas/entries.json
Labels: enhancement

#8140 Update Bunnings
  entries/b/bunnings.com.au.json
Labels: update site

#8141 Add API directory test
  .github/workflows/publish.yml
  tests/api_files.sh
Labels: enhancement

#8138 Add HotDoc
  entries/h/hotdoc.com.au.json
  img/h/hotdoc.com.au.svg
Labels: add site

#8143 Update VMware
  entries/b/broadcom.com.json
  entries/v/vmware.com.json
  img/b/broadcom.com.svg
  img/v/vmware.com.svg
Labels: update site
