Repository 2factorauth/twofactorauth, pull requests merged in 2025-07, with the labels that each got.

#8454 Update CommBank
  entries/c/commbank.com.au.json
Labels: update site

#8459 Remove cohost
  entries/c/cohost.org.json
  img/c/cohost.org.svg
Labels: remove site

#8458 Added Trovi
  entries/t/trovi.sk.json
  img/t/trovi.sk.svg
Labels: add site

#8461 Add Crowdcube
  entries/c/crowdcube.com.json
  img/c/crowdcube.com.png
Labels: add site
