Repository 2factorauth/twofactorauth, pull requests merged in 2025-05, with the labels that each got.

#8415 Add Vinted
  entries/v/vinted.com.json
  img/v/vinted.com.svg
Labels: add site

#8417 Update FuseBase
  entries/n/nimbusweb.me.json
  img/n/nimbusweb.me.svg
Labels: update site

#8419 Add New York University
  entries/n/nyu.edu.json
  img/n/nyu.edu.svg
Labels: add site

#8421 Update JetBlue
  entries/j/jetblue.com.json
Labels: update site

#8418 Add the rest of the University of California system
  entries/b/berkeley.edu.json
  entries/u/ucdavis.edu.json
  entries/u/uci.edu.json
  entries/u/ucla.edu.json
  entries/u/ucr.edu.json
  entries/u/ucsb.edu.json
  entries/u/ucsc.edu.json
  entries/u/ucsd.edu.json
  entries/u/ucsf.edu.json
  img/b/berkeley.edu.png
  img/u/ucdavis.edu.svg
  img/u/uci.edu.svg
  img/u/ucla.edu.svg
  img/u/ucr.edu.png
  img/u/ucsb.edu.png
  img/u/ucsc.edu.svg
  img/u/ucsd.edu.svg
  img/u/ucsf.edu.svg
Labels: add site, update site, multiple sites

#8426 Add Georgetown University
  entries/g/georgetown.edu.json
  img/g/georgetown.edu.png
Labels: add site

#8422 Add Texas A&M
  entries/t/tamu.edu.json
  img/t/tamu.edu.svg
Labels: add site

#8424 Add Columbia University
  entries/c/columbia.edu.json
  img/c/columbia.edu.svg
Labels: add site

#8423 Remove First Republic Bank
  entries/f/firstrepublic.com.json
  img/f/firstrepublic.com.svg
Labels: remove site

#8429 Update GOG.com
  entries/g/gog.com.json
Labels: add site

#8430 Update 2FA options for AFCU and MyChart
  entries/a/americafirst.com.json
  entries/m/mychart.org.json
  img/m/mychart.org.svg
Labels: update site, multiple sites

#8432 feat: split Vend and Schibsted
  entries/s/schibsted.com.json
  entries/v/vend.com.json
  img/v/vend.com.svg
Labels: add site, update site, multiple sites

#8433 Add Gumlet
  entries/g/gumlet.com.json
  img/g/gumlet.com.svg
Labels: add site

#8431 Update Profil Zaufany
  entries/p/pz.gov.pl.json
Labels: update site
