Repository 2factorauth/twofactorauth, pull requests merged in 2025-01, with the labels that each got.

#8354 Remove Polywork
  entries/p/polywork.com.json
  img/p/polywork.com.svg
Labels: remove site

#8353 Add travelers.com
  entries/t/travelers.com.json
  img/t/travelers.com.svg
Labels: add site

#8355 Add feedly.com.json
  entries/f/feedly.com.json
  img/f/feedly.com.svg
Labels: add site

#8356 Update Roku
  entries/r/roku.com.json
Labels: update site

#8352 Add ING Italia
  entries/i/ing.it.json
Labels: add site

#8357 Update Developer site logos
  img/a/alchemy.com.svg
  img/g/goteleport.com.svg
Labels: update site, multiple sites

#8359 Update Tower FCU
  entries/t/towerfcu.org.json
Labels: update site

#8361 Add Universitat de Barcelona
  entries/u/ub.edu.json
  img/u/ub.edu.png
Labels: add site

#8365 Update Signal
  entries/s/signal.org.json
  img/s/signal.org.svg
Labels: update site

#8362 Add musicMagpie
  entries/m/musicmagpie.co.uk.json
  img/m/musicmagpie.co.uk.svg
Labels: add site

#8366 Update Front
  entries/f/front.com.json
  entries/f/frontapp.com.json
  img/f/front.com.svg
  img/f/frontapp.com.svg
Labels: update site

#8369 Add Wallapop
  entries/w/wallapop.com.json
  img/w/wallapop.com.svg
Labels: add site

#8364 Update banking category
  entries/b/bankera.com.json
  entries/c/credit-suisse.com.json
  entries/p/pleo.io.json
  img/c/credit-suisse.com.svg
Labels: update site, remove site, multiple sites

#8370 Add Doctolib
  entries/d/doctolib.it.json
  img/d/doctolib.it.svg
Labels: add site

#8367 Update YNAB
  entries/y/ynab.com.json
  entries/y/youneedabudget.com.json
  img/y/ynab.com.svg
  img/y/youneedabudget.com.svg
Labels: update site

#8372 Add Subito.it
  entries/s/subito.it.json
  img/s/subito.it.svg
Labels: add site

#8363 Create Travel category
  CONTRIBUTING.md
  entries/a/aa.com.json
  entries/a/aerolineas.com.ar.json
  entries/a/airbnb.com.json
  entries/a/aircanada.com.json
  entries/a/alaskaair.com.json
  entries/a/allegiantair.com.json
  entries/b/bahn.com.json
  entries/b/booking.com.json
  entries/b/britishairways.com.json
  entries/c/cathaypacific.com.json
  entries/c/clearme.com.json
  entries/c/copaair.com.json
  entries/c/couchsurfing.com.json
  entries/d/delta.com.json
  entries/d/despegar.com.json
  entries/e/easyjet.com.json
  entries/e/eurowings.com.json
  entries/f/fahren-lernen.de.json
  entries/f/finnair.com.json
  entries/f/flybreeze.com.json
  entries/f/flyfrontier.com.json
  entries/f/flygbra.se.json
  entries/f/flyingblue.com.json
  entries/f/flysas.com.json
  entries/f/flyxo.com.json
  entries/h/hawaiianairlines.com.json
  entries/h/hilton.com.json
  entries/h/hostelworld.com.json
  entries/h/hyatt.com.json
  entries/i/ihg.com.json
  entries/j/jetblue.com.json
  entries/j/jetstar.com.json
  entries/l/latam.com.json
  entries/l/lufthansa.com.json
  entries/m/marriott.com.json
  entries/m/melia.com.json
  entries/n/nh-hotels.com.json
  entries/n/norwegian.com.json
  entries/q/qantas.com.json
  entries/r/ryanair.com.json
  entries/s/skanetrafiken.se.json
  entries/s/southwest.com.json
  entries/s/spirit.com.json
  entries/t/travala.com.json
  entries/t/tripit.com.json
  entries/t/turo.com.json
  entries/u/united.com.json
  entries/v/virginatlantic.com.json
  entries/v/vrbo.com.json
  entries/w/westjet.com.json
  entries/w/wyndhamhotels.com.json
  img/f/flygbra.se.svg
  tests/categories.json
Labels: add category, multiple sites

#8373 Add TAB
  entries/t/tab.com.au.json
  img/t/tab.com.au.svg
Labels: add site

#8374 Add NAVER
  entries/n/naver.com.json
  img/n/naver.com.svg
Labels: add site

#8375 Update Doctolib
  entries/d/doctolib.it.json
Labels: update site

#8377 Update Microsoft 365
  entries/m/m365.cloud.microsoft.json
  img/m/m365.cloud.microsoft.svg
  img/o/office.com.svg
Labels: update site

#8379 Update Zoom
  entries/z/zoom.us.json
  img/z/zoom.us.svg
Labels: update site
