Repository 2factorauth/twofactorauth, pull requests merged in 2025-06, with the labels that each got.

#8434 Add Lone Star College
  entries/l/lonestar.edu.json
  img/l/lonestar.edu.svg
Labels: add site

#8436 zoopla.co.uk
  entries/z/zoopla.co.uk.json
  img/z/zoopla.co.uk.svg
Labels: add site

#8446 Add TFA info and documentation for impots.gouv.fr
  entries/i/impots.gouv.fr.json
Labels: update site

#8438 Update Hilton
  entries/h/hilton.com.json
  img/h/hilton.com.svg
Labels: update site

#8440 Remove InVision
  entries/i/invisionapp.com.json
  img/i/invisionapp.com.svg
Labels: remove site

#8442 Update Robinhood
  entries/r/robinhood.com.json
Labels: update site

#8443 Remove 000webhost
  entries/0/000webhost.com.json
  img/0/000webhost.com.svg
Labels: remove site

#8447 Add Affinity Federal Credit Union (affinityfcu.com)
  entries/a/affinityfcu.com.json
  img/a/affinityfcu.com.png
Labels: add site

#8449 Add Choko.Link
  entries/c/choko.link.json
  img/c/choko.link.svg
Labels: add site

#8451 Update The Iconic
  entries/t/theiconic.com.au.json
Labels: update site
